-- U2 · SELECT-ONLY POSTCONDITION.  Run only after a U2 execution attempt.  0 DDL · 0 DML.
-- Asserts the converged four-policy architecture and never asks which path produced it, so it
-- passes identically after APPLIED and after RECOGNIZED.
--
-- ★ RAW relacl IS NOT A PORTABLE INVARIANT, AND THIS FILE ONCE TREATED IT AS ONE. The gating row
--   `assets_relacl = (null)` was derived from a LOCAL vanilla-Postgres bootstrap, where a table with
--   no grants has a NULL ACL. On hosted Supabase the platform's own default privileges grant Dxtm
--   (TRUNCATE/REFERENCES/TRIGGER/MAINTAIN) to anon/authenticated/service_role at CREATE TABLE time,
--   so relacl is populated on every public table. R02_6 had ALREADY proved this hosted — 41 of 41
--   public tables — and this row contradicted that committed evidence. It failed a correct U2 run.
--   The ACL text is also PG-version dependent: `m` (MAINTAIN) exists only on PG17+, and the local
--   containers are PG16, so the string can never agree across the two environments.
--
-- ★ THE INVARIANT U2 ACTUALLY OWNS is that U2 widened no CLIENT ROW-DML privilege. That is asserted
--   semantically, per role, via has_table_privilege. Dxtm is recorded, never gated: it belongs to U3,
--   and gating either way would be wrong — demanding its presence breaks after U3 removes it,
--   demanding its absence breaks today.
with chk(class, check_name, expected, actual, gating) as (values
  ('CONTROL','pg_policy_readable',$$true$$,(select (count(*)>=0)::text from pg_catalog.pg_policy),true),
  ('CONTROL','row_dml_instrument_live',$$true$$,(select has_table_privilege($$authenticated$$,$$public.estate_assets$$,$$SELECT$$)::text),true),
  ('DELTA','assets_policy_count',$$4$$,(select count(*)::text from pg_catalog.pg_policy pol join pg_catalog.pg_class c on c.oid=pol.polrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname=$$public$$ and c.relname=$$assets$$),true),
  ('DELTA','assets_read_intact',$$1$$,(select count(*)::text from pg_catalog.pg_policy pol join pg_catalog.pg_class c on c.oid=pol.polrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname=$$public$$ and c.relname=$$assets$$ and pol.polname='assets_read' and pol.polcmd::text='r' and pol.polpermissive and pol.polroles='{0}'::oid[] and pg_catalog.pg_get_expr(pol.polqual,pol.polrelid)='((owner_id = auth.uid()) OR is_estate_member(estate_id))' and pol.polwithcheck is null),true),
  ('DELTA','assets_write_hardened',$$1$$,(select count(*)::text from pg_catalog.pg_policy pol join pg_catalog.pg_class c on c.oid=pol.polrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname=$$public$$ and c.relname=$$assets$$ and pol.polname='assets_write' and pol.polcmd::text='*' and pol.polpermissive and pol.polroles='{0}'::oid[] and pg_catalog.pg_get_expr(pol.polqual,pol.polrelid)='(owner_id = auth.uid())' and pg_catalog.pg_get_expr(pol.polwithcheck,pol.polrelid)='((owner_id = auth.uid()) AND is_estate_owner(estate_id))'),true),
  ('DELTA','insert_restrictive_exact',$$1$$,(select count(*)::text from pg_catalog.pg_policy pol join pg_catalog.pg_class c on c.oid=pol.polrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname=$$public$$ and c.relname=$$assets$$ and pol.polname='assets_insert_require_estate_owner' and pol.polcmd::text='a' and not pol.polpermissive and pol.polroles='{0}'::oid[] and pol.polqual is null and pg_catalog.pg_get_expr(pol.polwithcheck,pol.polrelid)='is_estate_owner(estate_id)'),true),
  ('DELTA','update_restrictive_exact',$$1$$,(select count(*)::text from pg_catalog.pg_policy pol join pg_catalog.pg_class c on c.oid=pol.polrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname=$$public$$ and c.relname=$$assets$$ and pol.polname='assets_update_require_estate_owner' and pol.polcmd::text='w' and not pol.polpermissive and pol.polroles='{0}'::oid[] and pol.polqual is null and pg_catalog.pg_get_expr(pol.polwithcheck,pol.polrelid)='is_estate_owner(estate_id)'),true),
  ('DELTA','no_extra_assets_policy',$$0$$,(select count(*)::text from pg_catalog.pg_policy pol join pg_catalog.pg_class c on c.oid=pol.polrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname=$$public$$ and c.relname=$$assets$$ and pol.polname not in ('assets_read','assets_write','assets_insert_require_estate_owner','assets_update_require_estate_owner')),true),
  ('DELTA','no_permissive_beyond_two',$$2$$,(select count(*)::text from pg_catalog.pg_policy pol join pg_catalog.pg_class c on c.oid=pol.polrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname=$$public$$ and c.relname=$$assets$$ and pol.polpermissive),true),
  ('DELTA','restrictive_layer_is_two',$$2$$,(select count(*)::text from pg_catalog.pg_policy pol join pg_catalog.pg_class c on c.oid=pol.polrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname=$$public$$ and c.relname=$$assets$$ and not pol.polpermissive),true),
  ('RATCHET','client_row_dml_tables',$$0$$,(select count(*)::text from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace, (select rolname from pg_roles where rolname in ($$anon$$,$$authenticated$$,$$service_role$$)) r where n.nspname=$$public$$ and c.relname=$$assets$$ and (has_table_privilege(r.rolname,c.oid,$$SELECT$$) or has_table_privilege(r.rolname,c.oid,$$INSERT$$) or has_table_privilege(r.rolname,c.oid,$$UPDATE$$) or has_table_privilege(r.rolname,c.oid,$$DELETE$$))),true),
  ('RATCHET','assets_anon_row_dml',$$0$$,(select (case when has_table_privilege($$anon$$,c.oid,$$SELECT$$) then 1 else 0 end + case when has_table_privilege($$anon$$,c.oid,$$INSERT$$) then 1 else 0 end + case when has_table_privilege($$anon$$,c.oid,$$UPDATE$$) then 1 else 0 end + case when has_table_privilege($$anon$$,c.oid,$$DELETE$$) then 1 else 0 end)::text from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname=$$public$$ and c.relname=$$assets$$),true),
  ('RATCHET','assets_authenticated_row_dml',$$0$$,(select (case when has_table_privilege($$authenticated$$,c.oid,$$SELECT$$) then 1 else 0 end + case when has_table_privilege($$authenticated$$,c.oid,$$INSERT$$) then 1 else 0 end + case when has_table_privilege($$authenticated$$,c.oid,$$UPDATE$$) then 1 else 0 end + case when has_table_privilege($$authenticated$$,c.oid,$$DELETE$$) then 1 else 0 end)::text from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname=$$public$$ and c.relname=$$assets$$),true),
  ('RATCHET','assets_service_role_row_dml',$$0$$,(select (case when has_table_privilege($$service_role$$,c.oid,$$SELECT$$) then 1 else 0 end + case when has_table_privilege($$service_role$$,c.oid,$$INSERT$$) then 1 else 0 end + case when has_table_privilege($$service_role$$,c.oid,$$UPDATE$$) then 1 else 0 end + case when has_table_privilege($$service_role$$,c.oid,$$DELETE$$) then 1 else 0 end)::text from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname=$$public$$ and c.relname=$$assets$$),true),
  ('PLATFORM_BASELINE','assets_client_non_dml_privileges',$$__RECORD__$$,(select coalesce(string_agg(x.rolname||$$=$$||x.privs,$$, $$ order by x.rolname),$$(none)$$) from (select pg_catalog.pg_get_userbyid(a.grantee) rolname, string_agg(a.privilege_type,$$+$$ order by a.privilege_type) privs from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace, aclexplode(c.relacl) a where n.nspname=$$public$$ and c.relname=$$assets$$ and pg_catalog.pg_get_userbyid(a.grantee) in ($$anon$$,$$authenticated$$,$$service_role$$) group by 1) x),false),
  ('PLATFORM_BASELINE','assets_relacl',$$__RECORD__$$,(select coalesce((select c.relacl::text from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='assets'),'(null)')),false),
  ('UNCHANGED','public_policies_total',$$38$$,(select count(*)::text from pg_catalog.pg_policies where schemaname='public'),true),
  ('UNCHANGED','public_tables',$$41$$,(select count(*)::text from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r'),true),
  ('UNCHANGED','public_functions',$$147$$,(select count(*)::text from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid=p.pronamespace where n.nspname='public'),true),
  ('UNCHANGED','migration_metadata_tables',$$0$$,(select count(*)::text from information_schema.tables where table_schema='supabase_migrations'),true),
  ('RECORD','assets_policy_fingerprint',$$__RECORD__$$,(select coalesce(md5(string_agg(pol.polname||$$|$$||pol.polcmd::text||$$|$$||pol.polpermissive::text||$$|$$||(case when pol.polroles=$${0}$$::oid[] then $$PUBLIC$$ else $$SCOPED$$ end)||$$|$$||coalesce(pg_catalog.pg_get_expr(pol.polqual,pol.polrelid),$$~$$)||$$|$$||coalesce(pg_catalog.pg_get_expr(pol.polwithcheck,pol.polrelid),$$~$$),$$,$$ order by pol.polname)),$$NONE$$) from pg_catalog.pg_policy pol join pg_catalog.pg_class c on c.oid=pol.polrelid join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname=$$public$$ and c.relname=$$assets$$),false)
)
select class, check_name, expected, actual,
       case when not gating then 'RECORD' when actual is not distinct from expected then 'PASS' else 'FAIL' end as verdict
from chk
union all
select 'OVERALL','u2_postcheck',$$ALL_PASS$$,
  (select case when count(*) filter (where gating and actual is distinct from expected)=0 then 'ALL_PASS' else 'FAIL:'||count(*) filter (where gating and actual is distinct from expected)::text end from chk),
  (select case when count(*) filter (where gating and actual is distinct from expected)=0 then 'U2_APPLIED_AND_VERIFIED' else 'HALT — INVESTIGATE' end from chk);
