-- GENERATED by scripts/buildEstateAssetBundle.mjs — DO NOT EDIT.
-- Edit the sources instead:
--   db/migrations/0048_20260810_estate_assets.sql
--   db/functions/estate_asset_rpcs.sql
--
-- Paste this whole file into the Supabase SQL editor and run it once.
-- The migration is idempotent and every function is CREATE OR REPLACE, so re-running is safe.

-- ==== db/migrations/0048_20260810_estate_assets.sql ===============================================
-- db/migrations/0048_20260810_estate_assets.sql
--
-- PHASE 9 — the MANUAL estate asset inventory. An owner records what the estate actually consists of:
-- accounts, property, business interests, digital assets and physical valuables — without any
-- dependency on financial aggregation.
--
-- ★ WHY THIS IS A NEW TABLE AND NOT A COLUMN ON normalized_assets.
--   `normalized_assets` (0007) is AGGREGATOR-SHAPED and aggregator-OWNED:
--     * `connection_id` is NOT NULL and FKs to `connections`, so a manual asset has no legal row;
--     * a connection refresh performs DELETE + INSERT for the connection's rows, so anything manual
--       parked there would be destroyed by a Plaid sync — silently, and only for users who happen to
--       link an account.
--   Manual assets are therefore first-class in their own table, exactly as the product treats them.
--
-- ★ AAL2 POSTURE — OWNER-APPROVED RULING (Phase 9), AND IT LOOSENS NOTHING.
--   `list_estate_assets` keeps `require_aal2()` for aggregator-sourced exact values: UNCHANGED.
--   Cross-person disclosure keeps its gate: UNCHANGED (and no non-owner can read this table at all —
--   see the RLS note below). What is new is that an owner may read the values THEY THEMSELVES TYPED
--   at aal1, because re-proving identity to read back your own typing protects nothing, and the app
--   has no in-app TOTP enrollment flow, so the alternative was an enrollment wall in front of the
--   MVP's core feature.
--
-- ★ NON-OWNERS SEE NOTHING HERE, DELIBERATELY, AND THAT IS THE WHOLE PHASE-9 DISCLOSURE STORY FOR
--   MANUAL ASSETS. `access_grants` scopes a grant by an XOR of `document_id` / `category`; adding an
--   asset scope means altering that XOR and the write-time ceiling trigger keyed on `document_id` —
--   a change to the security-critical centre of the disclosure model. That is NOT smuggled into an
--   inventory slice. Manual assets are owner-only until per-asset grants are designed on their own
--   merits. Default-deny is the safe direction, and it is enforced structurally by RLS.
--
-- ★ DELETION — OWNER-APPROVED RULING (Phase 9): SOFT delete (archive) with restore. Documents keep
--   their locked HARD-delete design because their irreversibility is justified by a storage-byte
--   purge; a manual asset has no bytes of its own, so an accidental deletion during bulk inventory
--   entry is recoverable. Archiving an asset detaches no document and purges nothing.
--
-- Idempotent; safe to re-run.

begin;

-- =============================================================================================
-- 1 · estate_asset_category — the COARSE server-authoritative vocabulary
-- =============================================================================================
-- Born clean, exactly like `document_subtype` (0036): RLS on, NO client grants. The read path is
-- get_estate_asset_taxonomy(). A client union here would be a second source of truth that drifts the
-- moment a category is added — the taxonomy rule this codebase learned from `subtype: 'other'`.
create table if not exists public.estate_asset_category (
  value        text        primary key,
  display_name text        not null,
  description  text,
  sort_order   int         not null default 0,
  icon_key     text,
  -- PRESENTATION metadata only, never authorization: it tells the client which optional fields are
  -- worth offering (a location hint for a ring, an institution for a brokerage account).
  is_physical  boolean     not null default false,
  is_active    boolean     not null default true,
  created_at   timestamptz not null default now()
);
alter table public.estate_asset_category enable row level security;

-- =============================================================================================
-- 2 · estate_asset_subtype — the FINE vocabulary, parented to a category
-- =============================================================================================
-- Mirrors document_subtype → document_type: persist-both, so a client that does not recognise a new
-- subtype can still group by its parent category rather than losing the row.
create table if not exists public.estate_asset_subtype (
  subtype         text        primary key,
  parent_category text        not null references public.estate_asset_category(value),
  display_name    text        not null,
  description     text,
  sort_order      int         not null default 0,
  icon_key        text,
  is_active       boolean     not null default true,
  created_at      timestamptz not null default now()
);
create index if not exists estate_asset_subtype_parent_idx
  on public.estate_asset_subtype (parent_category);
alter table public.estate_asset_subtype enable row level security;

-- =============================================================================================
-- 3 · SEED — the nine categories from the product definition
-- =============================================================================================
insert into public.estate_asset_category (value, display_name, description, sort_order, icon_key, is_physical) values
  ('bankAccount',      'Bank or financial account', 'Chequing, savings, term deposits and similar cash holdings.', 1, 'financial', false),
  ('investment',       'Investment',                'Brokerage accounts and directly held securities.',            2, 'financial', false),
  ('retirement',       'Retirement or pension',     'Workplace pensions, personal retirement accounts, annuities.', 3, 'financial', false),
  ('insurance',        'Insurance',                 'Policies that pay out to the estate or to a named person.',   4, 'authority', false),
  ('realEstate',       'Real estate',               'Land and buildings, wherever they are held.',                  5, 'property',  false),
  ('businessInterest', 'Business interest',         'Ownership in a company, partnership or practice.',             6, 'authority', false),
  ('digitalAsset',     'Crypto or digital asset',   'Exchange accounts, self-custody wallets and digital property.', 7, 'financial', false),
  ('physicalValuable', 'Physical valuable',         'Items whose value is in the object itself.',                   8, 'property',  true),
  ('otherAsset',       'Other asset',               'Anything the other categories do not describe.',               9, 'document',  false)
on conflict (value) do update set
  display_name = excluded.display_name,
  description  = excluded.description,
  sort_order   = excluded.sort_order,
  icon_key     = excluded.icon_key,
  is_physical  = excluded.is_physical;

-- =============================================================================================
-- 4 · SEED — subtypes. `customAsset` is the GENERIC entry, the analogue of `customDocument`.
-- =============================================================================================
-- ★ THE GENERIC ENTRY EXISTS SO THE CLIENT NEVER HAS TO INVENT ONE. The Vault defect was a client
-- sending a value the catalog did not contain; a resolvable generic is what makes "I don't know what
-- this is" expressible IN the vocabulary instead of beside it.
insert into public.estate_asset_subtype (subtype, parent_category, display_name, sort_order) values
  ('chequingAccount',       'bankAccount',      'Chequing account',            1),
  ('savingsAccount',        'bankAccount',      'Savings account',             2),
  ('moneyMarketAccount',    'bankAccount',      'Money market account',        3),
  ('termDeposit',           'bankAccount',      'Term deposit or GIC/CD',      4),

  ('brokerageAccount',      'investment',       'Brokerage account',           1),
  ('directEquity',          'investment',       'Directly held shares',        2),
  ('bondHolding',           'investment',       'Bonds',                       3),
  ('fundHolding',           'investment',       'Mutual or index funds',       4),

  ('workplacePension',      'retirement',       'Workplace pension',           1),
  ('personalRetirement',    'retirement',       'Personal retirement account', 2),
  ('annuityContract',       'retirement',       'Annuity',                     3),

  ('lifeInsurance',         'insurance',        'Life insurance policy',       1),
  ('criticalIllnessCover',  'insurance',        'Critical illness cover',      2),
  ('longTermCareCover',     'insurance',        'Long-term care cover',        3),

  ('primaryResidence',      'realEstate',       'Primary residence',           1),
  ('secondaryProperty',     'realEstate',       'Second or holiday property',  2),
  ('rentalProperty',        'realEstate',       'Rental property',             3),
  ('landParcel',            'realEstate',       'Land',                        4),

  ('soleProprietorship',    'businessInterest', 'Sole proprietorship',         1),
  ('partnershipInterest',   'businessInterest', 'Partnership interest',        2),
  ('privateCompanyShares',  'businessInterest', 'Private company shares',      3),

  ('exchangeAccount',       'digitalAsset',     'Exchange account',            1),
  ('selfCustodyWallet',     'digitalAsset',     'Self-custody wallet',         2),
  ('digitalCollectible',    'digitalAsset',     'Digital collectible',         3),
  ('domainOrIntellectual',  'digitalAsset',     'Domain or intellectual property', 4),

  -- Section C of the product definition: the structured physical inventory.
  ('jewellery',             'physicalValuable', 'Jewellery',                   1),
  ('artwork',               'physicalValuable', 'Artwork',                     2),
  ('collectible',           'physicalValuable', 'Collectible',                 3),
  ('vehicle',               'physicalValuable', 'Vehicle',                     4),
  ('safeDepositBox',        'physicalValuable', 'Safe deposit box',            5),
  ('preciousMetal',         'physicalValuable', 'Precious metal',              6),

  ('customAsset',           'otherAsset',       'Other',                       1)
on conflict (subtype) do update set
  parent_category = excluded.parent_category,
  display_name    = excluded.display_name,
  sort_order      = excluded.sort_order;

-- =============================================================================================
-- 5 · estate_assets — the inventory itself
-- =============================================================================================
create table if not exists public.estate_assets (
  id                      uuid        primary key default gen_random_uuid(),
  estate_id               uuid        not null references public.estates(id) on delete cascade,
  created_by              uuid        not null references auth.users(id),

  -- Persist-both taxonomy, same discipline as documents: the fine subtype AND its coarse parent, so
  -- a client that has never heard of a new subtype can still group the row.
  category                text        not null references public.estate_asset_category(value),
  subtype                 text        not null references public.estate_asset_subtype(subtype),

  label                   text        not null,
  -- ★ THE SAME LADDER AS DOCUMENTS, ON PURPOSE. `document_grantable` is defined over exactly these
  -- five values, so an asset carrying a value from a DIFFERENT ladder could not be reasoned about by
  -- the ceiling the estate already has. One sensitivity vocabulary per estate, not two.
  -- (The catalog's NAME is document-flavoured; renaming it is a wider migration than this slice, and
  -- is ledgered rather than done here under cover of an inventory change.)
  sensitivity             text        not null default 'sealed' references public.document_sensitivity(value),

  owner_label             text,                     -- "Jointly held", "Held in trust" — free text
  country_code            text        check (country_code is null or country_code ~ '^[A-Z]{2}$'),
  jurisdiction            text,                     -- state / province / canton
  institution_name        text,
  -- ★ A HINT, AND THE SCHEMA ENFORCES THAT IT CANNOT BE MORE. Capped at 12 characters so a full
  -- account number, IBAN or wallet address is UNSTORABLE rather than merely discouraged. A field
  -- that can hold a secret eventually holds one.
  reference_hint          text        check (reference_hint is null or length(reference_hint) <= 12),

  approximate_value_cents bigint      check (approximate_value_cents is null or approximate_value_cents >= 0),
  currency                text        not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  notes                   text,
  -- Who is named AT THE INSTITUTION (an IRA beneficiary, a policy nominee). INFORMATIONAL RECORD
  -- KEEPING — it confers no access in this product and grants nothing.
  beneficiary_note        text,

  verification_status     text        not null default 'unverified'
                            check (verification_status in ('unverified','ownerAsserted','documented','verified')),

  -- Soft deletion. NULL = live. The pair is set and cleared together by the archive/restore RPCs.
  archived_at             timestamptz,
  archived_by             uuid        references auth.users(id),

  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),

  constraint estate_assets_label_not_blank check (length(btrim(label)) > 0),
  constraint estate_assets_label_len       check (length(label) <= 200),
  constraint estate_assets_archived_pair   check ((archived_at is null) = (archived_by is null))
);
create index if not exists estate_assets_estate_idx on public.estate_assets (estate_id);
-- Partial index: the common read is "the live inventory", and archived rows drop out of it.
create index if not exists estate_assets_live_idx on public.estate_assets (estate_id, created_at desc)
  where archived_at is null;

alter table public.estate_assets enable row level security;

-- READ: estate OWNER ONLY, through the is_estate_owner DEFINER helper. An inline estate_memberships
-- subquery would FAIL here (authenticated holds no SELECT grant on it — the policy subquery runs as
-- the invoker), which is the same reason connections/normalized_assets use the helper.
--
-- ★ NO aal2 CLAUSE, PER THE RULING. This policy is the ONLY read path, and it admits the owner only.
drop policy if exists estate_assets_read_owner on public.estate_assets;
create policy estate_assets_read_owner on public.estate_assets
  for select to authenticated using (public.is_estate_owner(estate_id));

-- WRITES ARE DEFINER-RPC-ONLY — the documents posture (0030). No INSERT/UPDATE/DELETE grant exists,
-- so validation, the audit trail and the archive semantics cannot be bypassed by a direct PostgREST
-- write. The table keeps exactly ONE client grant: authenticated SELECT.
grant select on table public.estate_assets to authenticated;

-- =============================================================================================
-- 6 · estate_asset_documents — evidence attached to an asset
-- =============================================================================================
-- ★ THE JOIN CARRIES NO AUTHORITY OF ITS OWN. Linking a document to an asset does not widen who may
-- read either one: the document keeps `documents_read` (owner, or a covering grant) and the asset
-- keeps owner-only. A join row is a statement about organisation, never about access.
create table if not exists public.estate_asset_documents (
  asset_id  uuid        not null references public.estate_assets(id) on delete cascade,
  doc_id    uuid        not null references public.documents(id) on delete cascade,
  linked_by uuid        not null references auth.users(id),
  linked_at timestamptz not null default now(),
  primary key (asset_id, doc_id)
);
create index if not exists estate_asset_documents_doc_idx on public.estate_asset_documents (doc_id);

alter table public.estate_asset_documents enable row level security;

-- Readable exactly when the asset is readable. `estate_assets` is owner-only, so this resolves to the
-- owner — expressed as a dependency on the asset rather than a second copy of the ownership rule, so
-- the two cannot drift apart.
drop policy if exists estate_asset_documents_read on public.estate_asset_documents;
create policy estate_asset_documents_read on public.estate_asset_documents
  for select to authenticated using (
    exists (select 1 from public.estate_assets a where a.id = asset_id and public.is_estate_owner(a.estate_id))
  );
grant select on table public.estate_asset_documents to authenticated;
-- No write grant: link/unlink are DEFINER RPCs.

-- ★ ON DELETE CASCADE from `documents` is what keeps this table honest. A vault document is HARD
-- deleted (0039), so its join rows must go with it; leaving a dangling asset↔doc row would render an
-- attachment for a document that no longer exists.

-- =============================================================================================
-- 7 · vocabulary versioning — the new catalogs share the existing taxonomy_version counter
-- =============================================================================================
-- ★ ONE COUNTER, ONE CLIENT CACHE INVALIDATION. The client caches the asset vocabulary by
-- `vocabulary_version` exactly as it caches the document vocabulary. Giving the asset catalogs their
-- own counter would mean a client had to track two, and the one it forgot would serve a stale
-- vocabulary indefinitely. `bump_taxonomy_vocabulary_version` (0036) is reused verbatim.
drop trigger if exists estate_asset_category_taxonomy_bump on public.estate_asset_category;
create trigger estate_asset_category_taxonomy_bump
  after insert or update or delete on public.estate_asset_category
  for each statement execute function public.bump_taxonomy_vocabulary_version();

drop trigger if exists estate_asset_subtype_taxonomy_bump on public.estate_asset_subtype;
create trigger estate_asset_subtype_taxonomy_bump
  after insert or update or delete on public.estate_asset_subtype
  for each statement execute function public.bump_taxonomy_vocabulary_version();

-- ★ THE TRIGGERS ARE CREATED AFTER THE SEED, deliberately, matching 0036: attaching them first would
-- bump the version once per seed statement and hand every client a version number that describes
-- nothing. One bump on the next real change is the useful signal.

commit;

-- =============================================================================================
-- 8 · RPCs — APPLY db/functions/estate_asset_rpcs.sql IMMEDIATELY AFTER THIS FILE
-- =============================================================================================
-- The function bodies live in ONE place (db/functions/estate_asset_rpcs.sql) rather than being
-- duplicated here. Two copies of a SECURITY DEFINER body is a drift hazard with an authorization
-- gate inside it: the copy that gets patched is not necessarily the copy that is deployed.
--
-- `scripts/buildEstateAssetBundle.mjs` concatenates this file and that one into a single paste-ready
-- artifact, so the SQL editor still gets one paste.


-- ==== db/functions/estate_asset_rpcs.sql ==========================================================
-- Estate-asset RPCs — migration 0048 (Phase 9). Source of truth; re-apply on reset.
--
-- Owner-gated DEFINER doors for the MANUAL estate inventory. Every one of them:
--   * resolves the row FIRST and gates on the ROW's estate_id, never on a caller-supplied estate;
--   * raises machine-readable sentinels as the exception MESSAGE (errcode P0001/P0002/42501), the
--     same message-as-code convention as `unknown_subtype`;
--   * writes an audit entry naming the CHANGED FIELDS, never their values — an asset's value, notes
--     and reference hint must not be reconstructable from the audit log.
--
-- ★ THE CATEGORY IS DERIVED FROM THE SUBTYPE, NEVER ACCEPTED FROM THE CALLER. Taking both would let a
-- client persist a (category, subtype) pair the catalog contradicts — a persist-both taxonomy is only
-- trustworthy if exactly one of the pair is authoritative and the other is looked up.

-- ---------------------------------------------------------------------------------------------
-- get_estate_asset_taxonomy() -> jsonb  — the client read path for the asset vocabulary
-- ---------------------------------------------------------------------------------------------
-- ACTIVE values only, so presence in the payload IS the active-validation fact (no client is_active
-- check to forget). Shares `taxonomy_version` with the document catalogs so one version bump
-- invalidates one client cache.
create or replace function public.get_estate_asset_taxonomy()
 returns jsonb
 language sql
 security definer
 stable
 set search_path to 'public'
as $function$
  select jsonb_build_object(
    'schema_version',     (select schema_version     from public.taxonomy_version where id = 1),
    'vocabulary_version', (select vocabulary_version from public.taxonomy_version where id = 1),
    'categories', coalesce((
      select jsonb_agg(jsonb_build_object(
        'value', value, 'display_name', display_name, 'description', description,
        'sort_order', sort_order, 'icon_key', icon_key, 'is_physical', is_physical)
        order by sort_order, value)
      from public.estate_asset_category where is_active), '[]'::jsonb),
    'subtypes', coalesce((
      select jsonb_agg(jsonb_build_object(
        'value', subtype, 'display_name', display_name, 'description', description,
        'parent_category', parent_category, 'sort_order', sort_order, 'icon_key', icon_key)
        order by sort_order, subtype)
      from public.estate_asset_subtype where is_active), '[]'::jsonb)
  );
$function$;
revoke execute on function public.get_estate_asset_taxonomy() from public, anon;
grant  execute on function public.get_estate_asset_taxonomy() to authenticated;

-- ---------------------------------------------------------------------------------------------
-- create_estate_asset(...) -> uuid
-- ---------------------------------------------------------------------------------------------
create or replace function public.create_estate_asset(
  p_estate                  uuid,
  p_subtype                 text,
  p_label                   text,
  p_sensitivity             text    default null,
  p_owner_label             text    default null,
  p_country_code            text    default null,
  p_jurisdiction            text    default null,
  p_institution_name        text    default null,
  p_reference_hint          text    default null,
  p_approximate_value_cents bigint  default null,
  p_currency                text    default null,
  p_notes                   text    default null,
  p_beneficiary_note        text    default null
)
 returns uuid
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid      uuid := auth.uid();
  v_category text;
  v_sens     text;
  v_cur      text;
  v_id       uuid;
begin
  if v_uid is null then raise exception 'auth_required' using errcode = '42501'; end if;
  if not public.is_estate_owner(p_estate) then raise exception 'not_estate_owner' using errcode = '42501'; end if;

  if p_label is null or length(btrim(p_label)) = 0 then
    raise exception 'label_required' using errcode = 'P0001';
  end if;
  if length(p_label) > 200 then
    raise exception 'label_too_long' using errcode = 'P0001';
  end if;

  -- Catalog interrogation. An unknown or retired subtype is refused BEFORE any row exists — the
  -- Vault lesson: a rejection that lands after the write leaves an orphan behind.
  select s.parent_category into v_category
    from public.estate_asset_subtype s
    where s.subtype = p_subtype and s.is_active;
  if not found then
    if exists (select 1 from public.estate_asset_subtype where subtype = p_subtype) then
      raise exception 'inactive_subtype' using errcode = 'P0001';
    else
      raise exception 'unknown_subtype' using errcode = 'P0001';
    end if;
  end if;

  -- Sensitivity defaults to the most protective level, and an explicit value is validated against the
  -- SAME catalog documents use. There is no fallback: an unknown value is refused, never coerced.
  v_sens := coalesce(p_sensitivity, 'sealed');
  if not exists (select 1 from public.document_sensitivity where value = v_sens and is_active) then
    raise exception 'invalid_sensitivity' using errcode = 'P0001';
  end if;

  v_cur := upper(coalesce(p_currency, 'USD'));
  if v_cur !~ '^[A-Z]{3}$' then raise exception 'invalid_currency' using errcode = 'P0001'; end if;

  if p_approximate_value_cents is not null and p_approximate_value_cents < 0 then
    raise exception 'invalid_value' using errcode = 'P0001';
  end if;
  if p_reference_hint is not null and length(p_reference_hint) > 12 then
    -- The column CHECK would refuse this too; raising here turns a constraint violation into a
    -- sentinel the client can explain.
    raise exception 'reference_hint_too_long' using errcode = 'P0001';
  end if;

  -- ★ THIS CHECK WAS MISSING, AND ITS ABSENCE LEAKED THE WHOLE ROW. `update_estate_asset` validated
  -- the country code and this function did not, so a bad code fell through to the column CHECK —
  -- and a Postgres constraint violation carries `DETAIL: Failing row contains (…)`, i.e. the
  -- approximate value, the notes, the beneficiary note and the reference hint, into the server log
  -- and into any error telemetry downstream. The client maps the unrecognized message to `unknown`
  -- and shows nothing, which is exactly why this would never have been noticed from the app.
  --
  -- Every user-supplied field on this path is now validated BEFORE the insert, so a constraint
  -- violation here means a genuine bug rather than ordinary bad input.
  if p_country_code is not null and btrim(p_country_code) <> ''
     and upper(btrim(p_country_code)) !~ '^[A-Z]{2}$' then
    raise exception 'invalid_country_code' using errcode = 'P0001';
  end if;

  insert into public.estate_assets (
    estate_id, created_by, category, subtype, label, sensitivity, owner_label, country_code,
    jurisdiction, institution_name, reference_hint, approximate_value_cents, currency, notes,
    beneficiary_note
  ) values (
    p_estate, v_uid, v_category, p_subtype, btrim(p_label), v_sens, p_owner_label,
    nullif(upper(btrim(coalesce(p_country_code, ''))), ''), p_jurisdiction, p_institution_name,
    p_reference_hint, p_approximate_value_cents, v_cur, p_notes, p_beneficiary_note
  ) returning id into v_id;

  -- FIELD NAMES ONLY. An estate's asset values must not be reconstructable from audit_logs.
  perform public.write_audit('estate_asset.created', 'estate_assets', v_id, p_estate,
    jsonb_build_object('category', v_category, 'subtype', p_subtype, 'sensitivity', v_sens,
                       'via', 'create_estate_asset'));
  return v_id;
end;
$function$;
revoke execute on function public.create_estate_asset(uuid, text, text, text, text, text, text, text, text, bigint, text, text, text) from public, anon;
grant  execute on function public.create_estate_asset(uuid, text, text, text, text, text, text, text, text, bigint, text, text, text) to authenticated;

-- ---------------------------------------------------------------------------------------------
-- update_estate_asset(...) -> void  — METADATA ONLY
-- ---------------------------------------------------------------------------------------------
-- ★ THE IMMUTABLE FIELDS ARE UNREPRESENTABLE. `estate_id`, `created_by` and `created_at` are not
-- parameters, so a caller cannot move an asset to another estate or rewrite its provenance — the
-- strongest form of "rejected", exactly as `update_vault_document` treats storage_path.
--
-- ★ NULL MEANS "LEAVE ALONE", so a client may send only what changed. The consequence is that a
-- nullable field cannot be CLEARED through this door; `p_clear` names the fields to blank, which
-- keeps "unset it" explicit instead of overloading NULL with two meanings.
create or replace function public.update_estate_asset(
  p_asset_id                uuid,
  p_subtype                 text    default null,
  p_label                   text    default null,
  p_sensitivity             text    default null,
  p_owner_label             text    default null,
  p_country_code            text    default null,
  p_jurisdiction            text    default null,
  p_institution_name        text    default null,
  p_reference_hint          text    default null,
  p_approximate_value_cents bigint  default null,
  p_currency                text    default null,
  p_notes                   text    default null,
  p_beneficiary_note        text    default null,
  p_verification_status     text    default null,
  p_clear                   text[]  default null
)
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid      uuid := auth.uid();
  v_estate   uuid;
  v_arch     timestamptz;
  v_category text;
  v_changed  text[] := '{}';
  v_field    text;
begin
  if v_uid is null then raise exception 'auth_required' using errcode = '42501'; end if;

  select estate_id, archived_at into v_estate, v_arch from public.estate_assets where id = p_asset_id;
  if not found then raise exception 'asset_not_found' using errcode = 'P0002'; end if;
  if not public.is_estate_owner(v_estate) then raise exception 'not_estate_owner' using errcode = '42501'; end if;
  -- An archived asset is restored before it is edited. Editing something the owner has removed from
  -- the inventory would silently resurrect it in every list that filters on archived_at.
  if v_arch is not null then raise exception 'asset_archived' using errcode = 'P0001'; end if;

  if p_subtype is null and p_label is null and p_sensitivity is null and p_owner_label is null
     and p_country_code is null and p_jurisdiction is null and p_institution_name is null
     and p_reference_hint is null and p_approximate_value_cents is null and p_currency is null
     and p_notes is null and p_beneficiary_note is null and p_verification_status is null
     and (p_clear is null or array_length(p_clear, 1) is null) then
    raise exception 'no_fields_to_update' using errcode = 'P0001';
  end if;

  if p_label is not null then
    if length(btrim(p_label)) = 0 then raise exception 'label_required' using errcode = 'P0001'; end if;
    if length(p_label) > 200 then raise exception 'label_too_long' using errcode = 'P0001'; end if;
    update public.estate_assets set label = btrim(p_label) where id = p_asset_id;
    v_changed := array_append(v_changed, 'label');
  end if;

  if p_subtype is not null then
    select s.parent_category into v_category
      from public.estate_asset_subtype s where s.subtype = p_subtype and s.is_active;
    if not found then
      if exists (select 1 from public.estate_asset_subtype where subtype = p_subtype) then
        raise exception 'inactive_subtype' using errcode = 'P0001';
      else
        raise exception 'unknown_subtype' using errcode = 'P0001';
      end if;
    end if;
    -- The category is RE-DERIVED, never taken from the caller — the pair cannot be made inconsistent.
    update public.estate_assets set subtype = p_subtype, category = v_category where id = p_asset_id;
    v_changed := array_append(v_changed, 'subtype');
    v_changed := array_append(v_changed, 'category');
  end if;

  if p_sensitivity is not null then
    if not exists (select 1 from public.document_sensitivity where value = p_sensitivity and is_active) then
      raise exception 'invalid_sensitivity' using errcode = 'P0001';
    end if;
    update public.estate_assets set sensitivity = p_sensitivity where id = p_asset_id;
    v_changed := array_append(v_changed, 'sensitivity');
  end if;

  if p_verification_status is not null then
    if p_verification_status not in ('unverified','ownerAsserted','documented','verified') then
      raise exception 'invalid_verification_status' using errcode = 'P0001';
    end if;
    update public.estate_assets set verification_status = p_verification_status where id = p_asset_id;
    v_changed := array_append(v_changed, 'verification_status');
  end if;

  if p_currency is not null then
    if upper(p_currency) !~ '^[A-Z]{3}$' then raise exception 'invalid_currency' using errcode = 'P0001'; end if;
    update public.estate_assets set currency = upper(p_currency) where id = p_asset_id;
    v_changed := array_append(v_changed, 'currency');
  end if;

  if p_approximate_value_cents is not null then
    if p_approximate_value_cents < 0 then raise exception 'invalid_value' using errcode = 'P0001'; end if;
    update public.estate_assets set approximate_value_cents = p_approximate_value_cents where id = p_asset_id;
    v_changed := array_append(v_changed, 'approximate_value_cents');
  end if;

  if p_reference_hint is not null then
    if length(p_reference_hint) > 12 then raise exception 'reference_hint_too_long' using errcode = 'P0001'; end if;
    update public.estate_assets set reference_hint = p_reference_hint where id = p_asset_id;
    v_changed := array_append(v_changed, 'reference_hint');
  end if;

  if p_country_code is not null then
    if upper(btrim(p_country_code)) !~ '^[A-Z]{2}$' then
      raise exception 'invalid_country_code' using errcode = 'P0001';
    end if;
    update public.estate_assets set country_code = upper(btrim(p_country_code)) where id = p_asset_id;
    v_changed := array_append(v_changed, 'country_code');
  end if;

  if p_owner_label is not null then
    update public.estate_assets set owner_label = p_owner_label where id = p_asset_id;
    v_changed := array_append(v_changed, 'owner_label');
  end if;
  if p_jurisdiction is not null then
    update public.estate_assets set jurisdiction = p_jurisdiction where id = p_asset_id;
    v_changed := array_append(v_changed, 'jurisdiction');
  end if;
  if p_institution_name is not null then
    update public.estate_assets set institution_name = p_institution_name where id = p_asset_id;
    v_changed := array_append(v_changed, 'institution_name');
  end if;
  if p_notes is not null then
    update public.estate_assets set notes = p_notes where id = p_asset_id;
    v_changed := array_append(v_changed, 'notes');
  end if;
  if p_beneficiary_note is not null then
    update public.estate_assets set beneficiary_note = p_beneficiary_note where id = p_asset_id;
    v_changed := array_append(v_changed, 'beneficiary_note');
  end if;

  -- Explicit clearing. Only genuinely optional columns are clearable — `label`, `subtype`,
  -- `category`, `sensitivity` and `currency` are NOT NULL and are absent from this list by design.
  if p_clear is not null then
    foreach v_field in array p_clear loop
      case v_field
        when 'owner_label'             then update public.estate_assets set owner_label = null where id = p_asset_id;
        when 'country_code'            then update public.estate_assets set country_code = null where id = p_asset_id;
        when 'jurisdiction'            then update public.estate_assets set jurisdiction = null where id = p_asset_id;
        when 'institution_name'        then update public.estate_assets set institution_name = null where id = p_asset_id;
        when 'reference_hint'          then update public.estate_assets set reference_hint = null where id = p_asset_id;
        when 'approximate_value_cents' then update public.estate_assets set approximate_value_cents = null where id = p_asset_id;
        when 'notes'                   then update public.estate_assets set notes = null where id = p_asset_id;
        when 'beneficiary_note'        then update public.estate_assets set beneficiary_note = null where id = p_asset_id;
        else raise exception 'unclearable_field' using errcode = 'P0001';
      end case;
      v_changed := array_append(v_changed, 'cleared:' || v_field);
    end loop;
  end if;

  update public.estate_assets set updated_at = now() where id = p_asset_id;

  perform public.write_audit('estate_asset.updated', 'estate_assets', p_asset_id, v_estate,
    jsonb_build_object('changed', to_jsonb(v_changed), 'via', 'update_estate_asset'));
end;
$function$;
revoke execute on function public.update_estate_asset(uuid, text, text, text, text, text, text, text, text, bigint, text, text, text, text, text[]) from public, anon;
grant  execute on function public.update_estate_asset(uuid, text, text, text, text, text, text, text, text, bigint, text, text, text, text, text[]) to authenticated;

-- ---------------------------------------------------------------------------------------------
-- archive_estate_asset / restore_estate_asset -> void  — the SOFT delete pair
-- ---------------------------------------------------------------------------------------------
-- ★ NOTHING IS DESTROYED AND NOTHING IS DETACHED. Archiving sets a timestamp; attached documents keep
-- their own hard-delete lifecycle untouched. This is the owner-approved asymmetry with documents: a
-- document's irreversibility is justified by a storage-byte purge, and an asset has no bytes.
create or replace function public.archive_estate_asset(p_asset_id uuid)
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid    uuid := auth.uid();
  v_estate uuid;
  v_arch   timestamptz;
begin
  if v_uid is null then raise exception 'auth_required' using errcode = '42501'; end if;
  select estate_id, archived_at into v_estate, v_arch from public.estate_assets where id = p_asset_id;
  if not found then raise exception 'asset_not_found' using errcode = 'P0002'; end if;
  if not public.is_estate_owner(v_estate) then raise exception 'not_estate_owner' using errcode = '42501'; end if;
  -- Idempotent by refusal rather than by silence: a no-op success would tell the client the state
  -- changed when it did not.
  if v_arch is not null then raise exception 'already_archived' using errcode = 'P0001'; end if;

  update public.estate_assets
     set archived_at = now(), archived_by = v_uid, updated_at = now()
   where id = p_asset_id;

  perform public.write_audit('estate_asset.archived', 'estate_assets', p_asset_id, v_estate,
    jsonb_build_object('via', 'archive_estate_asset'));
end;
$function$;
revoke execute on function public.archive_estate_asset(uuid) from public, anon;
grant  execute on function public.archive_estate_asset(uuid) to authenticated;

create or replace function public.restore_estate_asset(p_asset_id uuid)
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid    uuid := auth.uid();
  v_estate uuid;
  v_arch   timestamptz;
begin
  if v_uid is null then raise exception 'auth_required' using errcode = '42501'; end if;
  select estate_id, archived_at into v_estate, v_arch from public.estate_assets where id = p_asset_id;
  if not found then raise exception 'asset_not_found' using errcode = 'P0002'; end if;
  if not public.is_estate_owner(v_estate) then raise exception 'not_estate_owner' using errcode = '42501'; end if;
  if v_arch is null then raise exception 'not_archived' using errcode = 'P0001'; end if;

  update public.estate_assets
     set archived_at = null, archived_by = null, updated_at = now()
   where id = p_asset_id;

  perform public.write_audit('estate_asset.restored', 'estate_assets', p_asset_id, v_estate,
    jsonb_build_object('via', 'restore_estate_asset'));
end;
$function$;
revoke execute on function public.restore_estate_asset(uuid) from public, anon;
grant  execute on function public.restore_estate_asset(uuid) to authenticated;

-- ---------------------------------------------------------------------------------------------
-- link_asset_document / unlink_asset_document -> void
-- ---------------------------------------------------------------------------------------------
-- ★ BOTH SIDES ARE OWNERSHIP-CHECKED, AND BOTH MUST BE THE SAME ESTATE. Checking only the asset would
-- let an owner attach a document from an estate they do not own — the join row itself grants nothing,
-- but it would leak the document's EXISTENCE into a surface they control.
create or replace function public.link_asset_document(p_asset_id uuid, p_doc_id uuid)
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid        uuid := auth.uid();
  v_asset_est  uuid;
  v_doc_est    uuid;
begin
  if v_uid is null then raise exception 'auth_required' using errcode = '42501'; end if;

  select estate_id into v_asset_est from public.estate_assets where id = p_asset_id;
  if not found then raise exception 'asset_not_found' using errcode = 'P0002'; end if;
  select estate_id into v_doc_est from public.documents where id = p_doc_id;
  if not found then raise exception 'document_not_found' using errcode = 'P0002'; end if;

  if not public.is_estate_owner(v_asset_est) then raise exception 'not_estate_owner' using errcode = '42501'; end if;
  if v_asset_est <> v_doc_est then raise exception 'cross_estate_link' using errcode = '42501'; end if;

  insert into public.estate_asset_documents (asset_id, doc_id, linked_by)
  values (p_asset_id, p_doc_id, v_uid)
  on conflict (asset_id, doc_id) do nothing;

  perform public.write_audit('estate_asset.document_linked', 'estate_assets', p_asset_id, v_asset_est,
    jsonb_build_object('doc_id', p_doc_id, 'via', 'link_asset_document'));
end;
$function$;
revoke execute on function public.link_asset_document(uuid, uuid) from public, anon;
grant  execute on function public.link_asset_document(uuid, uuid) to authenticated;

create or replace function public.unlink_asset_document(p_asset_id uuid, p_doc_id uuid)
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid       uuid := auth.uid();
  v_asset_est uuid;
begin
  if v_uid is null then raise exception 'auth_required' using errcode = '42501'; end if;
  select estate_id into v_asset_est from public.estate_assets where id = p_asset_id;
  if not found then raise exception 'asset_not_found' using errcode = 'P0002'; end if;
  if not public.is_estate_owner(v_asset_est) then raise exception 'not_estate_owner' using errcode = '42501'; end if;

  delete from public.estate_asset_documents where asset_id = p_asset_id and doc_id = p_doc_id;

  -- ★ UNLINKING DELETES NO BYTES AND NO DOCUMENT ROW. Detaching evidence from an asset is an
  -- organisational act; removing the document itself remains `delete_vault_document`, with its own
  -- blocking gauntlet and purge outbox.
  perform public.write_audit('estate_asset.document_unlinked', 'estate_assets', p_asset_id, v_asset_est,
    jsonb_build_object('doc_id', p_doc_id, 'via', 'unlink_asset_document'));
end;
$function$;
revoke execute on function public.unlink_asset_document(uuid, uuid) from public, anon;
grant  execute on function public.unlink_asset_document(uuid, uuid) to authenticated;
