-- GENERATED by scripts/scripts/buildChallengeSettlementBundle.mjs — DO NOT EDIT.
-- Edit the sources instead:
--   db/functions/release_safety.sql
--
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- PASTE THIS WHOLE FILE INTO THE SUPABASE WEB SQL EDITOR AND RUN IT ONCE.
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- PURE SQL: this artifact contains no psql meta-commands. (\set and friends are client directives
-- the web editor cannot honour; they are stripped at build time and remain only in the sources,
-- which are applied through psql by the SQL suite.)
--
-- TRANSACTIONAL: the entire artifact runs inside ONE explicit transaction. Every statement here is
-- transaction-safe — the builder refuses to emit a wrapper otherwise — so:
--
--   · if ANY statement fails, the transaction aborts and COMMIT is never reached;
--   · the database is left EXACTLY as it was: there is no half-applied state to diagnose;
--   · the migrations' own self-checks raise on a bad state, which aborts before COMMIT too, so a
--     bundle that detects a problem rolls itself back rather than shipping it.
--
-- IDEMPOTENT: every table is IF NOT EXISTS, every function is CREATE OR REPLACE, every constraint
-- is dropped-then-added, and every seed uses ON CONFLICT. Re-running is safe and is the intended
-- recovery action after a failure.
begin;

-- ==== db/functions/release_safety.sql =============================================================
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- PHASE 11-E · RELEASE SAFETY — the challenge window between death_verified and released
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- ★ WHAT THIS FILE OWNS. The three transitions that stand between an accepted death verification
-- and irreversible disclosure, plus the owner-facing status read:
--
--   begin_challenge_window   death_verified → challenge_window     [admin, AAL2+fresh]
--   challenge_death_process  any pre-released death-process state
--                            → challenge_halted                    [the authenticated OWNER, alone]
--   release_estate           challenge_window → released           [INTERNAL — no reachable door]
--   get_owner_safety_status  owner-scoped presentation union       [authenticated, owner-gated]
--
-- ★ WHAT THIS FILE MUST NEVER TOUCH: access_grants, visibility tiers, memberships, designations,
-- documents, claim rows, or the release predicate. Release is EVALUATIVE — the lifecycle moves and
-- the one canonical predicate answers differently. `test/deathVerificationFoundation.test.ts`
-- pins the forbidden set for this file exactly as it does for the death-verification module.
--
-- ★ THE SAFETY NOTIFICATION IS LOAD-BEARING, AND THE EMITTER'S USUAL TRADE IS INVERTED HERE.
-- `emit_lifecycle_notification` deliberately swallows insert failure so that a grant still commits
-- when a heads-up cannot be written — the right trade for a heads-up. The window-open notice is
-- not a heads-up: it is the owner's one chance to object before disclosure becomes irreversible,
-- so `begin_challenge_window` REQUIRES the emit to return a committed row id and rolls the whole
-- transition back otherwise. The window cannot begin un-notified. (Reliability class, stated
-- honestly: one in-app notification row, committed in the SAME transaction as the transition.
-- Whether that class is sufficient to start a release clock in production is part of the window-
-- duration product decision; until an operator configures a duration, no window can elapse.)
--
-- ★ THE TIEBREAK IS STRUCTURAL (R14). Release requires the window STRICTLY elapsed:
-- `now() > owner_notified_at + duration`. At the exact boundary instant the release refuses while
-- the challenge still succeeds; both serialize on the lifecycle row lock; and the transition map
-- has no edge out of challenge_halted, so a committed challenge is final in 11-E — no resume, no
-- admin override (R: deliberately absent, a future product decision).
--
-- ★ CHALLENGE PROVENANCE IS PROTECTED (§17). The audit row records THAT the owner challenged and
-- from which lifecycle state — never a channel, device, address, or location. `write_audit` does
-- not populate ip/user_agent, and nothing here adds them. Claimant-facing surfaces may learn only
-- that the process halted.
--
-- Deploys via `db/bundles/death_verification_bundle.sql` (after 0054 and the workflow routines).
-- Source of truth — re-apply on DB reset.

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- challenge_window_duration() → interval                        [INTERNAL — the configured window]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- NULL means NOT CONFIGURED, and not configured means the window never elapses (fail-closed:
-- release refuses, the challenge stays available). Read LIVE at release time — the H2 precedent:
-- a duration lengthened mid-window lengthens the window; there is no stamped deadline to go stale.
create or replace function public.challenge_window_duration()
 returns interval
 language sql
 security definer
 stable
 set search_path to 'public'
as $function$
  select p.challenge_window from public.release_safety_policy p where p.id;
$function$;
revoke execute on function public.challenge_window_duration() from public, anon, authenticated;

comment on function public.challenge_window_duration() is
  'The configured owner-challenge window (Phase 11-E). NULL = not configured = the window never '
  'elapses and release refuses. Set only by an explicit, reviewed operator INSERT into '
  'release_safety_policy — never seeded by a migration. INTERNAL: clients cannot read the safety '
  'clock; the owner surface answers through get_owner_safety_status.';

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- dispatch_owner_safety_notice(p_estate) → text                               [admin, AAL2+fresh]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ PHASE 11-F, D4 — "the owner was told" MUST mean an independently reachable channel. 11-E wrote
-- one in-app notification and required it to commit; that is a real guarantee and it is not enough,
-- because a person who has stopped opening the app is exactly the person a false death process
-- targets successfully. This routine additionally commits an EMAIL row addressed to the owner, in
-- the SAME transaction as the state change, and refuses the whole transition if it cannot.
--
-- ★ THE REQUIREMENT IS DISPATCH INITIATION, NOT DELIVERY (Stage 2, stated exactly). No read
-- receipt, no open tracking, no acknowledgement — none of which this product can honestly observe,
-- and each of which would let a silent mail server hold a release hostage forever. What IS required
-- is that a real address was resolved and a real row was committed to a real queue.
--
-- ★ AND AN UNRESOLVABLE ADDRESS IS A HARD FAILURE. Queueing a row with no recipient would be
-- "dispatch initiated" in name only — the fail-closed answer is to refuse the transition, leaving
-- the estate at `death_verified` where nothing can release, rather than starting a clock nobody can
-- hear ticking.
--
-- ★ D2 — THE CLOCK STARTS HERE. `owner_notified_at` is stamped at dispatch, so the seven days run
-- from the moment the owner was told; not from claim creation, evidence upload, verification, or
-- administrative review, none of which the owner can see.
create or replace function public.dispatch_owner_safety_notice(p_estate uuid)
 returns text
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid       uuid;
  v_state     text;
  v_owner     uuid;
  v_recipient text;
  v_case      uuid;
  v_notice    uuid;
  v_outbox    uuid;
begin
  perform public.admin_require_gate();
  v_uid := auth.uid();

  select l.state into v_state
    from public.estate_lifecycle l
   where l.estate_id = p_estate
   for update;

  if v_state = 'owner_notification_dispatched' then
    return 'owner_notification_dispatched'; -- idempotent replay: no re-dispatch, no re-audit
  end if;
  if v_state is distinct from 'death_verified' then
    raise exception 'invalid_dispatch_state' using errcode = 'P0001';
  end if;

  select c.id into v_case
    from public.death_verification_cases c
   where c.estate_id = p_estate and c.status = 'verified'
   order by c.decided_at desc
   limit 1;
  if v_case is null then
    raise exception 'no_verified_case' using errcode = 'P0001';
  end if;

  v_owner := public.estate_owner_user_id(p_estate);
  if v_owner is null then
    raise exception 'owner_unresolved' using errcode = 'P0001';
  end if;

  -- ★ THE INDEPENDENT CHANNEL, RESOLVED FROM THE IDENTITY PROVIDER rather than from anything a
  -- claimant can write. `profiles.email` is user-editable in principle; `auth.users.email` is the
  -- address the account authenticates with, which is the one a claimant cannot repoint.
  select u.email into v_recipient from auth.users u where u.id = v_owner;
  if v_recipient is null or btrim(v_recipient) = '' then
    raise exception 'owner_channel_unreachable' using errcode = 'P0001';
  end if;

  -- EMAIL FIRST: the row whose existence is the dispatch. Same transaction as the transition, so a
  -- rollback anywhere below un-dispatches it and the window never opened.
  -- ★ PHASE 11-OC — THE ROW NAMES ITS EPISODE, AND `v_case` WAS ALREADY IN HAND.
  --
  -- `v_case` is resolved above and, until this phase, was discarded into the audit metadata only. It
  -- is the EPISODE key: one estate may legitimately experience several independent death processes
  -- over time (`rejected` and `cancelled` both return the lifecycle to `active`), so an accepted
  -- notice from a prior, rejected process must never authorize a release under a later case. Scoping
  -- the release predicate to the estate would do exactly that; scoping it to the case cannot.
  --
  -- `generation` is the literal 1 here and only ever incremented by the re-notice routine, under the
  -- predecessor's row lock — never from an unlocked max().
  --
  -- A BEFORE INSERT trigger (migration 0058) refuses any owner-notice row with a NULL case_id, so
  -- this is a wall rather than a promise this routine makes. Legacy rows keep their NULL and stay
  -- updatable, because the trigger fires on INSERT only.
  insert into public.owner_notice_outbox
    (estate_id, user_id, channel, recipient, notice_kind, status, case_id, generation)
  values (p_estate, v_owner, 'email', v_recipient, 'death_process.window_opened', 'queued',
          v_case, 1)
  returning id into v_outbox;
  if v_outbox is null then
    raise exception 'owner_notification_failed' using errcode = 'P0001';
  end if;

  -- IN-APP SECOND, and still REQUIRED (11-E's guarantee is kept, not replaced). Two channels, both
  -- committed, before any clock starts.
  v_notice := public.emit_lifecycle_notification(
    v_owner, p_estate, 'death_process.window_opened', 'afterworth://challenge');
  if v_notice is null then
    raise exception 'owner_notification_failed' using errcode = 'P0001';
  end if;

  perform public.apply_estate_lifecycle_transition(
    p_estate, 'owner_notification_dispatched', v_case, 'owner_notice_dispatched');

  update public.estate_lifecycle
     set owner_notified_at = now(),
         safety_notification_id = v_notice
   where estate_id = p_estate;

  -- ★ THE AUDIT RECORDS THE CHANNEL CLASS, NEVER THE ADDRESS. That a notice went to email is an
  -- operational fact; WHICH address is a living owner's contact detail, and an audit row outlives
  -- every reason anyone had to read it.
  insert into public.audit_logs (actor_id, estate_id, action, target_table, target_id, metadata, source)
  values (v_uid, p_estate, 'death_process.owner_notice_dispatched', 'owner_notice_outbox', v_outbox,
          jsonb_build_object('severity', 'high', 'case_id', v_case, 'channel', 'email',
                            'in_app_notification_id', v_notice),
          'admin');
  return 'owner_notification_dispatched';
end $function$;
revoke execute on function public.dispatch_owner_safety_notice(uuid) from public, anon;
grant  execute on function public.dispatch_owner_safety_notice(uuid) to authenticated;

comment on function public.dispatch_owner_safety_notice(uuid) is
  'Phase 11-F (D4): commits an EMAIL row and an in-app notice to the owner, in the same transaction '
  'as the death_verified -> owner_notification_dispatched transition, and stamps owner_notified_at '
  '(D2: the challenge clock starts at dispatch). Requires dispatch INITIATION, never delivery '
  'confirmation. An unresolvable owner address refuses the transition. Admin-gated; idempotent.';

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- begin_challenge_window(p_estate) → text                                      [admin, AAL2+fresh]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ REWRITTEN IN 11-F: it no longer notifies, because it no longer can. The notice moved to
-- `dispatch_owner_safety_notice`, and the edge `death_verified → challenge_window` was DELETED from
-- the transition map — so this routine's only legal input is an estate whose owner has already been
-- sent an email and an in-app notice. The guarantee "no window opens un-notified" is now carried by
-- the state machine rather than by this function remembering to check.
create or replace function public.begin_challenge_window(p_estate uuid)
 returns text
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid   uuid;
  v_state text;
  v_case  uuid;
  v_row   public.estate_lifecycle%rowtype;
begin
  perform public.admin_require_gate();
  v_uid := auth.uid();

  select l.* into v_row
    from public.estate_lifecycle l
   where l.estate_id = p_estate
   for update;
  v_state := v_row.state;

  if v_state = 'challenge_window' then
    return 'challenge_window'; -- idempotent replay
  end if;
  if v_state is distinct from 'owner_notification_dispatched' then
    raise exception 'invalid_window_state' using errcode = 'P0001';
  end if;

  -- Belt beside the state machine: the dispatch facts must actually be on the row.
  if v_row.owner_notified_at is null or v_row.safety_notification_id is null then
    raise exception 'owner_not_notified' using errcode = 'P0001';
  end if;
  if not exists (
    select 1 from public.owner_notice_outbox o
     where o.estate_id = p_estate
       and o.channel = 'email'
       and o.status <> 'cancelled'
  ) then
    raise exception 'owner_channel_unreachable' using errcode = 'P0001';
  end if;

  select c.id into v_case
    from public.death_verification_cases c
   where c.estate_id = p_estate and c.status = 'verified'
   order by c.decided_at desc
   limit 1;
  if v_case is null then
    raise exception 'no_verified_case' using errcode = 'P0001';
  end if;

  perform public.apply_estate_lifecycle_transition(
    p_estate, 'challenge_window', v_case, 'window_opened');

  update public.estate_lifecycle
     set challenge_window_started_at = now()
   where estate_id = p_estate;

  insert into public.audit_logs (actor_id, estate_id, action, target_table, target_id, metadata, source)
  values (v_uid, p_estate, 'death_process.window_opened', 'estate_lifecycle', v_case,
          jsonb_build_object('severity', 'high', 'case_id', v_case,
                            'owner_notified_at', v_row.owner_notified_at),
          'admin');
  return 'challenge_window';
end $function$;
revoke execute on function public.begin_challenge_window(uuid) from public, anon;
grant  execute on function public.begin_challenge_window(uuid) to authenticated;

comment on function public.begin_challenge_window(uuid) is
  'Opens the owner-challenge window (Phase 11-E, rewritten 11-F). Its ONLY legal input is '
  'owner_notification_dispatched — the death_verified -> challenge_window edge was deleted, so a '
  'window cannot open on an un-notified owner even by mistake. Admin-gated; idempotent; discloses '
  'nothing.';

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- authorize_release(p_estate, p_reason) → text                                 [admin, AAL2+fresh]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ THE TWO-PERSON RULE (D1), AND WHY IT LIVES IN THE DATABASE. The operator who verified the death
-- may not authorize the release. A console can enforce that and a console can be bypassed — by a
-- direct RPC, a future admin tool, a script, or the next rewrite. Here the rule is enforced twice on
-- purpose: this routine refuses, AND `release_authorizations` carries a CHECK constraint that makes
-- a single-reviewer row unwritable by ANY path. The routine is the door; the constraint is the wall.
--
-- ★ reviewer_a IS DERIVED, NEVER SUPPLIED. It is read from the verified case's `decided_by` — the
-- operator who actually made the call. A parameter would let the caller nominate a different
-- "first reviewer" and satisfy the rule against someone who never reviewed anything.
--
-- ★ THIS ROUTINE REPLACES 11-E's `release_estate`, WHICH IS DROPPED BY 0055. Leaving a one-person
-- lever beside a two-person door would be the whole decision undone by an un-rewired caller.
--
-- ★ AND IT STILL MANUFACTURES NOTHING (D5). No grant, no tier, no membership, no designation. The
-- lifecycle moves and the ONE canonical predicate answers differently for grants the owner already
-- authored.
create or replace function public.authorize_release(p_estate uuid, p_reason text)
 returns text
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_row        public.estate_lifecycle%rowtype;
  v_uid        uuid;
  v_case       uuid;
  v_reviewer_a uuid;
  v_verified   timestamptz;
  v_duration   interval;
begin
  perform public.admin_require_gate();
  v_uid := auth.uid();

  if p_reason is null or btrim(p_reason) = '' then
    raise exception 'audit_reason_required' using errcode = 'P0001';
  end if;

  select l.* into v_row
    from public.estate_lifecycle l
   where l.estate_id = p_estate
   for update;

  if v_row.state = 'released' then
    return 'released'; -- idempotent replay: no second authorization row, no re-audit
  end if;
  if v_row.state is distinct from 'challenge_window' then
    -- challenge_halted lands here too: release can NEVER proceed from a halted process.
    raise exception 'invalid_release_state' using errcode = 'P0001';
  end if;

  -- The dispatch facts (D4). A window that somehow lacks them cannot elapse into disclosure.
  if v_row.owner_notified_at is null or v_row.safety_notification_id is null then
    raise exception 'owner_not_notified' using errcode = 'P0001';
  end if;
  if not exists (
    select 1 from public.owner_notice_outbox o
     where o.estate_id = p_estate and o.channel = 'email' and o.status <> 'cancelled'
  ) then
    raise exception 'owner_channel_unreachable' using errcode = 'P0001';
  end if;

  select c.id, c.decided_by, c.decided_at into v_case, v_reviewer_a, v_verified
    from public.death_verification_cases c
   where c.estate_id = p_estate and c.status = 'verified'
   order by c.decided_at desc
   limit 1;
  if v_case is null then
    raise exception 'no_verified_case' using errcode = 'P0001';
  end if;
  if v_reviewer_a is null then
    raise exception 'reviewer_a_unresolved' using errcode = 'P0001';
  end if;

  -- ★ D1, ENFORCED HERE AND AGAIN BY THE TABLE CONSTRAINT BELOW.
  if v_uid = v_reviewer_a then
    raise exception 'two_person_rule_violated' using errcode = 'P0001';
  end if;

  v_duration := public.challenge_window_duration();
  if v_duration is null then
    raise exception 'release_window_not_configured' using errcode = 'P0001';
  end if;

  -- ★ STRICTLY ELAPSED (D3). At the exact boundary instant this refuses and the owner challenge —
  -- serialized on the same row lock — still succeeds. The coalesce is the three-valued-logic
  -- discipline: a NULL comparison must refuse, not pass.
  if not coalesce(now() > v_row.owner_notified_at + v_duration, false) then
    raise exception 'release_window_not_elapsed' using errcode = 'P0001';
  end if;

  insert into public.release_authorizations
    (estate_id, case_id, reviewer_a, reviewer_b, verified_at, authorized_at, released_at, audit_reason)
  values (p_estate, v_case, v_reviewer_a, v_uid, v_verified, now(), now(), p_reason);

  perform public.apply_estate_lifecycle_transition(
    p_estate, 'released', v_case, 'two_person_release');

  update public.estate_lifecycle
     set released_at = now()
   where estate_id = p_estate;

  insert into public.audit_logs (actor_id, estate_id, action, target_table, target_id, metadata, source)
  values (v_uid, p_estate, 'death_process.released', 'release_authorizations', v_case,
          jsonb_build_object('severity', 'high', 'case_id', v_case,
                            'reviewer_a', v_reviewer_a, 'reviewer_b', v_uid,
                            'verified_at', v_verified,
                            'owner_notified_at', v_row.owner_notified_at,
                            'window_duration', v_duration::text,
                            'audit_reason', p_reason),
          'admin');
  return 'released';
end $function$;
revoke execute on function public.authorize_release(uuid, text) from public, anon;
grant  execute on function public.authorize_release(uuid, text) to authenticated;

comment on function public.authorize_release(uuid, text) is
  'THE release transition (Phase 11-F): challenge_window -> released, by a SECOND platform operator. '
  'Requires admin gate, a non-empty audit reason, a committed owner email + in-app notice, a '
  'verified case, a STRICTLY elapsed 7-day window (ties go to the owner challenge), and '
  'reviewer_b <> reviewer_a where reviewer_a is DERIVED from the case decider. Records a '
  'release_authorizations row whose CHECK constraint makes a single-reviewer release unwritable by '
  'any path. Creates no grant, tier, membership or designation.';

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- challenge_death_process(p_estate) → text                          [the authenticated OWNER only]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ R13 IS THE SIGNATURE: one argument, one action. No evidence parameter exists, no review step
-- exists, no waiting period exists, no designation is consulted. The authenticated owner of the
-- estate halts the process — from pending, from death_verified, or from inside the window — and
-- challenge_halted is terminal in 11-E: the map has no edge out, and no routine reopens it.
--
-- ★ THE GATE RUNS BEFORE ANY EXISTENCE OR STATE LOOKUP. `is_estate_owner` answers false for a
-- nonexistent estate and a foreign one alike, so every unauthorized caller — beneficiary,
-- designee, claimant, foreign owner, probe against a random uuid — refuses with the same bytes.
create or replace function public.challenge_death_process(p_estate uuid)
 returns text
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid       uuid := auth.uid();
  v_state     text;
  -- ★ Phase 11-L. The initiator of the case THIS CALL halts, captured from the UPDATE's own
  -- RETURNING rather than looked up afterwards. A separate SELECT could name a case this call did
  -- not touch — one already halted, or one halted by a concurrent transaction — and would notify
  -- someone about a process that is still running, or notify twice about one that stopped once.
  v_initiator uuid;
begin
  if v_uid is null then
    raise exception 'auth_required' using errcode = '42501';
  end if;
  if not public.is_estate_owner(p_estate) then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  select l.state into v_state
    from public.estate_lifecycle l
   where l.estate_id = p_estate
   for update;
  if v_state is null then
    v_state := 'active';
  end if;

  if v_state = 'challenge_halted' then
    return 'challenge_halted'; -- idempotent replay: no re-stamp, no re-audit
  end if;
  if v_state = 'active' then
    raise exception 'nothing_to_challenge' using errcode = 'P0001';
  end if;
  -- Too late is stated honestly (R15): what was disclosed cannot be undisclosed, and pretending
  -- a halt succeeded would claim otherwise. The owner is authorized to know this about their
  -- own estate.
  if v_state = 'released' then
    raise exception 'already_released' using errcode = 'P0001';
  end if;

  perform public.apply_estate_lifecycle_transition(
    p_estate, 'challenge_halted', null, 'owner_challenge');

  update public.estate_lifecycle
     set halted_at = now()
   where estate_id = p_estate;

  -- The live case is halted — distinct from 'cancelled' (initiator withdrew): the owner said no.
  --
  -- ★ PHASE 11-NR — THE SET IS ('open','verified'), AND 'open' ALONE WAS THE DEFECT. This predicate
  -- read `status = 'open'`, which is the case status at exactly ONE of the four lifecycle states this
  -- routine can be reached from. The Branch A production drill measured the consequence: on the
  -- canonical operator-driven path the estate reached challenge_halted while its case row stayed
  -- 'verified', `v_initiator` came back NULL, and the 11-L halt notification — the entire deliverable
  -- of that phase — was never emitted to anybody. The case also stayed in the operator's `verified`
  -- work queue, invisible to a `halted` filter, with the queue row stating the contradiction outright.
  --
  -- The set is CLOSED and derived from the transition map, never "every row for this estate":
  --
  --   death_verification_pending    → case is 'open'      (initiate)
  --   death_verified                → case is 'verified'  (admin_decide 'verify')
  --   owner_notification_dispatched → case is 'verified'  (dispatch requires a verified case)
  --   challenge_window              → case is 'verified'  (begin_challenge_window requires one)
  --
  -- 'rejected' and 'cancelled' both return the lifecycle to `active`, where this routine has already
  -- raised `nothing_to_challenge` — they are decided history and settling them would overwrite an
  -- adjudication that did happen. 'halted' is excluded as a SECOND, independent guard against a
  -- re-stamp: the idempotent return above already refuses to reach this statement.
  --
  -- ★ AND IT STILL MATCHES AT MOST ONE ROW, WHICH NO LONGER FOLLOWS FROM THE INDEX ALONE.
  -- `death_verification_cases_one_open_per_estate` makes 'open' unique per estate; 'verified' is
  -- unique per estate for a different reason, and it is the state machine that supplies it. A
  -- verified case pins the lifecycle at death_verified or beyond, `initiate_death_verification_case`
  -- refuses unless the lifecycle is `active`, and no edge returns there from death_verified — so a
  -- second case cannot be opened once one is verified, and an 'open' case cannot coexist with a
  -- 'verified' one. Historical 'rejected' / 'cancelled' rows DO coexist and are excluded by the
  -- predicate. `into` therefore still has no set to choose from arbitrarily, and
  -- `release_safety_authorization.sql` §8 proves it on an estate that actually carries a decided
  -- historical case beside the live one.
  --
  -- ★ RETURNING gives us the initiator of the case actually settled HERE. A separate SELECT could
  -- name a case this call did not touch — one already halted, one from a prior rejected attempt, or
  -- one halted by a concurrent transaction — and would notify the wrong person, or notify twice
  -- about a process that stopped once.
  update public.death_verification_cases
     set status = 'halted', updated_at = now()
   where estate_id = p_estate and status in ('open', 'verified')
  returning initiated_by into v_initiator;

  -- ────────────────────────────────────────────────────────────────────────────────────────────
  -- ★ PHASE 11-L — TELL THE INITIATING FIDUCIARY THAT THEIR PROCESS STOPPED.
  -- ────────────────────────────────────────────────────────────────────────────────────────────
  --
  -- ★ RECIPIENT COMES FROM WORKFLOW STATE, NEVER FROM A CALLER. `p_estate` is the only input to
  -- this routine; there is no recipient parameter and therefore nothing for a client to point at
  -- someone else. `initiated_by` is `not null references auth.users(id)` on the case row.
  --
  -- ★ HISTORICAL INITIATOR, AND THE CASE MODEL SETTLES IT RATHER THAN A GUESS. 0052 states that
  -- `initiator_designation_id` / `initiator_capacity` are "a snapshot of fact ('this person acted
  -- as executor'), never an authority the case can later re-assert — a revoked designee does not
  -- keep acting because a case remembers them." So a designation revoked after initiation must NOT
  -- suppress this message: the notification asserts no authority, it reports one fact about
  -- something the recipient personally did. They already know they initiated it; being told it
  -- stopped discloses nothing they did not bring with them. Re-deriving a LIVE designation here
  -- would instead silently drop the message for exactly the person owed it.
  --
  -- ★ IT CANNOT REACH THE OWNER. The owner is the caller (is_estate_owner above), and the guard
  -- below excludes them explicitly. That covers the degenerate case where an estate owner is also
  -- a designee on their own estate: they would otherwise receive claimant-facing copy about their
  -- own halt, which reads as a message from a stranger about their own death process.
  --
  -- ★ NO DEEP LINK, DELIBERATELY. The recipient's own surface is `/executor`
  -- (`get_executor_workspace`, which refuses a revoked designee) — but the RN deep-link allowlist
  -- in `features/notifications/actions.ts` has no `afterworth://executor` key, and a link that is
  -- not in the allowlist resolves to null and renders as a non-navigating row anyway. Passing an
  -- unmatched string would be inventing a route rather than using one. Wiring that destination is
  -- a bounded mobile follow-up, recorded in docs/phase11l-halt-notification.md §6.
  --
  -- ★ EMISSION IS INSIDE THIS TRANSACTION, so it commits with the halt or not at all — no
  -- notification can precede or outlive the state change it describes. The idempotent-replay
  -- return above happens BEFORE any of this, so a second challenge emits nothing. And when no case
  -- was open, `v_initiator` is null and nothing is emitted: a halt with no initiated process to
  -- report has nobody to report it to.
  if v_initiator is not null and v_initiator <> v_uid then
    perform public.emit_lifecycle_notification(
      v_initiator, p_estate, 'death_process.halted', null);
  end if;

  -- ★ NO PROVENANCE. The fact recorded is THAT the owner challenged and from which state — never
  -- a channel, a device, an address, or a location (§17: provenance is security-sensitive
  -- information about a living owner).
  perform public.write_audit(
    'death_process.challenged', 'estate_lifecycle', null, p_estate,
    jsonb_build_object('severity', 'high', 'from_state', v_state));
  return 'challenge_halted';
end $function$;
revoke execute on function public.challenge_death_process(uuid) from public, anon;
grant  execute on function public.challenge_death_process(uuid) to authenticated;

comment on function public.challenge_death_process(uuid) is
  'The owner challenge (Phase 11-E, R12-R14): the authenticated estate owner halts a pre-released '
  'death process in one action — no evidence, no review, no waiting, no designation. Wins ties '
  '(release requires the window strictly elapsed; both serialize on the lifecycle row lock). '
  'Produces challenge_halted, terminal in 11-E. Records no provenance beyond the act itself.';

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- release_estate — REMOVED IN PHASE 11-F. Its replacement is `authorize_release` above.
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ REMOVED FROM SOURCE, AND DROPPED BY MIGRATION 0055 — both halves are required. 11-E's
-- `release_estate(uuid)` released on ONE operator's say-so, which D1 forbids. Deleting only the
-- source would leave the function alive in every database that ever applied 11-E, because
-- `create or replace` cannot remove what it no longer mentions; dropping only in the migration
-- would let the next bundle paste recreate it from source. So the definition is gone from here and
-- the drop ships in the migration beside it — the 0053 precedent, applied to an actor rather than
-- to an argument.
--
-- A caller that was never rewired now fails loudly (`function does not exist`) instead of quietly
-- releasing an estate without a second reviewer.

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- get_owner_safety_status(p_estate) → text                          [authenticated, owner-gated]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- The owner-facing presentation of their own estate's safety state — a CLOSED four-value union,
-- deliberately coarser than the lifecycle: the owner surface needs "is there something to halt",
-- never the machine's internals. An owner is authorized to know this about their own estate; no
-- one else may ask (same byte-identical refusal discipline as the challenge).
--
--   none          nothing to challenge (no death process, or it concluded without release)
--   challengeable a death process is underway and the owner may halt it
--   halted        the owner (or a prior challenge) halted the process
--   released      the process completed; the owner arrived too late to halt (stated honestly)
create or replace function public.get_owner_safety_status(p_estate uuid)
 returns text
 language plpgsql
 security definer
 stable
 set search_path to 'public'
as $function$
declare
  v_uid   uuid := auth.uid();
  v_state text;
begin
  if v_uid is null then
    raise exception 'auth_required' using errcode = '42501';
  end if;
  if not public.is_estate_owner(p_estate) then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  v_state := public.estate_lifecycle_state(p_estate);
  -- ★ THE 11-F STATE JOINS THE `challengeable` GROUP, and that is the safety-preserving mapping:
  -- an owner who has just received the email is squarely in the population this surface exists for.
  -- The union stays four values on purpose — the owner needs "can I stop this", never the machine's
  -- internals, and a client that could distinguish dispatched from windowed would be a client with
  -- something to branch on.
  return case v_state
    when 'death_verification_pending'    then 'challengeable'
    when 'death_verified'                then 'challengeable'
    when 'owner_notification_dispatched' then 'challengeable'
    when 'challenge_window'              then 'challengeable'
    when 'challenge_halted'              then 'halted'
    when 'released'                      then 'released'
    else 'none'
  end;
end $function$;
revoke execute on function public.get_owner_safety_status(uuid) from public, anon;
grant  execute on function public.get_owner_safety_status(uuid) to authenticated;

comment on function public.get_owner_safety_status(uuid) is
  'Owner-scoped safety status (Phase 11-E): a closed presentation union (none / challengeable / '
  'halted / released) over the authoritative lifecycle, for the challenge surface. Owner-only; '
  'every other caller refuses byte-identically. Not an authorization and not a disclosure: it '
  'answers about the process, never about estate content.';

commit;
-- ★ If you see an error above and no COMMIT, nothing was applied. Fix the cause and paste again.
