-- GENERATED by scripts/buildDeathVerificationBundle.mjs — DO NOT EDIT.
-- Edit the sources instead:
--   db/migrations/0052_20260812_death_verification_foundation.sql
--   db/migrations/0054_20260812_challenge_window_release_seam.sql
--   db/functions/estate_lifecycle_state.sql
--   db/functions/death_verification.sql
--   db/functions/release_safety.sql
--
-- Paste this whole file into the Supabase SQL editor and run it once.
-- The migration is idempotent and every function is CREATE OR REPLACE, so re-running is safe.

-- ==== db/migrations/0052_20260812_death_verification_foundation.sql ===============================
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- 0052 · PHASE 11-C — death event + evidence + verification-state FOUNDATION (data model only)
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- ★ THIS MIGRATION CHANGES NO DISCLOSURE. It creates three tables and grants NOTHING to any client
-- role. Every read path answers exactly what it answered before, for every stored row — the Phase
-- 11-C SQL suite compares composed viewer payloads across every new state to prove it.
--
-- What exists after this migration:
--
--   1 · `estate_lifecycle` — the AUTHORITATIVE estate lifecycle record Phase 11-B deferred here.
--       One current state per estate. `claim_packets.status` stops being the only carrier of
--       anything lifecycle-shaped: the claim row is EVIDENCE FOR a lifecycle event, never the event.
--       (`estate_release_state()` remains what it was — a label-only projection of claim status
--       with one consumer — untouched, still consulted by no authorization path.)
--
--   2 · `death_verification_cases` — the death-verification case: who initiated, in what fiduciary
--       capacity, under what jurisdiction context, what the policy REQUIRED at initiation, and what
--       has actually been ATTAINED. Required and attained are different columns with different
--       writers, and the attained baseline is NULL — nothing attained — which is the fail-closed
--       floor every comparison must coalesce against.
--
--   3 · `death_verification_evidence` — evidence received for a case. Evidence KIND is not modelled
--       here as a new vocabulary: an evidence row references a `documents` row, and the document
--       taxonomy (a server catalog) is the authoritative descriptor of what a document is. Review
--       status says only what the platform actually did — `received` / `reviewed_accepted` /
--       `reviewed_rejected` — never "verified": no authenticity vendor exists, and a status that
--       claimed verification would be a fact the system does not possess.
--
-- ★ WHAT IS DELIBERATELY IMPOSSIBLE HERE:
--
--   · `released` is NOT in the lifecycle CHECK. Making an estate released is not a state this
--     schema can store, let alone a transition a routine could take. Widening that CHECK is 11-D's
--     controlled, reviewed change — not a value waiting for a writer.
--   · `event_type` admits ONLY 'death'. Incapacity is a legally distinct event (D9); the fused
--     death-or-incapacity shape is unrepresentable for new rows. Widening the CHECK is an explicit
--     future migration, not an accepted value.
--   · No client role can read or write any of the three tables. RLS is enabled and there are ZERO
--     grants and ZERO policies — the tables are reachable only through the SECURITY DEFINER
--     routines in `db/functions/death_verification.sql`, each of which carries its own gate.
--   · Nothing here manufactures a grant, a disclosure tier, or a fiduciary capacity. The case
--     records facts ABOUT verification; it is not itself an access instrument.
--
-- ★ REQUIRED vs ATTAINED. `required_level_at_initiation` is a SNAPSHOT of what
-- `public.required_verification_level(estate)` answered when the case was opened — recorded so the
-- case file is honest about the policy in force at initiation. It is NEVER the enforcement input:
-- the decision routine re-derives the requirement live at decision time, so a policy tightened
-- mid-case tightens the case. The snapshot cannot leak into `attained_level` — different columns,
-- different writers, and the suite mutation-proves that initiation leaves attained NULL.
--
-- IDEMPOTENT. Safe to re-apply: `create table if not exists`, `create index if not exists`, and
-- the self-checks at the end raise rather than silently no-op.
--
-- APPLY ORDER: requires migrations 0019 (estate_designations), 0026/0027 (verification_level enum +
-- policy engine), 0035 (documents write path exists in practice) — all deployed long before this
-- file. Standing Phase 11-B rule unchanged: `release_conditions_bundle.sql` is pasted FIRST before
-- any other bundle re-application. The `death_verification_bundle.sql` artifact bundles this file
-- with its routines in the right order for a single paste.

\set ON_ERROR_STOP on

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 1 · THE ESTATE LIFECYCLE RECORD — one authoritative current state per estate
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ ABSENT ROW = 'active'. Every estate that has never seen a death-verification case has no row
-- here, and `estate_lifecycle_state()` reads that absence as the base state. That keeps the table
-- append-on-first-event rather than requiring a backfill trigger on estate creation, and it means
-- the empty table is a correct table, not a missing one.
--
-- ★ HISTORY LIVES IN `audit_logs`. Every transition writes an audit row carrying from/to/case/actor
-- (see `apply_estate_lifecycle_transition`), so the current-state row can stay a single row per
-- estate without losing the append-only trail the 11-A forensics review required.
create table if not exists public.estate_lifecycle (
  estate_id  uuid primary key references public.estates(id) on delete cascade,
  -- 'released', 'frozen', 'release_pending' are DELIBERATELY NOT HERE. A value with no writer is a
  -- value waiting for one; the 11-D activation adds states the same reviewed way this file adds
  -- these three. `death_verified` IS reachable in 11-C — through exactly one admin-gated routine
  -- that enforces attained ≥ required — and the Phase 11-C suite proves reaching it changes no
  -- viewer payload by one byte.
  state           text        not null default 'active'
    check (state in ('active', 'death_verification_pending', 'death_verified')),
  updated_at      timestamptz not null default now(),
  -- The case that most recently moved this estate's state (null for the base row shape). Kept as a
  -- plain FK for forensics; authority never flows FROM this column.
  updated_case_id uuid
);

alter table public.estate_lifecycle enable row level security;
-- ZERO grants, ZERO policies — not client-readable, not client-writable, by construction. The
-- jurisdiction_policy precedent: a table only DEFINER routines may touch needs no latent policy
-- inviting a future grant to widen it.

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 2 · THE DEATH-VERIFICATION CASE
-- ────────────────────────────────────────────────────────────────────────────────────────────────
create table if not exists public.death_verification_cases (
  id                           uuid        primary key default gen_random_uuid(),
  estate_id                    uuid        not null references public.estates(id) on delete cascade,
  -- ★ ONLY 'death'. Incapacity is a distinct event with a deferred workflow (D9); admitting it here
  -- before that workflow exists would be vocabulary ahead of authorization. The fused value is
  -- unrepresentable — that is the point.
  event_type                   text        not null default 'death'
    check (event_type in ('death')),
  status                       text        not null default 'open'
    check (status in ('open', 'verified', 'rejected', 'cancelled')),
  initiated_by                 uuid        not null references auth.users(id),
  -- The designation row that AUTHORIZED initiation, and the capacity it carried at that moment.
  -- Capacity is a snapshot of fact ("this person acted as executor"), never an authority the case
  -- can later re-assert — a revoked designee does not keep acting because a case remembers them.
  initiator_designation_id     uuid        not null references public.estate_designations(id),
  initiator_capacity           text        not null
    check (initiator_capacity in ('executor', 'trustee')),
  -- Snapshot of `estates.jurisdiction` at initiation. NULL is a legal, honest value — an estate
  -- with no jurisdiction resolves to the fail-closed maximum requirement, and recording NULL here
  -- says "unknown at initiation" rather than inventing a jurisdiction.
  jurisdiction_context         text,
  -- What the policy engine REQUIRED when the case opened. A record, not the enforcement input —
  -- the decision routine re-derives live. Typed to the same enum as the requirement engine so the
  -- two can never drift vocabularies.
  required_level_at_initiation public.verification_level not null,
  -- What has actually been ATTAINED. NULL = nothing attained — the fail-closed baseline every
  -- comparison must coalesce against. Written by exactly one admin-gated routine; the enum type
  -- makes an out-of-vocabulary level unrepresentable rather than merely refused.
  attained_level               public.verification_level,
  decided_by                   uuid        references auth.users(id),
  decided_at                   timestamptz,
  decision_note                text,
  created_at                   timestamptz not null default now(),
  updated_at                   timestamptz not null default now()
);

-- ★ ONE OPEN CASE PER ESTATE — the claim_packets_one_active_per_estate precedent. Decided cases
-- (verified / rejected / cancelled) are history and coexist; a second OPEN case is a conflict, not
-- a queue.
create unique index if not exists death_verification_cases_one_open_per_estate
  on public.death_verification_cases (estate_id) where status = 'open';
create index if not exists death_verification_cases_estate_idx
  on public.death_verification_cases (estate_id);

alter table public.death_verification_cases enable row level security;
-- ZERO grants, ZERO policies. Unlike `claim_packets` (which the mobile client reads directly under
-- `claim_own_read`), no client surface reads cases in 11-C — so nothing is granted, and an
-- unauthorized viewer cannot learn a case EXISTS, which is itself protected information (T9/H1:
-- whether a death claim is in flight is a fact about a person).

-- The lifecycle FK arrives after the cases table exists (forward reference above).
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'estate_lifecycle_updated_case_id_fkey'
  ) then
    alter table public.estate_lifecycle
      add constraint estate_lifecycle_updated_case_id_fkey
      foreign key (updated_case_id) references public.death_verification_cases(id);
  end if;
end $$;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 3 · EVIDENCE — received, reviewed, never "verified"
-- ────────────────────────────────────────────────────────────────────────────────────────────────
create table if not exists public.death_verification_evidence (
  id            uuid        primary key default gen_random_uuid(),
  case_id       uuid        not null references public.death_verification_cases(id) on delete cascade,
  -- Denormalized estate scope so cross-estate smuggling is refusable without a join, and provable
  -- by constraint in the routines (the attach routine asserts document.estate_id = case.estate_id).
  estate_id     uuid        not null references public.estates(id) on delete cascade,
  -- ★ NO `on delete` CLAUSE — deliberate. `documents` is the single secure store (the Vault); an
  -- evidence pin does not copy bytes, it references them. A vault deletion that would orphan
  -- OPEN-case evidence fails the FK instead of silently un-evidencing a case. (The claim pins chose
  -- `on delete set null` + an explicit `blocked_active_claim` guard inside the delete routine;
  -- giving this FK the same polished sentinel is recorded in the 11-C deferred ledger rather than
  -- edited into `delete_vault_document` here, because that function is deployed and unbundled, and
  -- editing it would open a source↔deployment drift this phase does not need.)
  document_id   uuid        not null references public.documents(id),
  submitted_by  uuid        not null references auth.users(id),
  submitted_at  timestamptz not null default now(),
  -- What the platform actually did with it. 'received' is the entire truth at insert time — no
  -- authenticity vendor exists, and nothing here may claim one does (D1; brief §13).
  review_status text        not null default 'received'
    check (review_status in ('received', 'reviewed_accepted', 'reviewed_rejected')),
  reviewed_by   uuid        references auth.users(id),
  reviewed_at   timestamptz,
  review_note   text
);

create index if not exists death_verification_evidence_case_idx
  on public.death_verification_evidence (case_id);
create index if not exists death_verification_evidence_document_idx
  on public.death_verification_evidence (document_id);

alter table public.death_verification_evidence enable row level security;
-- ZERO grants, ZERO policies — same posture, same reason.

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 4 · PROVE THE FOUNDATION TOOK, IN THE MIGRATION ITSELF
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ BOTH DIRECTIONS, LIKE 0051: the states this phase needs must be admitted, and the states this
-- phase must NOT make storable must be absent from the constraint text. A CHECK that silently
-- failed to apply reads identically from the accepting side.
do $$
declare
  v_def text;
begin
  -- Lifecycle vocabulary: the three foundation states this migration owns must be present.
  --
  -- ★ EDITED IN PHASE 11-E (0052 has never been deployed; the bundles re-apply this file after
  -- 0054). The original check raised if 'released' was storable — correct while 0052 was the last
  -- word on the vocabulary, and WRONG the moment 0054 deliberately widened it: a re-applied bundle
  -- would read the widened CHECK and abort its own idempotent re-paste. The absence pin did not
  -- weaken — it MOVED to where the vocabulary now lives: 0054's self-check pins exactly six states
  -- and refuses invented ones, and the SQL suite enumerates the deployed CHECK on every run.
  select pg_get_constraintdef(con.oid) into v_def
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
   where nsp.nspname = 'public' and rel.relname = 'estate_lifecycle'
     and con.contype = 'c' and pg_get_constraintdef(con.oid) ilike '%state%';
  if v_def is null then
    raise exception '0052 FAILED: estate_lifecycle has no state CHECK';
  end if;
  if position('active' in v_def) = 0
     or position('death_verification_pending' in v_def) = 0
     or position('death_verified' in v_def) = 0 then
    raise exception '0052 FAILED: lifecycle CHECK is missing an 11-C foundation state: %', v_def;
  end if;

  -- Event vocabulary: death only; the fused shape unrepresentable.
  select pg_get_constraintdef(con.oid) into v_def
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
   where nsp.nspname = 'public' and rel.relname = 'death_verification_cases'
     and con.contype = 'c' and pg_get_constraintdef(con.oid) ilike '%event_type%';
  if v_def is null then
    raise exception '0052 FAILED: death_verification_cases has no event_type CHECK';
  end if;
  if position('incapacity' in v_def) > 0 then
    raise exception '0052 FAILED: event_type admits an incapacity value — D9 keeps the events '
      'distinct and the incapacity workflow deferred: %', v_def;
  end if;

  -- Required and attained are BOTH the policy engine's enum — no duplicate ladder, no drift.
  if (select count(*)
        from information_schema.columns
       where table_schema = 'public' and table_name = 'death_verification_cases'
         and column_name in ('required_level_at_initiation', 'attained_level')
         and udt_name = 'verification_level') <> 2 then
    raise exception '0052 FAILED: required/attained levels are not both typed '
      'public.verification_level — a second vocabulary would drift from the policy engine';
  end if;

  -- The attained baseline is fail-closed: no default may exist on the column.
  if (select column_default
        from information_schema.columns
       where table_schema = 'public' and table_name = 'death_verification_cases'
         and column_name = 'attained_level') is not null then
    raise exception '0052 FAILED: attained_level has a DEFAULT — the baseline must be NULL '
      '(nothing attained), not a granted starting level';
  end if;

  -- No client role can touch any of the three tables.
  if exists (
    select 1
      from information_schema.role_table_grants
     where table_schema = 'public'
       and table_name in ('estate_lifecycle', 'death_verification_cases', 'death_verification_evidence')
       and grantee in ('anon', 'authenticated')
  ) then
    raise exception '0052 FAILED: a client role holds a table grant on the death-verification '
      'foundation — these tables are DEFINER-routine-only';
  end if;

  raise notice '0052 · death-verification foundation in place (lifecycle, case, evidence; '
    'released unrepresentable; attained baseline NULL; client roles grant-less)';
end $$;


-- ==== db/migrations/0054_20260812_challenge_window_release_seam.sql ===============================
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- 0054 · PHASE 11-E — the challenge window: the safety seam between death_verified and released
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- ★ WHAT THIS PHASE INSERTS, AND WHY IT EXISTS. 11-D let `after_verified_death` satisfy at
-- `death_verified`. That connected verification directly to irreversible disclosure — and disclosure
-- cannot be undone (R15: revoking future access is possible; undoing disclosure is not). 11-E
-- inserts the missing safety states between them:
--
--     active → death_verification_pending → death_verified
--            → challenge_window            (verification accepted; release deliberately waiting;
--                                           the owner has been notified and can object)
--            → released                    (the ONLY lifecycle at which owner-authored
--                                           death-conditioned grants may evaluate as satisfied)
--     any pre-released death-process state
--            → challenge_halted            (the authenticated owner objected; terminal in 11-E)
--
-- The predicate change rides in `release_conditions.sql`: `after_verified_death` is FALSE at
-- death_verified, FALSE throughout challenge_window, FALSE at challenge_halted, TRUE only at
-- released. So this migration making `released` STORABLE widens no disclosure: the only writer is
-- `release_estate` (client-revoked, no reachable door in 11-E), behind an elapsed, configured,
-- owner-notified, unchallenged window.
--
-- ★ THE WINDOW DURATION IS CONFIGURATION, NOT A GUESS. `release_safety_policy` ships EMPTY: no
-- default duration is seeded, because the duration is a product decision this phase does not own.
-- Fail-closed direction: an estate can always ENTER the challenge window (the owner-safety clock
-- and notice), but with no configured duration the window NEVER ELAPSES and release refuses with
-- `release_window_not_configured`. The duration is re-read LIVE at release time (the H2 precedent:
-- a policy tightened mid-window tightens the window) — never stamped at entry.
--
-- ★ THE OWNER CHALLENGE IS CHEAPER THAN THE CLAIM (R13) AND WINS TIES (R14). No evidence, no
-- review, no waiting period, no designation — one authenticated owner action. The tiebreak is
-- structural: release requires the window STRICTLY elapsed (`now() > notified_at + duration`), so
-- at the exact boundary instant release refuses while challenge still succeeds; both transitions
-- serialize on the lifecycle row lock, and nothing transitions out of challenge_halted.
--
-- IDEMPOTENT. Safe to re-apply. APPLY ORDER: after 0052/0053, inside the bundles that carry it.

\set ON_ERROR_STOP on

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 1 · WIDEN the lifecycle vocabulary to the six-state safety machine. Additive only.
-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- The constraint name is resolved from the catalog, not guessed (the 0051 lesson).
do $$
declare
  v_name text;
begin
  for v_name in
    select con.conname
      from pg_constraint con
      join pg_class rel on rel.oid = con.conrelid
      join pg_namespace nsp on nsp.oid = rel.relnamespace
     where nsp.nspname = 'public'
       and rel.relname = 'estate_lifecycle'
       and con.contype = 'c'
       and pg_get_constraintdef(con.oid) ilike '%state%'
  loop
    execute format('alter table public.estate_lifecycle drop constraint %I', v_name);
  end loop;

  alter table public.estate_lifecycle
    add constraint estate_lifecycle_state_check
    check (state in (
      'active',
      'death_verification_pending',
      'death_verified',
      -- Phase 11-E: the safety seam. Storable here; REACHABLE only through the closed transition
      -- map in apply_estate_lifecycle_transition, and 'released' only through release_estate.
      'challenge_window',
      'challenge_halted',
      'released'
    ));
end $$;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 2 · THE SAFETY FACTS live on the lifecycle row: when the owner was notified, when the window
--     opened, when it was halted or released, and WHICH notification row is the safety notice.
--     Facts, never authority — release re-derives everything live.
-- ────────────────────────────────────────────────────────────────────────────────────────────────
alter table public.estate_lifecycle add column if not exists owner_notified_at            timestamptz;
alter table public.estate_lifecycle add column if not exists challenge_window_started_at  timestamptz;
alter table public.estate_lifecycle add column if not exists halted_at                    timestamptz;
alter table public.estate_lifecycle add column if not exists released_at                  timestamptz;
alter table public.estate_lifecycle add column if not exists safety_notification_id       uuid;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 3 · A HALTED CASE IS ITS OWN STATUS. The owner challenge halts any open case; 'cancelled' means
--     the initiator withdrew and reusing it would erase the difference between "the claimant
--     changed their mind" and "the owner said they are alive" — facts with different forensics.
-- ────────────────────────────────────────────────────────────────────────────────────────────────
do $$
declare
  v_name text;
begin
  for v_name in
    select con.conname
      from pg_constraint con
      join pg_class rel on rel.oid = con.conrelid
      join pg_namespace nsp on nsp.oid = rel.relnamespace
     where nsp.nspname = 'public'
       and rel.relname = 'death_verification_cases'
       and con.contype = 'c'
       and pg_get_constraintdef(con.oid) ilike '%status%'
       and pg_get_constraintdef(con.oid) not ilike '%event_type%'
       and pg_get_constraintdef(con.oid) not ilike '%review_status%'
       and pg_get_constraintdef(con.oid) not ilike '%initiator_capacity%'
  loop
    execute format('alter table public.death_verification_cases drop constraint %I', v_name);
  end loop;

  alter table public.death_verification_cases
    add constraint death_verification_cases_status_check
    check (status in ('open', 'verified', 'rejected', 'cancelled',
                      -- Phase 11-E: set only by the owner-challenge routine.
                      'halted'));
end $$;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 4 · THE WINDOW-DURATION CONFIGURATION — one row, definer-only, DELIBERATELY UNSEEDED.
-- ────────────────────────────────────────────────────────────────────────────────────────────────
create table if not exists public.release_safety_policy (
  -- Single-row table: the PK admits exactly `true`.
  id               boolean     primary key default true check (id),
  challenge_window interval    not null,
  updated_at       timestamptz not null default now()
);

alter table public.release_safety_policy enable row level security;
-- ZERO grants, ZERO policies — reachable only through the DEFINER reader. No seed row: the
-- duration is a product/operator decision recorded by an explicit, reviewed INSERT, and until it
-- exists the release window cannot elapse anywhere.

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 5 · PROVE THE SEAM TOOK, IN THE MIGRATION ITSELF (both directions, the 0051/0052 discipline).
-- ────────────────────────────────────────────────────────────────────────────────────────────────
do $$
declare
  v_def text;
begin
  select pg_get_constraintdef(con.oid) into v_def
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
   where nsp.nspname = 'public' and rel.relname = 'estate_lifecycle'
     and con.contype = 'c' and pg_get_constraintdef(con.oid) ilike '%state%';
  if v_def is null then
    raise exception '0054 FAILED: estate_lifecycle has no state CHECK after the widening';
  end if;
  if position('challenge_window' in v_def) = 0
     or position('challenge_halted' in v_def) = 0
     or position('released' in v_def) = 0 then
    raise exception '0054 FAILED: the safety vocabulary is incomplete: %', v_def;
  end if;
  if (select count(*) from regexp_matches(v_def, '''[a-z_]+''', 'g')) <> 6 then
    raise exception '0054 FAILED: the lifecycle vocabulary is not exactly six states: %', v_def;
  end if;
  -- 'frozen' and other invented states must still be unrepresentable.
  if position('frozen' in v_def) > 0 then
    raise exception '0054 FAILED: an unapproved lifecycle state is storable: %', v_def;
  end if;

  select pg_get_constraintdef(con.oid) into v_def
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
   where nsp.nspname = 'public' and rel.relname = 'death_verification_cases'
     and con.conname = 'death_verification_cases_status_check';
  if v_def is null or position('halted' in v_def) = 0 then
    raise exception '0054 FAILED: the case status vocabulary did not gain ''halted'': %',
      coalesce(v_def, '<absent>');
  end if;

  -- The policy table is definer-only and EMPTY: a seeded duration would be a product decision
  -- taken by a migration.
  if exists (
    select 1 from information_schema.role_table_grants
     where table_schema = 'public' and table_name = 'release_safety_policy'
       and grantee in ('anon', 'authenticated')
  ) then
    raise exception '0054 FAILED: a client role holds a grant on release_safety_policy';
  end if;
  if (select count(*) from public.release_safety_policy) <> 0 then
    -- On RE-application to a database whose operator later configured the window, a row is
    -- legitimate — the check refuses only a duration arriving in the SAME transaction that
    -- created the table (i.e. seeded by migration).
    if (select min(updated_at) from public.release_safety_policy) >= transaction_timestamp() then
      raise exception '0054 FAILED: release_safety_policy was seeded by this migration — the '
        'window duration is a product decision, not a default';
    end if;
  end if;

  raise notice '0054 · challenge-window seam in place (6 lifecycle states; halted case status; '
    'safety facts columns; duration configuration table EMPTY and definer-only)';
end $$;


-- ==== db/functions/estate_lifecycle_state.sql =====================================================
-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- estate_lifecycle_state(p_estate) → text            [INTERNAL — the authoritative lifecycle read]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ EXTRACTED FROM `death_verification.sql` IN PHASE 11-D, because the seam changed sides. In 11-C
-- this reader existed for the death-verification routines and was consulted by nobody else — that
-- absence was the firewall. In 11-D the canonical release predicate consumes lifecycle state as an
-- argument, so every disclosure evaluator resolves it at read time. The reader therefore ships in
-- `release_conditions_bundle.sql` (the FIRST artifact an operator pastes), so that no paste order
-- ever leaves a consumer referencing a reader that does not exist yet. The death-verification
-- bundle also carries it (idempotent re-create), keeping that artifact single-paste runnable.
--
-- ★ ABSENT ROW = 'active'. An estate that has never seen a death-verification case has no row in
-- `estate_lifecycle`, and this reader answers the base state. The empty table is a correct table.
--
-- ★ THE CLOSED SET IS THE TABLE'S, NOT THIS FUNCTION'S. The CHECK on `estate_lifecycle.state`
-- (migration 0052) admits exactly 'active' / 'death_verification_pending' / 'death_verified', and
-- the canonical predicate REFUSES any lifecycle value outside that set — so a state this reader
-- could never produce fails closed at the predicate rather than being interpreted.
--
-- ★ NO CLIENT MAY EXECUTE THIS. A client that can map estate → lifecycle state has been handed a
-- death-status oracle for arbitrary estates. Its callers are SECURITY DEFINER routines (the
-- death-verification module and the disclosure evaluators) and the SQL suite. The disclosure rule
-- for consumers is pinned by `test/deathVerificationFoundation.test.ts`: outside the death module,
-- this function may appear ONLY as the lifecycle argument of `public.release_condition_satisfied` —
-- never as the subject of a local comparison, which would be release policy leaking out of the
-- canonical predicate one `if` at a time.
create or replace function public.estate_lifecycle_state(p_estate uuid)
 returns text
 language sql
 security definer
 stable
 set search_path to 'public'
as $function$
  select coalesce(
    (select l.state from public.estate_lifecycle l where l.estate_id = p_estate),
    'active');
$function$;
revoke execute on function public.estate_lifecycle_state(uuid) from public, anon, authenticated;

comment on function public.estate_lifecycle_state(uuid) is
  'THE authoritative estate lifecycle read (Phase 11-C, extracted 11-D). Absent row = active. '
  'INTERNAL: execute revoked from every client role — a client that can map estate to lifecycle '
  'state holds a death-status oracle. Consumed by the death-verification routines and, since 11-D, '
  'as the lifecycle argument to public.release_condition_satisfied inside disclosure evaluators. '
  'Never derived from claim_packets.status, evidence, or attained verification levels.';


-- ==== db/functions/death_verification.sql =========================================================
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- PHASE 11-C · DEATH-VERIFICATION ROUTINES — initiation, evidence, review, decision, lifecycle
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- ★ NOTHING IN THIS FILE RELEASES ANYTHING. No routine here writes `access_grants`, `documents`,
-- `encrypted_instructions`, `claim_packets`, `notifications`, or any visibility tier. No routine
-- calls `release_condition_satisfied`, `estate_release_state`, or any disclosure projection. The
-- case is a record of facts about verification — it is never an access instrument, and the Phase
-- 11-C suite proves every state it can reach leaves every viewer's composed payload byte-identical.
--
-- ★ THE GATES LIVE INSIDE THE DEFINERS (the DEFINER-door discipline). Every client-reachable
-- routine re-derives its own authority; nothing trusts a wrapper.
--
-- ★ REFUSAL SHAPE. For the client-reachable routines the unauthorized answer is ONE sentinel —
-- `not_authorized` (42501) — for every cause an unauthenticated identity check does not cover:
-- nonexistent estate, real-but-foreign estate, nonexistent case, foreign case, wrong role, revoked
-- designation. The gate runs BEFORE any existence lookup can differentiate, so a probe cannot use
-- refusal bytes to learn whether an estate or case exists (T9: case existence is itself protected).
-- `auth_required` for a missing session is the one distinguishable cause, matching every existing
-- gate in the repo. Admin routines may name their causes — an authenticated platform admin behind
-- AAL2 + freshness is authorized to know a case exists.
--
-- ★ REQUIRED ≥ ATTAINED IS ENFORCED HERE (H2 closed). `admin_decide_death_verification_case`
-- re-derives the required level LIVE at decision time and refuses `verify` unless the attained
-- level meets it. The initiation-time snapshot on the case row is a record for the case file,
-- never the enforcement input — a policy tightened mid-case tightens the case.
--
-- Deploys via `db/bundles/death_verification_bundle.sql` (migration 0052 + the lifecycle reader +
-- this file). Source of truth — re-apply on DB reset.
--
-- ★ `estate_lifecycle_state` MOVED OUT IN PHASE 11-D — see `db/functions/estate_lifecycle_state.sql`.
-- The reader now ships with the release-conditions bundle (the disclosure evaluators consume it as
-- the predicate's lifecycle argument, and the FIRST pasted artifact must carry the seam so no paste
-- order leaves a consumer referencing a reader that does not exist). The routines below still call
-- it at execution time; the death bundle carries the same source file so it stays single-paste
-- runnable.

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- apply_estate_lifecycle_transition(p_estate, p_to, p_case, p_reason) → void          [INTERNAL]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ THE ONLY WRITER of `estate_lifecycle`, and the transition map is written out as the closed set
-- it is. Eight legal moves since 11-E:
--
--     active                      → death_verification_pending   (case initiated)
--     death_verification_pending  → active                       (case rejected / cancelled)
--     death_verification_pending  → death_verified               (admin decision, attained ≥ required)
--     death_verified              → challenge_window             (window opened, owner notified — 11-E)
--     death_verification_pending  → challenge_halted             (owner challenge — 11-E)
--     death_verified              → challenge_halted             (owner challenge — 11-E)
--     challenge_window            → challenge_halted             (owner challenge — 11-E)
--     challenge_window            → released                     (window elapsed, release_estate — 11-E)
--
-- Everything else raises. Two absences are the load-bearing half of the 11-E map:
--
--   · NOTHING LEAVES challenge_halted. The owner said no; there is no resume, no admin override,
--     no reopen — restoring one is a future product decision, not a bigger map (R: 11-E brief §7).
--   · NOTHING LEAVES released. Disclosure cannot be undone (R15); a post-release freeze would be a
--     new product surface, not an edge here.
--
-- And `released` is REACHABLE only through `release_estate` (client-revoked, no caller in 11-E),
-- which alone checks the window guards before asking for this edge.
--
-- ★ TRANSACTIONAL + AUDITED (the 11-A §7 requirement): the current row is locked, the move is
-- validated against it, and one audit row records from/to/case/reason with the acting user.
create or replace function public.apply_estate_lifecycle_transition(
  p_estate uuid,
  p_to     text,
  p_case   uuid,
  p_reason text
)
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_from text;
begin
  select l.state into v_from
    from public.estate_lifecycle l
   where l.estate_id = p_estate
   for update;
  if v_from is null then
    v_from := 'active';
  end if;

  -- The closed map. An unknown current state is unreachable (table CHECK) but still refused here:
  -- unknown state fails closed, it is never a wildcard. challenge_halted and released have NO
  -- outbound edges, deliberately (see the header).
  if not (
       (v_from = 'active'                     and p_to = 'death_verification_pending')
    or (v_from = 'death_verification_pending' and p_to = 'active')
    or (v_from = 'death_verification_pending' and p_to = 'death_verified')
    or (v_from = 'death_verified'             and p_to = 'challenge_window')
    or (v_from = 'death_verification_pending' and p_to = 'challenge_halted')
    or (v_from = 'death_verified'             and p_to = 'challenge_halted')
    or (v_from = 'challenge_window'           and p_to = 'challenge_halted')
    or (v_from = 'challenge_window'           and p_to = 'released')
  ) then
    raise exception 'invalid_lifecycle_transition' using errcode = 'P0001';
  end if;

  insert into public.estate_lifecycle (estate_id, state, updated_at, updated_case_id)
  values (p_estate, p_to, now(), p_case)
  on conflict (estate_id) do update
    set state = excluded.state,
        updated_at = excluded.updated_at,
        updated_case_id = excluded.updated_case_id;

  perform public.write_audit(
    'estate_lifecycle.transition', 'estate_lifecycle', p_case, p_estate,
    jsonb_build_object('from_state', v_from, 'to_state', p_to,
                       'case_id', p_case, 'reason', p_reason));
end $function$;
revoke execute on function public.apply_estate_lifecycle_transition(uuid, text, uuid, text)
  from public, anon, authenticated;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- initiate_death_verification_case(p_estate) → uuid                        [authenticated, gated]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ D2: initiation is DESIGNEE-ONLY — the same canonical fiduciary predicate that gates claim
-- submission (`is_estate_executor`: an ACTIVE executor or trustee designation). Membership roles,
-- disclosure tiers, professional_delegate status, and estate ownership neither qualify nor
-- disqualify: an owner without a designation is refused like any non-designee, and an owner who
-- holds one passes by the designation, exactly as `submit_claim_packet` has always answered.
--
-- ★ THE GATE RUNS BEFORE ANY EXISTENCE LOOKUP. `is_estate_executor` returns false for a
-- nonexistent estate and for a foreign one alike, so both refuse with the same bytes.
create or replace function public.initiate_death_verification_case(p_estate uuid)
 returns uuid
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid          uuid := auth.uid();
  v_designation  uuid;
  v_capacity     text;
  v_state        text;
  v_juris        text;
  v_required     public.verification_level;
  v_case         uuid;
begin
  if v_uid is null then
    raise exception 'auth_required' using errcode = '42501';
  end if;
  if not public.is_estate_executor(p_estate, v_uid) then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  -- The designation that authorizes this initiation, captured as fact on the case. Deterministic
  -- when the caller holds both capacities: 'executor' precedes 'trustee' (current product
  -- semantics rank them identically for initiation; the recorded capacity is a fact, not a power).
  select d.id, d.designation_type
    into v_designation, v_capacity
    from public.estate_designations d
   where d.estate_id = p_estate
     and d.user_id = v_uid
     and d.designation_type in ('executor', 'trustee')
     and d.status = 'active'
   order by d.designation_type
   limit 1;

  -- One live death-verification process per estate. An open case holds the lifecycle at
  -- death_verification_pending; a verified case holds it at death_verified. Both refuse a new
  -- initiation. Only an authorized designee can reach this sentinel, so it is not an oracle.
  v_state := public.estate_lifecycle_state(p_estate);
  if v_state <> 'active' then
    raise exception 'lifecycle_conflict' using errcode = 'P0001';
  end if;

  select e.jurisdiction into v_juris from public.estates e where e.id = p_estate;

  -- The policy engine's answer AT INITIATION, recorded on the case. Fail-closed inside the engine:
  -- unknown / unapproved / NULL jurisdiction answers 'enhanced_kyc'. NEVER copied into attained.
  v_required := public.required_verification_level(p_estate);

  insert into public.death_verification_cases
    (estate_id, event_type, status, initiated_by, initiator_designation_id, initiator_capacity,
     jurisdiction_context, required_level_at_initiation)
  values
    (p_estate, 'death', 'open', v_uid, v_designation, v_capacity, v_juris, v_required)
  returning id into v_case;

  perform public.apply_estate_lifecycle_transition(
    p_estate, 'death_verification_pending', v_case, 'case_initiated');

  perform public.write_audit(
    'death_case.initiated', 'death_verification_cases', v_case, p_estate,
    jsonb_build_object('case_id', v_case, 'event_type', 'death',
                       'initiator_capacity', v_capacity,
                       'required_level_at_initiation', v_required::text,
                       'jurisdiction_known', v_juris is not null));
  return v_case;
end $function$;
revoke execute on function public.initiate_death_verification_case(uuid) from public, anon;
grant  execute on function public.initiate_death_verification_case(uuid) to authenticated;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- attach_death_verification_evidence(p_case, p_document) → uuid            [authenticated, gated]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- Records that a document was RECEIVED as evidence for a case. It does not review, grade, or
-- verify anything, and it touches no verification level — a thousand attachments leave the
-- attained level exactly where it was (brief §13: file upload ≠ document verification).
--
-- The document must belong to the case's estate — the multi-source-agreement rule from
-- `submit_claim_with_evidence`, one join shorter. A document in another estate and a document that
-- does not exist refuse identically.
create or replace function public.attach_death_verification_evidence(p_case uuid, p_document uuid)
 returns uuid
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid        uuid := auth.uid();
  v_estate     uuid;
  v_status     text;
  v_doc_estate uuid;
  v_evidence   uuid;
begin
  if v_uid is null then
    raise exception 'auth_required' using errcode = '42501';
  end if;

  select c.estate_id, c.status into v_estate, v_status
    from public.death_verification_cases c
   where c.id = p_case;
  -- Nonexistent case and foreign case answer with the same bytes: the caller learns nothing about
  -- whether a case exists anywhere they are not a designee.
  if v_estate is null or not public.is_estate_executor(v_estate, v_uid) then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  if v_status <> 'open' then
    raise exception 'case_not_open' using errcode = 'P0001';
  end if;

  select d.estate_id into v_doc_estate from public.documents d where d.id = p_document;
  -- One sentinel for missing and foreign alike: a designee cannot probe the document space of
  -- other estates through attachment errors.
  if v_doc_estate is null or v_doc_estate <> v_estate then
    raise exception 'doc_not_in_estate' using errcode = 'P0001';
  end if;

  insert into public.death_verification_evidence (case_id, estate_id, document_id, submitted_by)
  values (p_case, v_estate, p_document, v_uid)
  returning id into v_evidence;

  perform public.write_audit(
    'death_case.evidence_attached', 'death_verification_evidence', v_evidence, v_estate,
    jsonb_build_object('case_id', p_case, 'evidence_id', v_evidence, 'document_id', p_document));
  return v_evidence;
end $function$;
revoke execute on function public.attach_death_verification_evidence(uuid, uuid) from public, anon;
grant  execute on function public.attach_death_verification_evidence(uuid, uuid) to authenticated;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- cancel_death_verification_case(p_case) → text                            [authenticated, gated]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- The initiator may withdraw an OPEN case — and only while they still hold an active designation:
-- a revoked fiduciary does not keep acting because a case remembers them. Cancellation returns the
-- lifecycle to `active`; the case row survives as history.
create or replace function public.cancel_death_verification_case(p_case uuid)
 returns text
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid          uuid := auth.uid();
  v_estate       uuid;
  v_status       text;
  v_initiated_by uuid;
begin
  if v_uid is null then
    raise exception 'auth_required' using errcode = '42501';
  end if;

  select c.estate_id, c.status, c.initiated_by
    into v_estate, v_status, v_initiated_by
    from public.death_verification_cases c
   where c.id = p_case
   for update;
  if v_estate is null
     or v_initiated_by <> v_uid
     or not public.is_estate_executor(v_estate, v_uid) then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  if v_status = 'cancelled' then
    return v_status; -- idempotent replay: no re-stamp, no re-audit (the claim-decision precedent)
  end if;
  if v_status <> 'open' then
    raise exception 'case_already_decided' using errcode = 'P0001';
  end if;

  update public.death_verification_cases
     set status = 'cancelled', updated_at = now()
   where id = p_case;

  perform public.apply_estate_lifecycle_transition(v_estate, 'active', p_case, 'case_cancelled');

  perform public.write_audit(
    'death_case.cancelled', 'death_verification_cases', p_case, v_estate,
    jsonb_build_object('case_id', p_case));
  return 'cancelled';
end $function$;
revoke execute on function public.cancel_death_verification_case(uuid) from public, anon;
grant  execute on function public.cancel_death_verification_case(uuid) to authenticated;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- admin_review_death_evidence(p_evidence, p_outcome, p_note) → text            [admin, AAL2+fresh]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- Records the platform's review of one received evidence item. The outcome vocabulary says what
-- happened — a reviewer accepted or rejected the item — never that a document is authentic (no
-- vendor exists to say so). Reviewing evidence DOES NOT move the attained level: that is a
-- separate, separately-audited act, so "the file looked right" can never silently become "the
-- death is verified" (T15).
create or replace function public.admin_review_death_evidence(
  p_evidence uuid,
  p_outcome  text,
  p_note     text default null
)
 returns text
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid     uuid;
  v_case    uuid;
  v_estate  uuid;
  v_status  text;
begin
  perform public.admin_require_gate();
  v_uid := auth.uid();

  if p_outcome not in ('reviewed_accepted', 'reviewed_rejected') then
    raise exception 'invalid_review_outcome' using errcode = 'P0001';
  end if;

  select e.case_id, e.estate_id, e.review_status
    into v_case, v_estate, v_status
    from public.death_verification_evidence e
   where e.id = p_evidence
   for update;
  if v_case is null then
    raise exception 'evidence_not_found' using errcode = 'P0002';
  end if;

  if v_status = p_outcome then
    return v_status; -- idempotent replay: no re-stamp, no re-audit
  end if;
  if v_status <> 'received' then
    raise exception 'evidence_already_reviewed' using errcode = 'P0001';
  end if;

  update public.death_verification_evidence
     set review_status = p_outcome, reviewed_by = v_uid, reviewed_at = now(), review_note = p_note
   where id = p_evidence;

  -- Direct insert, source='admin', severity high — the admin_decide_claim_packet precedent.
  -- Metadata names ids and the outcome; never document contents, titles, or claimant identity.
  insert into public.audit_logs (actor_id, estate_id, action, target_table, target_id, metadata, source)
  values (v_uid, v_estate, 'death_case.evidence_reviewed', 'death_verification_evidence', p_evidence,
          jsonb_build_object('severity', 'high', 'case_id', v_case,
                            'evidence_id', p_evidence, 'outcome', p_outcome),
          'admin');
  return p_outcome;
end $function$;
revoke execute on function public.admin_review_death_evidence(uuid, text, text) from public, anon;
grant  execute on function public.admin_review_death_evidence(uuid, text, text) to authenticated;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- admin_set_attained_verification_level(p_case, p_level, p_basis) → text       [admin, AAL2+fresh]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ THE ONLY WRITER of `attained_level`. The parameter is TYPED to the policy engine's enum, so an
-- out-of-vocabulary level is unrepresentable at the call boundary — it fails Postgres enum
-- decoding before this body runs, and there is no text path around it. NULL is refused: attained
-- never returns to "unknown" by assertion; it starts there and moves only by this audited act.
--
-- Nothing here compares the level to the requirement — attainment is a fact, sufficiency is the
-- DECISION routine's question. And nothing here derives a level from evidence counts: a reviewer
-- states what the review process actually established, with the basis recorded.
create or replace function public.admin_set_attained_verification_level(
  p_case  uuid,
  p_level public.verification_level,
  p_basis text default null
)
 returns text
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid    uuid;
  v_estate uuid;
  v_status text;
  v_old    public.verification_level;
begin
  perform public.admin_require_gate();
  v_uid := auth.uid();

  if p_level is null then
    raise exception 'invalid_verification_level' using errcode = 'P0001';
  end if;

  select c.estate_id, c.status, c.attained_level
    into v_estate, v_status, v_old
    from public.death_verification_cases c
   where c.id = p_case
   for update;
  if v_estate is null then
    raise exception 'case_not_found' using errcode = 'P0002';
  end if;
  if v_status <> 'open' then
    raise exception 'case_not_open' using errcode = 'P0001';
  end if;

  if v_old is not distinct from p_level then
    return p_level::text; -- idempotent replay: no re-stamp, no re-audit
  end if;

  update public.death_verification_cases
     set attained_level = p_level, updated_at = now()
   where id = p_case;

  insert into public.audit_logs (actor_id, estate_id, action, target_table, target_id, metadata, source)
  values (v_uid, v_estate, 'death_case.attained_level_set', 'death_verification_cases', p_case,
          jsonb_build_object('severity', 'high', 'case_id', p_case,
                            'old_level', v_old::text, 'new_level', p_level::text,
                            'basis', p_basis),
          'admin');
  return p_level::text;
end $function$;
revoke execute on function public.admin_set_attained_verification_level(uuid, public.verification_level, text)
  from public, anon;
grant  execute on function public.admin_set_attained_verification_level(uuid, public.verification_level, text)
  to authenticated;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- admin_decide_death_verification_case(p_case, p_decision, p_note) → text      [admin, AAL2+fresh]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ H2 CLOSED HERE: `verify` refuses unless attained ≥ required, with the requirement RE-DERIVED
-- LIVE from the policy engine at decision time — the initiation snapshot is a record, not the
-- gate. A NULL attained level coalesces to refusal (the three-valued-logic trap, handled the way
-- `release_condition_satisfied` handles it).
--
-- ★ VERIFYING A DEATH RELEASES NOTHING. The lifecycle moves to `death_verified` and that is the
-- entire effect: no grant goes live (`release_condition_satisfied` takes no lifecycle state, and
-- `after_verified_death` satisfies nothing under any policy), no notification is emitted, no
-- claim row changes, no read path consults the new state. The 11-C suite compares every viewer's
-- composed payload across this transition and requires byte identity.
create or replace function public.admin_decide_death_verification_case(
  p_case     uuid,
  p_decision text,
  p_note     text default null
)
 returns text
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid      uuid;
  v_estate   uuid;
  v_status   text;
  v_attained public.verification_level;
  v_required public.verification_level;
  v_target   text;
begin
  perform public.admin_require_gate();
  v_uid := auth.uid();

  if p_decision not in ('verify', 'reject') then
    raise exception 'invalid_decision' using errcode = 'P0001';
  end if;
  v_target := case p_decision when 'verify' then 'verified' else 'rejected' end;

  select c.estate_id, c.status, c.attained_level
    into v_estate, v_status, v_attained
    from public.death_verification_cases c
   where c.id = p_case
   for update;
  if v_estate is null then
    raise exception 'case_not_found' using errcode = 'P0002';
  end if;

  if v_status = v_target then
    return v_status; -- idempotent replay: no re-stamp, no re-audit
  end if;
  if v_status <> 'open' then
    raise exception 'case_already_decided' using errcode = 'P0001';
  end if;

  if p_decision = 'verify' then
    -- LIVE requirement, not the snapshot: a policy tightened mid-case tightens the case.
    v_required := public.required_verification_level(v_estate);
    if not coalesce(v_attained >= v_required, false) then
      raise exception 'verification_level_insufficient' using errcode = 'P0001';
    end if;
  end if;

  update public.death_verification_cases
     set status = v_target, decided_by = v_uid, decided_at = now(),
         decision_note = p_note, updated_at = now()
   where id = p_case;

  perform public.apply_estate_lifecycle_transition(
    v_estate,
    case when p_decision = 'verify' then 'death_verified' else 'active' end,
    p_case,
    'case_' || v_target);

  insert into public.audit_logs (actor_id, estate_id, action, target_table, target_id, metadata, source)
  values (v_uid, v_estate, 'death_case.' || v_target, 'death_verification_cases', p_case,
          jsonb_build_object('severity', 'high', 'case_id', p_case, 'decision', p_decision,
                            'required_level', v_required::text, 'attained_level', v_attained::text,
                            'reviewer_id', v_uid),
          'admin');
  return v_target;
end $function$;
revoke execute on function public.admin_decide_death_verification_case(uuid, text, text) from public, anon;
grant  execute on function public.admin_decide_death_verification_case(uuid, text, text) to authenticated;


-- ==== db/functions/release_safety.sql =============================================================
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- PHASE 11-E · RELEASE SAFETY — the challenge window between death_verified and released
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- ★ WHAT THIS FILE OWNS. The three transitions that stand between an accepted death verification
-- and irreversible disclosure, plus the owner-facing status read:
--
--   begin_challenge_window   death_verified → challenge_window     [admin, AAL2+fresh]
--   challenge_death_process  any pre-released death-process state
--                            → challenge_halted                    [the authenticated OWNER, alone]
--   release_estate           challenge_window → released           [INTERNAL — no reachable door]
--   get_owner_safety_status  owner-scoped presentation union       [authenticated, owner-gated]
--
-- ★ WHAT THIS FILE MUST NEVER TOUCH: access_grants, visibility tiers, memberships, designations,
-- documents, claim rows, or the release predicate. Release is EVALUATIVE — the lifecycle moves and
-- the one canonical predicate answers differently. `test/deathVerificationFoundation.test.ts`
-- pins the forbidden set for this file exactly as it does for the death-verification module.
--
-- ★ THE SAFETY NOTIFICATION IS LOAD-BEARING, AND THE EMITTER'S USUAL TRADE IS INVERTED HERE.
-- `emit_lifecycle_notification` deliberately swallows insert failure so that a grant still commits
-- when a heads-up cannot be written — the right trade for a heads-up. The window-open notice is
-- not a heads-up: it is the owner's one chance to object before disclosure becomes irreversible,
-- so `begin_challenge_window` REQUIRES the emit to return a committed row id and rolls the whole
-- transition back otherwise. The window cannot begin un-notified. (Reliability class, stated
-- honestly: one in-app notification row, committed in the SAME transaction as the transition.
-- Whether that class is sufficient to start a release clock in production is part of the window-
-- duration product decision; until an operator configures a duration, no window can elapse.)
--
-- ★ THE TIEBREAK IS STRUCTURAL (R14). Release requires the window STRICTLY elapsed:
-- `now() > owner_notified_at + duration`. At the exact boundary instant the release refuses while
-- the challenge still succeeds; both serialize on the lifecycle row lock; and the transition map
-- has no edge out of challenge_halted, so a committed challenge is final in 11-E — no resume, no
-- admin override (R: deliberately absent, a future product decision).
--
-- ★ CHALLENGE PROVENANCE IS PROTECTED (§17). The audit row records THAT the owner challenged and
-- from which lifecycle state — never a channel, device, address, or location. `write_audit` does
-- not populate ip/user_agent, and nothing here adds them. Claimant-facing surfaces may learn only
-- that the process halted.
--
-- Deploys via `db/bundles/death_verification_bundle.sql` (after 0054 and the workflow routines).
-- Source of truth — re-apply on DB reset.

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- challenge_window_duration() → interval                        [INTERNAL — the configured window]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- NULL means NOT CONFIGURED, and not configured means the window never elapses (fail-closed:
-- release refuses, the challenge stays available). Read LIVE at release time — the H2 precedent:
-- a duration lengthened mid-window lengthens the window; there is no stamped deadline to go stale.
create or replace function public.challenge_window_duration()
 returns interval
 language sql
 security definer
 stable
 set search_path to 'public'
as $function$
  select p.challenge_window from public.release_safety_policy p where p.id;
$function$;
revoke execute on function public.challenge_window_duration() from public, anon, authenticated;

comment on function public.challenge_window_duration() is
  'The configured owner-challenge window (Phase 11-E). NULL = not configured = the window never '
  'elapses and release refuses. Set only by an explicit, reviewed operator INSERT into '
  'release_safety_policy — never seeded by a migration. INTERNAL: clients cannot read the safety '
  'clock; the owner surface answers through get_owner_safety_status.';

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- begin_challenge_window(p_estate) → text                                      [admin, AAL2+fresh]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- Opens the safety window on a death_verified estate: notifies the owner (same transaction,
-- REQUIRED — see the header) and moves the lifecycle. The same platform authority that decides a
-- verification case (admin_require_gate) opens the window; unlike release, this action is
-- safety-INCREASING — it starts the owner's clock and discloses nothing.
create or replace function public.begin_challenge_window(p_estate uuid)
 returns text
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid    uuid;
  v_state  text;
  v_owner  uuid;
  v_case   uuid;
  v_notice uuid;
begin
  perform public.admin_require_gate();
  v_uid := auth.uid();

  select l.state into v_state
    from public.estate_lifecycle l
   where l.estate_id = p_estate
   for update;

  if v_state = 'challenge_window' then
    return 'challenge_window'; -- idempotent replay: no re-notify, no re-audit
  end if;
  if v_state is distinct from 'death_verified' then
    raise exception 'invalid_window_state' using errcode = 'P0001';
  end if;

  -- The verified case is the workflow evidence the window rests on (belt beside the state machine).
  select c.id into v_case
    from public.death_verification_cases c
   where c.estate_id = p_estate and c.status = 'verified'
   order by c.decided_at desc
   limit 1;
  if v_case is null then
    raise exception 'no_verified_case' using errcode = 'P0001';
  end if;

  v_owner := public.estate_owner_user_id(p_estate);
  if v_owner is null then
    raise exception 'owner_unresolved' using errcode = 'P0001';
  end if;

  -- ★ THE INVERTED TRADE: the safety notice must COMMIT or the window must not open. A null here
  -- means the emitter refused or failed; raising rolls back everything this routine did.
  v_notice := public.emit_lifecycle_notification(
    v_owner, p_estate, 'death_process.window_opened', 'afterworth://challenge');
  if v_notice is null then
    raise exception 'owner_notification_failed' using errcode = 'P0001';
  end if;

  perform public.apply_estate_lifecycle_transition(
    p_estate, 'challenge_window', v_case, 'window_opened');

  update public.estate_lifecycle
     set owner_notified_at = now(),
         challenge_window_started_at = now(),
         safety_notification_id = v_notice
   where estate_id = p_estate;

  insert into public.audit_logs (actor_id, estate_id, action, target_table, target_id, metadata, source)
  values (v_uid, p_estate, 'death_process.window_opened', 'estate_lifecycle', v_case,
          jsonb_build_object('severity', 'high', 'case_id', v_case,
                            'safety_notification_id', v_notice),
          'admin');
  return 'challenge_window';
end $function$;
revoke execute on function public.begin_challenge_window(uuid) from public, anon;
grant  execute on function public.begin_challenge_window(uuid) to authenticated;

comment on function public.begin_challenge_window(uuid) is
  'Opens the owner-challenge window on a death_verified estate (Phase 11-E). Admin-gated '
  '(AAL2 + freshness). The owner safety notice is REQUIRED to commit in the same transaction — '
  'a window cannot begin un-notified. Idempotent. Discloses nothing; starts the safety clock.';

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- challenge_death_process(p_estate) → text                          [the authenticated OWNER only]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ R13 IS THE SIGNATURE: one argument, one action. No evidence parameter exists, no review step
-- exists, no waiting period exists, no designation is consulted. The authenticated owner of the
-- estate halts the process — from pending, from death_verified, or from inside the window — and
-- challenge_halted is terminal in 11-E: the map has no edge out, and no routine reopens it.
--
-- ★ THE GATE RUNS BEFORE ANY EXISTENCE OR STATE LOOKUP. `is_estate_owner` answers false for a
-- nonexistent estate and a foreign one alike, so every unauthorized caller — beneficiary,
-- designee, claimant, foreign owner, probe against a random uuid — refuses with the same bytes.
create or replace function public.challenge_death_process(p_estate uuid)
 returns text
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid   uuid := auth.uid();
  v_state text;
begin
  if v_uid is null then
    raise exception 'auth_required' using errcode = '42501';
  end if;
  if not public.is_estate_owner(p_estate) then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  select l.state into v_state
    from public.estate_lifecycle l
   where l.estate_id = p_estate
   for update;
  if v_state is null then
    v_state := 'active';
  end if;

  if v_state = 'challenge_halted' then
    return 'challenge_halted'; -- idempotent replay: no re-stamp, no re-audit
  end if;
  if v_state = 'active' then
    raise exception 'nothing_to_challenge' using errcode = 'P0001';
  end if;
  -- Too late is stated honestly (R15): what was disclosed cannot be undisclosed, and pretending
  -- a halt succeeded would claim otherwise. The owner is authorized to know this about their
  -- own estate.
  if v_state = 'released' then
    raise exception 'already_released' using errcode = 'P0001';
  end if;

  perform public.apply_estate_lifecycle_transition(
    p_estate, 'challenge_halted', null, 'owner_challenge');

  update public.estate_lifecycle
     set halted_at = now()
   where estate_id = p_estate;

  -- Any open case is halted — distinct from 'cancelled' (initiator withdrew): the owner said no.
  update public.death_verification_cases
     set status = 'halted', updated_at = now()
   where estate_id = p_estate and status = 'open';

  -- ★ NO PROVENANCE. The fact recorded is THAT the owner challenged and from which state — never
  -- a channel, a device, an address, or a location (§17: provenance is security-sensitive
  -- information about a living owner).
  perform public.write_audit(
    'death_process.challenged', 'estate_lifecycle', null, p_estate,
    jsonb_build_object('severity', 'high', 'from_state', v_state));
  return 'challenge_halted';
end $function$;
revoke execute on function public.challenge_death_process(uuid) from public, anon;
grant  execute on function public.challenge_death_process(uuid) to authenticated;

comment on function public.challenge_death_process(uuid) is
  'The owner challenge (Phase 11-E, R12-R14): the authenticated estate owner halts a pre-released '
  'death process in one action — no evidence, no review, no waiting, no designation. Wins ties '
  '(release requires the window strictly elapsed; both serialize on the lifecycle row lock). '
  'Produces challenge_halted, terminal in 11-E. Records no provenance beyond the act itself.';

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- release_estate(p_estate) → text            [INTERNAL — no client role, no reachable door in 11-E]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ THE ACTOR IS DELIBERATELY UNWIRED. Who may pull this lever — a single admin, a two-person
-- rule, an automated elapse job — is a product decision (11-A threat model T5) that 11-E does not
-- own. The routine exists so the guards are real and testable; EXECUTE is revoked from every
-- client role and no routine calls it. Wiring an actor is the named 11-F decision, and the drift
-- verifier reports this function's privilege posture so a quiet future GRANT is loud.
create or replace function public.release_estate(p_estate uuid)
 returns text
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_row      public.estate_lifecycle%rowtype;
  v_case     uuid;
  v_duration interval;
begin
  select l.* into v_row
    from public.estate_lifecycle l
   where l.estate_id = p_estate
   for update;

  if v_row.state = 'released' then
    return 'released'; -- idempotent replay: no re-stamp, no re-audit
  end if;
  if v_row.state is distinct from 'challenge_window' then
    -- challenge_halted lands here too: release can NEVER proceed from a halted process.
    raise exception 'invalid_release_state' using errcode = 'P0001';
  end if;

  -- The window rests on a committed safety notice and a verified case — facts, re-checked.
  if v_row.owner_notified_at is null or v_row.safety_notification_id is null then
    raise exception 'owner_not_notified' using errcode = 'P0001';
  end if;
  select c.id into v_case
    from public.death_verification_cases c
   where c.estate_id = p_estate and c.status = 'verified'
   order by c.decided_at desc
   limit 1;
  if v_case is null then
    raise exception 'no_verified_case' using errcode = 'P0001';
  end if;

  -- The duration is read LIVE (H2 precedent). Unconfigured = the window never elapses.
  v_duration := public.challenge_window_duration();
  if v_duration is null then
    raise exception 'release_window_not_configured' using errcode = 'P0001';
  end if;

  -- ★ STRICTLY ELAPSED (R14). At the exact boundary instant (`now() = notified + duration`) this
  -- refuses — and the owner challenge, serialized on the same row lock, still succeeds. The
  -- coalesce is the three-valued-logic discipline: a NULL comparison must refuse, not pass.
  if not coalesce(now() > v_row.owner_notified_at + v_duration, false) then
    raise exception 'release_window_not_elapsed' using errcode = 'P0001';
  end if;

  perform public.apply_estate_lifecycle_transition(
    p_estate, 'released', v_case, 'window_elapsed');

  update public.estate_lifecycle
     set released_at = now()
   where estate_id = p_estate;

  perform public.write_audit(
    'death_process.released', 'estate_lifecycle', v_case, p_estate,
    jsonb_build_object('severity', 'high', 'case_id', v_case,
                       'owner_notified_at', v_row.owner_notified_at,
                       'window_started_at', v_row.challenge_window_started_at,
                       'window_duration', v_duration::text));
  return 'released';
end $function$;
revoke execute on function public.release_estate(uuid) from public, anon, authenticated;

comment on function public.release_estate(uuid) is
  'THE release transition (Phase 11-E): challenge_window -> released, only when the owner was '
  'notified (committed safety notice), a verified case exists, the configured window has STRICTLY '
  'elapsed (ties refuse - the owner challenge wins them, R14), and no challenge halted the process '
  '(the map has no edge from challenge_halted). Idempotent, audited. INTERNAL: EXECUTE revoked '
  'from every client role and called by nothing - the release ACTOR is an explicitly deferred '
  'product decision (11-F), so in 11-E released is unreachable in any deployed environment.';

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- get_owner_safety_status(p_estate) → text                          [authenticated, owner-gated]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- The owner-facing presentation of their own estate's safety state — a CLOSED four-value union,
-- deliberately coarser than the lifecycle: the owner surface needs "is there something to halt",
-- never the machine's internals. An owner is authorized to know this about their own estate; no
-- one else may ask (same byte-identical refusal discipline as the challenge).
--
--   none          nothing to challenge (no death process, or it concluded without release)
--   challengeable a death process is underway and the owner may halt it
--   halted        the owner (or a prior challenge) halted the process
--   released      the process completed; the owner arrived too late to halt (stated honestly)
create or replace function public.get_owner_safety_status(p_estate uuid)
 returns text
 language plpgsql
 security definer
 stable
 set search_path to 'public'
as $function$
declare
  v_uid   uuid := auth.uid();
  v_state text;
begin
  if v_uid is null then
    raise exception 'auth_required' using errcode = '42501';
  end if;
  if not public.is_estate_owner(p_estate) then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  v_state := public.estate_lifecycle_state(p_estate);
  return case v_state
    when 'death_verification_pending' then 'challengeable'
    when 'death_verified'             then 'challengeable'
    when 'challenge_window'           then 'challengeable'
    when 'challenge_halted'           then 'halted'
    when 'released'                   then 'released'
    else 'none'
  end;
end $function$;
revoke execute on function public.get_owner_safety_status(uuid) from public, anon;
grant  execute on function public.get_owner_safety_status(uuid) to authenticated;

comment on function public.get_owner_safety_status(uuid) is
  'Owner-scoped safety status (Phase 11-E): a closed presentation union (none / challengeable / '
  'halted / released) over the authoritative lifecycle, for the challenge surface. Owner-only; '
  'every other caller refuses byte-identically. Not an authorization and not a disclosure: it '
  'answers about the process, never about estate content.';
