-- GENERATED by scripts/scripts/buildFiduciaryDiscoveryBundle.mjs — DO NOT EDIT.
-- Edit the sources instead:
--   db/functions/fiduciary_estate_discovery.sql
--
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- PASTE THIS WHOLE FILE INTO THE SUPABASE WEB SQL EDITOR AND RUN IT ONCE.
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- PURE SQL: this artifact contains no psql meta-commands. (\set and friends are client directives
-- the web editor cannot honour; they are stripped at build time and remain only in the sources,
-- which are applied through psql by the SQL suite.)
--
-- TRANSACTIONAL: the entire artifact runs inside ONE explicit transaction. Every statement here is
-- transaction-safe — the builder refuses to emit a wrapper otherwise — so:
--
--   · if ANY statement fails, the transaction aborts and COMMIT is never reached;
--   · the database is left EXACTLY as it was: there is no half-applied state to diagnose;
--   · the migrations' own self-checks raise on a bad state, which aborts before COMMIT too, so a
--     bundle that detects a problem rolls itself back rather than shipping it.
--
-- IDEMPOTENT: every table is IF NOT EXISTS, every function is CREATE OR REPLACE, every constraint
-- is dropped-then-added, and every seed uses ON CONFLICT. Re-running is safe and is the intended
-- recovery action after a failure.
begin;

-- ==== db/functions/fiduciary_estate_discovery.sql =================================================
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- public.get_my_fiduciary_estates() -> TABLE(estate_id, estate_display_name, capacity)
-- Phase 11-MB · DISCOVERY ONLY. Grants nothing.                              [authenticated, self]
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- ★ WHY THIS EXISTS: A DESIGNATION WAS UNDISCOVERABLE, SO PROVISIONING FAKED A MEMBERSHIP.
--
-- `resolve_membership` builds `additionalContexts` from `estate_memberships` ALONE — it never queries
-- `estate_designations`. The mobile estate selector consumes that payload, so an estate reachable
-- only through a fiduciary designation could never be listed, never be activated, and therefore
-- never reach `/executor`.
--
-- Executor/trustee provisioning bridged that gap by FORCING the invitation's proposed_role to
-- `beneficiary` (`create_invitation`, one hardcoded line), which manufactures an approved beneficiary
-- membership as a side effect of granting fiduciary capacity. That is an authority-model defect:
-- workflow capacity silently minting a disclosure class. This routine removes the reason for it.
--
-- ★ IT IS THE ENUMERATION, NOT THE AUTHORITY. `get_executor_workspace` already answers "may I act on
-- THIS estate" from the designation alone and consults no membership. What did not exist was "WHICH
-- estates" — so this adds exactly that and nothing else. Authorization stays where it already is.
--
-- ★ DISCOVERY IS NOT DISCLOSURE, and the distinction is the whole point. Appearing in this list makes
-- an estate SELECTABLE. It confers no tier, no grant, no membership, no document, no asset, no
-- valuation, no beneficiary data and no lifecycle fact. Every disclosure projection must answer
-- BYTE-IDENTICALLY before and after a designation is granted; only this routine and the executor
-- workspace may move. Both halves are asserted in `db/tests/death_verification_authorization.sql`.
--
-- ★ THE ONE NEW DISCLOSURE, NAMED RATHER THAN SLIPPED IN: `estate_display_name`.
--
-- No existing routine gives a designation-only participant the estate's name. `get_executor_workspace`
-- returns capacity, process and verification state and NO display metadata at all;
-- `resolve_membership` returns `e.name` only for people who hold a membership; the invitation preview
-- gates it behind `preview_visibility->>'showEstateName'`. So this column is a genuinely new fact
-- disclosed to a genuinely new class, and it is here for one reason: a selector row that cannot name
-- the estate cannot be chosen between. An executor administering an estate needs to know which estate
-- it is, and a beneficiary already learns the same string.
--
-- It is owner-authored free text (the 11-K disclosure census records that), so it is the ONLY content
-- field here and it is trivially removable — drop the column and the selector falls back to
-- identifying estates by nothing, which is why it was not dropped. If product decides a fiduciary must
-- not see the name, that is a one-line change and this comment is the record of the choice.
--
-- ★ NO CALLER PARAMETER, DELIBERATELY. `auth.uid()` is the only subject. A `p_user` argument would let
-- any authenticated caller enumerate another person's fiduciary relationships — a map of who is
-- executor of what, which is exactly the kind of question this product refuses elsewhere. Anon gets
-- two independent refusals: EXECUTE is revoked, and `auth.uid()` is NULL so the predicate matches
-- nothing even if a grant were ever widened by mistake.
--
-- ★ ONE ROW PER ESTATE, WITH A DETERMINISTIC CAPACITY. A person may hold BOTH an executor and a
-- trustee designation on one estate (the partial unique index is per designation_type), so a naive
-- select would list the estate twice and the selector would show a duplicate. The aggregate collapses
-- it, and `min(designation_type)` reproduces EXACTLY the tiebreak `initiate_death_verification_case`
-- uses (`order by d.designation_type limit 1`, so 'executor' precedes 'trustee'). Matching it matters:
-- if the UI named one capacity and the routine recorded the other, the case history and the screen
-- that started it would disagree about who acted.
--
-- STABLE + SECURITY DEFINER because `estate_designations` is grant-less (born clean) and is read here
-- as the owner. Reads two tables, writes nothing, emits nothing.
create or replace function public.get_my_fiduciary_estates()
 returns table(estate_id uuid, estate_display_name text, capacity text)
 language sql
 security definer
 stable
 set search_path to 'public'
as $function$
  select d.estate_id,
         e.name,
         min(d.designation_type)
    from public.estate_designations d
    join public.estates e on e.id = d.estate_id
   where d.user_id = auth.uid()
     and d.status = 'active'
     and d.designation_type in ('executor', 'trustee')
   group by d.estate_id, e.name;
$function$;
revoke execute on function public.get_my_fiduciary_estates() from public, anon;
grant  execute on function public.get_my_fiduciary_estates() to authenticated;

comment on function public.get_my_fiduciary_estates() is
  'Phase 11-MB. Enumerates estates on which the CALLER holds an active executor/trustee designation, '
  'for estate-context selection ONLY. Returns estate id, display name and one deterministic capacity; '
  'no tier, grant, membership, asset, valuation, document, beneficiary or lifecycle fact. Discovery is '
  'not disclosure: appearing here makes an estate selectable and readable by nothing. Scoped to '
  'auth.uid() with no caller parameter, so no one can enumerate another person''s fiduciary '
  'relationships.';

commit;
-- ★ If you see an error above and no COMMIT, nothing was applied. Fix the cause and paste again.
