-- GENERATED by scripts/scripts/buildOwnerNoticeClaimVisibilityBundle.mjs — DO NOT EDIT.
-- Edit the sources instead:
--   db/migrations/0057_20260816_owner_notice_claim_visibility.sql
--   db/functions/outbox_safety.sql
--
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- PASTE THIS WHOLE FILE INTO THE SUPABASE WEB SQL EDITOR AND RUN IT ONCE.
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- PURE SQL: this artifact contains no psql meta-commands. (\set and friends are client directives
-- the web editor cannot honour; they are stripped at build time and remain only in the sources,
-- which are applied through psql by the SQL suite.)
--
-- TRANSACTIONAL: the entire artifact runs inside ONE explicit transaction. Every statement here is
-- transaction-safe — the builder refuses to emit a wrapper otherwise — so:
--
--   · if ANY statement fails, the transaction aborts and COMMIT is never reached;
--   · the database is left EXACTLY as it was: there is no half-applied state to diagnose;
--   · the migrations' own self-checks raise on a bad state, which aborts before COMMIT too, so a
--     bundle that detects a problem rolls itself back rather than shipping it.
--
-- IDEMPOTENT: every table is IF NOT EXISTS, every function is CREATE OR REPLACE, every constraint
-- is dropped-then-added, and every seed uses ON CONFLICT. Re-running is safe and is the intended
-- recovery action after a failure.
begin;

-- ==== db/migrations/0057_20260816_owner_notice_claim_visibility.sql ===============================
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- PHASE 11-OBR · OB-1 — A CLAIMED OWNER NOTICE MUST BE RECOVERABLE
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- ★ THE DEFECT, MEASURED IN PRODUCTION, NOT INFERRED. On 2026-08-16 the Branch A owner-safety
-- notice `7ec99457-38af-4e2c-b2eb-eca771fe7d5e` was observed at `status = 'processing'`,
-- `attempts = 1`, `dispatched_at = null`, `failure_class = null`, `provider_result = null`. The
-- 04:00Z drain had claimed it and never settled it.
--
-- `claim_owner_notices` selects `where o.status = 'queued'` only. A row in `processing` is therefore
-- never handed out again by any future drain. Its ONLY remaining transition is the stale sweep, which
-- marks it `failedPermanent` once it passes the age gate — and the age gate is `challenge_window + 1
-- day`, so a lost notice is not even marked failed until a DAY AFTER the release window it was meant
-- to protect has already elapsed.
--
-- The owner is never warned, and nothing anywhere says so.
--
-- ★ WHY THE FIX IS A COLUMN AND NOT A PREDICATE. The reclaim condition everyone reaches for is
-- "processing for too long". That sentence cannot be written against this table: there is no record
-- of WHEN a row was claimed. `requested_at` is when the notice was created (it does not move on
-- claim), and `attempts` is a counter with no clock. **You cannot time out a claim you never
-- timestamped.** That absence — not the `= 'queued'` predicate — is the root enabler, and it is what
-- this migration closes.
--
-- ★ WHAT THIS MIGRATION DELIBERATELY DOES NOT DO.
--
--   · It does NOT touch the release precondition. `authorize_release` accepts any owner-notice row
--     whose status is `<> 'cancelled'` — so `processing` and even `failedPermanent` satisfy the
--     "owner is independently reachable" guard today. That is OB-2, it is a product/safety decision
--     about when a release may proceed, and folding it into a recovery fix would be deciding it
--     silently. `db/tests/release_safety_authorization.sql` asserts the precondition is UNCHANGED by
--     this artifact, so OB-1 cannot drift into OB-2 unnoticed.
--
--   · It does NOT backfill `claimed_at` for existing rows, and it does NOT special-case the one
--     stranded row. A backfill would be a guess about when a claim happened, written into the column
--     whose whole purpose is to stop guessing. Legacy `processing` rows land with `claimed_at IS
--     NULL` and are handled by the reclaim contract as a class (see `claim_owner_notices`), never by
--     name.
--
-- Deploys via `db/bundles/owner_notice_claim_visibility_bundle.sql`. Source of truth — re-apply on
-- DB reset.

-- [psql meta-command removed for the SQL editor] \set ON_ERROR_STOP on

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 1 · THE CLAIM TIMESTAMP
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- Nullable, and permanently so. NULL means "claimed before this column existed" for the legacy rows
-- that exist at deployment, and "not currently claimed" for every row that has never been claimed.
-- Both are read through the same predicate; neither is inferred from `attempts`.
alter table public.owner_notice_outbox
  add column if not exists claimed_at timestamptz;

comment on column public.owner_notice_outbox.claimed_at is
  'When claim_owner_notices last moved this row into `processing` (Phase 11-OBR / OB-1). NULL means '
  'never claimed, or claimed before this column existed. It is the ONLY basis for deciding that a '
  'claim has gone stale — attempts is a counter with no clock, and requested_at does not move on '
  'claim. Never backfilled: a guessed claim time defeats the column.';

-- ★ THE PARTIAL INDEX MATCHES THE RECLAIM PREDICATE, INCLUDING ITS NULL BRANCH. The drain asks for
-- rows that are `processing` and stale; ordering is by `requested_at`, oldest first, exactly as the
-- queued branch orders. Partial so it stays small: `processing` is a transient state and in a
-- healthy system this index is nearly empty — which is itself the point.
create index if not exists owner_notice_outbox_processing_claimed_idx
  on public.owner_notice_outbox (requested_at)
  where status = 'processing';

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 2 · OB-4 — THE AUDIT SOURCE THE WORKER HAS ALWAYS WRITTEN AND HAS NEVER BEEN ALLOWED TO
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ THIS IS THE ROOT CAUSE OF OB-1, AND IT IS NOT A STRANDED-CLAIM PROBLEM AT ALL.
--
-- `record_owner_notice_outcome` closes by writing an audit row with `source = 'worker'` — a
-- deliberate 11-K choice, documented there: the actor is a scheduled worker, not a person, so
-- `actor_id` is NULL and the source says so rather than inventing a synthetic operator identity.
--
-- `audit_logs_source_check` has admitted `('server', 'ios_forward', 'admin')` since migration 0014
-- and was NEVER widened. So the final statement of `record_owner_notice_outcome` raises
-- `check_violation` on EVERY call. The routine cannot settle any notice, ever. `recordOutcome` in
-- `lib/ownerNotices/drain.ts` catches the RPC error, logs the code, and returns — so the row is left
-- exactly where the claim put it: `processing`, `attempts = 1`, `dispatched_at = null`.
--
-- That is the Branch A row, precisely. The claim was never the problem; the SETTLE was, and it has
-- been totally broken since 11-K wired the cron. The email itself is sent BEFORE the settle, so the
-- owner may well have received it — the system simply cannot record that it did.
--
-- ★ WHY THIS MUST SHIP WITH OB-1 RATHER THAN AFTER IT. A visibility timeout alone makes an
-- unsettleable row reclaimable, and a reclaimed row is sent again and still cannot be settled. The
-- result is a daily resend loop that runs until the age gate — turning one silent lost notice into
-- eight days of repeated mail to a living owner about their own death process. Fixing the reclaim
-- without fixing the settle is strictly worse than fixing neither.
--
-- ★ THE VALUE IS SERVER-STAMPED, NEVER A CLIENT PARAMETER — the same property that justified
-- admitting 'admin' in 0014. No client can reach this routine: EXECUTE is service_role only.
alter table public.audit_logs drop constraint if exists audit_logs_source_check;
alter table public.audit_logs add constraint audit_logs_source_check
  check (source in ('server', 'ios_forward', 'admin', 'worker'));

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 3 · PROVE THE SEAM TOOK, IN THE MIGRATION ITSELF (the 0051/0052/0054 discipline)
-- ────────────────────────────────────────────────────────────────────────────────────────────────
do $$
declare
  v_type text;
  v_nullable text;
  -- Phase D supersession bookkeeping — see the banner beside the release-precondition guard below.
  v_def  text;
  v_old  boolean;
  v_new  boolean;
begin
  select data_type, is_nullable into v_type, v_nullable
    from information_schema.columns
   where table_schema = 'public'
     and table_name = 'owner_notice_outbox'
     and column_name = 'claimed_at';

  if v_type is null then
    raise exception '0057 FAILED: owner_notice_outbox.claimed_at was not added';
  end if;
  if v_type <> 'timestamp with time zone' then
    raise exception '0057 FAILED: claimed_at is %, expected timestamptz', v_type;
  end if;
  -- ★ NULLABLE IS LOAD-BEARING, NOT AN OVERSIGHT. A NOT NULL column would have required a backfill
  -- default, and every value it invented would be a fabricated claim time on a row whose real claim
  -- time is unknowable. The reclaim contract reads NULL as a first-class case.
  if v_nullable <> 'YES' then
    raise exception '0057 FAILED: claimed_at must remain nullable (it is %), or legacy rows carry a '
      'fabricated claim time', v_nullable;
  end if;

  if not exists (
    select 1 from pg_indexes
     where schemaname = 'public'
       and tablename = 'owner_notice_outbox'
       and indexname = 'owner_notice_outbox_processing_claimed_idx'
  ) then
    raise exception '0057 FAILED: the processing/claimed index is absent';
  end if;

  -- ════════════════════════════════════════════════════════════════════════════════════════════
  -- ★ SUPERSEDED BY MIGRATION 0060 (PHASE 11-OC / PHASE D) — AMENDED 2026-08-17, ASSERTION LAYER
  --   ONLY. NO DEPLOYED SCHEMA BEHAVIOUR OF THIS MIGRATION CHANGED.
  -- ════════════════════════════════════════════════════════════════════════════════════════════
  --
  -- ORIGINAL INVARIANT (correct when written): OB-1 adds `claimed_at` and a reclaim predicate, and
  -- must not have implemented OB-2 as a side effect. Asserted by requiring `authorize_release` to
  -- still carry the pre-OB-2 predicate text `o.status <> 'cancelled'`.
  --
  -- SUPERSEDING INVARIANT (OB-2, migration 0060): the release door consults
  -- `owner_notice_release_authority` and no status string whatsoever, so the pinned literal is gone
  -- by design and exact-text pinning would fail every replay from 0060 onward.
  --
  -- WHY EXACT-TEXT PINNING IS NO LONGER VALID, AND WHY THE GUARD SURVIVES ANYWAY. `prosrc` includes
  -- comments, so re-satisfying the old check by planting the literal in one would convert a live
  -- guard into a decoration that inspects nothing. Deleting it would let a future edit remove the
  -- owner-notice precondition entirely with nothing objecting. So the check becomes a
  -- supersession-aware disjunction: the door must carry the OB-1 predicate **or** the OB-2 authority
  -- — never neither, and never both. That is strictly stronger than what this migration originally
  -- asserted, because the original could not fail on the absence of both.
  --
  -- The OB-2 branch is anchored on `to_regprocedure`, a CATALOG fact about a function that must
  -- genuinely exist, precisely so a comment cannot supply it. Runtime semantics are proven where
  -- they can be observed — 0060 §4 by execution, and the SQL suite §12 against the real door.
  select prosrc into v_def from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'authorize_release';
  if v_def is null then
    raise exception '0057 FAILED: authorize_release does not exist, so the OB-2 precondition this '
      'migration is required to leave alone cannot be inspected at all';
  end if;
  -- ★ COMMENTS STRIPPED BEFORE MATCHING. Postgres stores a plpgsql body verbatim, so prose could
  -- otherwise satisfy either branch — which is precisely the "plant the literal in a comment" R13
  -- fix this programme refused. Stripping makes it unavailable rather than merely forbidden. String
  -- literals are NOT stripped: the predicate being looked for IS a quoted literal.
  v_def := regexp_replace(v_def, E'--[^\n]*', '', 'g');
  if v_def not like '%raise exception%' then
    raise exception '0057 FAILED: the stripped authorize_release body contains no code — the '
      'preprocessing has eaten the routine and this guard is inspecting an empty string';
  end if;
  v_old := v_def like '%o.status <> ''cancelled''%';
  v_new := to_regprocedure('public.owner_notice_release_authority(uuid)') is not null
           and v_def like '%public.owner_notice_release_authority(%';
  if not (v_old or v_new) then
    raise exception '0057 FAILED: authorize_release carries NEITHER the OB-1 owner-notice predicate '
      'nor the OB-2 acceptance authority — the precondition has been removed rather than superseded, '
      'and an estate can release with no provable owner notice of any kind';
  end if;
  if v_old and v_new then
    raise exception '0057 FAILED: authorize_release carries BOTH postures — a half-applied Phase D '
      'cutover, which is neither posture and cannot be reasoned about';
  end if;

  -- ★ OB-4: the settle path must actually be able to write its audit row. Asserted by EXECUTING an
  -- insert rather than by reading the constraint text — a constraint that merely mentions 'worker'
  -- is not proof that the value is storable, and this whole defect existed because nobody ever tried.
  begin
    insert into public.audit_logs (actor_id, estate_id, action, target_table, target_id, metadata, source)
    values (null, null, 'aw.migration_0057_probe', 'audit_logs', null, '{}'::jsonb, 'worker');
    delete from public.audit_logs where action = 'aw.migration_0057_probe';
  exception when check_violation then
    raise exception '0057 FAILED: audit_logs still refuses source = ''worker'' — '
      'record_owner_notice_outcome cannot settle any notice and every claimed owner notice will '
      'strand in processing exactly as the Branch A row did';
  end;

  -- And the widening is EXACTLY one value: a source vocabulary that had quietly grown would be a
  -- different problem wearing this fix as cover.
  select pg_get_constraintdef(oid) into v_type
    from pg_constraint where conname = 'audit_logs_source_check';
  if (select count(*) from regexp_matches(v_type, '''[a-z_]+''', 'g')) <> 4 then
    raise exception '0057 FAILED: the audit source vocabulary is not exactly four values: %', v_type;
  end if;

  raise notice '0057 OK: claimed_at present and nullable, reclaim index present, the release door '
    'carries exactly ONE owner-notice posture (OB-1 status <> cancelled, or the OB-2 acceptance '
    'authority — never neither, never both), audit source admits worker (proved by execution)';
end $$;


-- ==== db/functions/outbox_safety.sql ==============================================================
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- PHASE 11-F · OUTBOX SAFETY — age gate, stale protection, and a purge that cannot be silent
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- ★ WHY A SAFETY NOTICE NEEDS DIFFERENT RULES FROM AN INVITATION EMAIL. `invitation_delivery_outbox`
-- is drained daily and its claim predicate has NO age bound: any `queued` row is claimable whenever
-- the worker next runs. For an invitation that is merely late. For the notice that tells a living
-- owner a process is running to release their estate, sending it three weeks after the fact is
-- worse than not sending it — the situation it describes has already resolved, and the message
-- would arrive as a false alarm about a window that closed, or a true alarm nobody can act on.
--
-- ★ SO STALENESS IS A DECISION, MADE ONCE, RECORDED. A notice older than the age gate is never
-- quietly sent and never quietly deleted: it is marked `failedPermanent` with an explicit failure
-- class, which leaves the evidence in place. Whether the estate should then still be releasable is
-- NOT this module's call — dispatch INITIATION already happened (Stage 2), and re-deciding that
-- here would be a second release authority hiding in a mail queue.
--
-- ★ AND NOTHING IS EVER SILENTLY DELETED (Stage 3). `purge_outbox_rows` writes an
-- `outbox_purge_audit` row BEFORE it deletes, in the same transaction, carrying the count and the
-- age range it removed. A purge with no audit row is impossible rather than discouraged.
--
-- Source of truth — re-apply on DB reset. Deploys with the release-authorization bundle.

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- owner_notice_age_gate() → interval                                                   [INTERNAL]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ DERIVED FROM THE CHALLENGE WINDOW, NOT CONFIGURED SEPARATELY. A notice is worth sending while
-- the window it announces could still matter; the window is 7 days (D2), so the gate is the window
-- plus one day of slack for a queue that fell behind. Two independently-tunable numbers would drift
-- apart, and the failure mode of that drift is a notice sent after its own window closed.
--
-- Fail-closed: an unconfigured window yields NULL, and a NULL gate makes `claim_owner_notices`
-- refuse to claim anything rather than treat everything as fresh.
create or replace function public.owner_notice_age_gate()
 returns interval
 language sql
 security definer
 stable
 set search_path to 'public'
as $function$
  select public.challenge_window_duration() + interval '1 day';
$function$;
revoke execute on function public.owner_notice_age_gate() from public, anon, authenticated;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- owner_notice_claim_visibility() → interval                                          [INTERNAL]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ PHASE 11-OBR / OB-1. How long a claim is believed before the row is handed to another worker.
--
-- Derived from measured ceilings, not chosen for roundness: the provider request timeout is 10s
-- (`REQUEST_TIMEOUT_MS`), retried at most once on an ambiguous answer, so one row can legitimately
-- occupy a worker for ~20s; the drain runs on a serverless function whose execution ceiling is at
-- most 300s. One hour is therefore 12× the highest possible platform ceiling and ~180× the real
-- per-row cost — a row still `processing` an hour later is not slow, it is abandoned.
--
-- The upper bound matters as much: the stale sweep settles rows at `age_gate` (window + 1 day) and
-- the cron runs daily, so one hour leaves every one of those daily drains available as a recovery
-- opportunity instead of spending the gate waiting.
--
-- ★ IT IS A FUNCTION SO THERE IS EXACTLY ONE COPY. `claim_owner_notices` decides what to reclaim and
-- `owner_notice_census` reports how much is reclaimable; two literals would be two opinions about
-- the same bytes, and the first time they drifted the census would quietly stop describing what the
-- drain actually does. Not a policy table: the challenge window is a PRODUCT decision an operator
-- must be able to state, whereas this is an operational property of this worker whose only failure
-- mode is being set below the platform ceiling — which would reclaim rows out from under live
-- workers and manufacture the duplicate sends this module exists to avoid.
create or replace function public.owner_notice_claim_visibility()
 returns interval
 language sql
 immutable
 set search_path to 'public'
as $function$
  select interval '1 hour';
$function$;
revoke execute on function public.owner_notice_claim_visibility() from public, anon, authenticated;

comment on function public.owner_notice_claim_visibility() is
  'How long an owner-notice claim is believed before the row may be reclaimed (Phase 11-OBR). One '
  'hour: 12x the highest serverless execution ceiling and ~180x the real per-row send cost, and far '
  'inside the age gate so every daily drain remains a recovery opportunity. Single-sourced so the '
  'claim routine and the census cannot disagree about what is stale.';

comment on function public.owner_notice_age_gate() is
  'How old an owner safety notice may be and still be worth sending (Phase 11-F): the challenge '
  'window plus one day of queue slack, DERIVED so the two cannot drift apart. NULL when the window '
  'is unconfigured, which makes the claim routine refuse rather than treat everything as fresh.';

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- claim_owner_notices(p_max) → setof                                                   [INTERNAL]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- The claim side of the owner-notice channel, with the age gate applied BEFORE anything is handed
-- to a sender. Two populations leave the queue on every call:
--
--   · STALE  — older than the gate. Marked `failedPermanent`, class `stale_beyond_age_gate`. Never
--              sent, never deleted. The row is the evidence that the owner was not reached in time,
--              which an operator investigating a disputed release will want.
--   · FRESH  — claimed for delivery with `for update skip locked`, so two concurrent drains never
--              hand the same notice out twice.
--
-- ★ PHASE 11-K WIRED THE CRON. 11-F's note read: "NO CRON IS WIRED TO THIS IN 11-F, DELIBERATELY.
-- Enabling a new delivery path is a deployment decision with its own operator step, and the phase
-- brief's own instruction is to build the safety BEFORE enabling the path. The routine exists, is
-- tested, and waits." The safety was built; 11-K enables the path. The drain is
-- `lib/ownerNotices/drain.ts`, reached by `GET /api/claims/drain_outboxes` under CRON_SECRET, and it
-- claims through this routine as `service_role` — the grant is at the foot of this section.
--
-- ★ THE ROUTE NAME IS NOT `drain_owner_notices`, AND THIS COMMENT USED TO SAY IT WAS. There is no
-- such endpoint: it returns 404 in production, verified by probing it. `drain_owner_notices` is only
-- the LOG LABEL for the owner-notice half inside the shared dispatcher. The half shares the claims
-- cron slot because Vercel Hobby permits exactly two cron jobs, so it could never have its own path.
-- A comment naming a 404 is not cosmetic in THIS module: §5/§7 of the deployment doc verify the
-- channel by probing it, and an engineer who probes the name written here gets a 404 and concludes
-- the drain was never deployed — a false negative about the only independent channel that warns a
-- living owner their estate is being released.
create or replace function public.claim_owner_notices(p_max int default 25)
 returns table (id uuid, estate_id uuid, recipient text, notice_kind text)
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_gate interval;
  v_max  int;
  -- ★ PHASE 11-OBR / OB-1 — the claim visibility timeout, read from the ONE place that defines it
  -- (`owner_notice_claim_visibility()`), so this routine and `owner_notice_census` can never
  -- disagree about which rows are stale.
  v_visibility interval := public.owner_notice_claim_visibility();
begin
  v_gate := public.owner_notice_age_gate();
  if v_gate is null then
    -- Fail-closed: with no configured window there is no defensible notion of "too old", so the
    -- queue is not drained at all rather than drained by a guess.
    raise exception 'owner_notice_age_gate_unconfigured' using errcode = 'P0001';
  end if;
  v_max := least(greatest(coalesce(p_max, 25), 1), 100);

  -- STALE FIRST, so a stale row can never be claimed for sending by the same call.
  update public.owner_notice_outbox o
     set status = 'failedPermanent',
         failure_class = 'stale_beyond_age_gate',
         next_attempt_at = null
   where o.status in ('queued', 'processing')
     and o.requested_at < now() - v_gate;

  -- ────────────────────────────────────────────────────────────────────────────────────────────
  -- ★ THE CLAIM SET IS CLOSED AND WRITTEN OUT AS TWO NAMED BRANCHES (OB-1).
  -- ────────────────────────────────────────────────────────────────────────────────────────────
  --
  --   A · queued           — claimable immediately, subject to its backoff. Unchanged.
  --   B · processing, stale — claimed by a worker that never settled it. Reclaimable ONLY once the
  --                           claim is older than the visibility timeout.
  --
  -- Every other status is excluded, and excluded BY NAME rather than by falling through a
  -- `status <> terminal` predicate. `dispatched`, `outcomeUncertain`, `failedPermanent` and
  -- `cancelled` are all settled: two of them are terminal precisely because the message may already
  -- be in the owner's inbox, and a broad "not terminal" test is exactly how a future status added to
  -- the CHECK constraint would silently become re-sendable.
  --
  -- ★ `claimed_at IS NULL` ON A `processing` ROW IS RECLAIMABLE, AND THAT IS A DECISION.
  -- Such a row was claimed before `claimed_at` existed (migration 0057), which means it has been
  -- sitting in `processing` since at least the deployment — already far beyond any timeout. Treating
  -- NULL as "infinitely stale" is what lets the DEPLOYED mechanism recover the rows the defect
  -- already stranded, rather than requiring a hand-written repair for each one. It is a class rule;
  -- no row is named.
  --
  -- ★ WHAT A RECLAIM COSTS, STATED HONESTLY. A reclaimed row is re-sent under the SAME deterministic
  -- `Idempotency-Key` (`afterworth/owner-notice/<row id>`, built in `lib/ownerNotices/drain.ts` from
  -- the row id with no generation counter), so the provider is asked to no-op a repeat. That is the
  -- same operation the worker ALREADY performs when it retries an ambiguous first attempt — this
  -- does not re-mint a message, it replays one. It is nevertheless AT-LEAST-ONCE, not exactly-once:
  -- the provider's dedupe retention is a vendor property this repository does not pin, and a reclaim
  -- that lands outside it could produce a second copy. See docs/phase11ob-owner-notice-delivery-defect.md.
  return query
  with candidate as (
    select o.id
      from public.owner_notice_outbox o
     where o.requested_at >= now() - v_gate
       and (
         -- A · the ordinary queue
         (o.status = 'queued'
          and (o.next_attempt_at is null or o.next_attempt_at <= now()))
         -- B · an abandoned claim
         or (o.status = 'processing'
             and (o.claimed_at is null or o.claimed_at < now() - v_visibility))
       )
     order by o.requested_at
     limit v_max
     for update skip locked
  )
  update public.owner_notice_outbox o
     set status     = 'processing',
         attempts   = o.attempts + 1,
         -- Stamped on EVERY claim, first or repeat: the timeout must run from THIS claim, or a
         -- reclaimed row would be instantly reclaimable again by the next concurrent drain.
         claimed_at = now()
    from candidate c
   where o.id = c.id
  returning o.id, o.estate_id, o.recipient, o.notice_kind;
end $function$;
-- ★ THE WORKER GRANT (11-K), AND WHY IT IS NOT `authenticated`. Claiming is a WORKER act, not an
-- operator act: it moves a live safety message into `processing` and hands it to a sender. An
-- operator who could claim could also strand a notice in `processing`, where the stale sweep will
-- eventually mark it failedPermanent — an owner silently un-notified by a console click. The 0043
-- precedent exactly: the claim/record pair is service_role only, revoked from every client role.
revoke execute on function public.claim_owner_notices(int) from public, anon, authenticated;
grant  execute on function public.claim_owner_notices(int) to service_role;

comment on function public.claim_owner_notices(int) is
  'Claims owner safety notices for delivery, applying the age gate FIRST (Phase 11-F, Stage 3): '
  'rows older than the gate are marked failedPermanent/stale_beyond_age_gate and are never sent and '
  'never deleted. Fresh rows are claimed with skip-locked so concurrent drains cannot double-send. '
  'Refuses entirely when the age gate is unconfigured. service_role ONLY (Phase 11-K wired the '
  'drain); no client role may claim.';

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- record_owner_notice_outcome(p_id, p_outcome, p_failure_class) → text            [service_role]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ THE HALF 11-F LEFT OUT, AND THE REASON A DRAIN COULD NOT BE WRITTEN UNTIL NOW.
-- `claim_owner_notices` moves a row to `processing` and returns it. Nothing wrote back what the
-- sender then learned — so any worker built on the 11-F schema would have claimed rows and stranded
-- every one of them in `processing`, where the stale sweep would later mark them failedPermanent.
-- The queue would have looked drained and no owner would have been reached.
--
-- Modelled on `record_invitation_delivery_outcome` (0043) with three deliberate differences, each
-- forced by what THIS channel is for:
--
--   · NO GENERATION GUARD, because there is no generation column and no reissue concept. A safety
--     notice is dispatched once, by one transition, and is never re-minted. What replaces the guard
--     is the settled-status check below: a row that has already settled is a no-op.
--
--   · NO PROVIDER MESSAGE ID IS STORED. The table has no column for one and gains none. A provider
--     handle is a lookup key into a third party's log of a message addressed to a living owner; the
--     operational fact this product needs is the outcome, and that is what is recorded.
--
--   · A LOWER CAP AND A SHORTER BACKOFF. Invitations retry 5 times with up to 12h between attempts,
--     which is right for a message that is merely late. This notice is only worth sending inside
--     the age gate (window + 1 day), so a 12h backoff would spend the whole gate on two attempts.
--     Three attempts at ~1h/2h/3h all land comfortably inside it.
--
-- ★ ACCEPTED AND UNCERTAIN ARE BOTH TERMINAL, for the same reason: the message may already be in
-- the owner's inbox, and this product will not send a second copy of a notice about their own death
-- on the strength of a lost HTTP response. Only `retryPending` — where the provider ANSWERED and
-- refused, proving nothing was accepted — returns a row to `queued`.
create or replace function public.record_owner_notice_outcome(
  p_id            uuid,
  p_outcome       text,
  p_failure_class text default null
)
 returns text
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_row    public.owner_notice_outbox%rowtype;
  v_status text;
  v_next   timestamptz;
  v_class  text;
  c_max_attempts constant int := 3;
begin
  if p_outcome not in ('providerAccepted', 'outcomeUncertain', 'retryPending', 'failedPermanent') then
    raise exception 'invalid_outcome' using errcode = 'P0001';
  end if;

  select * into v_row from public.owner_notice_outbox where id = p_id for update;
  if not found then
    raise exception 'outbox_entry_not_found' using errcode = 'P0002';
  end if;

  -- Already settled: report current state, change nothing, write no second audit row. Covers a
  -- duplicate callback and an operator-cancelled row alike.
  if v_row.status in ('dispatched', 'outcomeUncertain', 'failedPermanent', 'cancelled') then
    return v_row.status;
  end if;

  v_class := case when p_outcome in ('retryPending', 'failedPermanent') then p_failure_class else null end;
  v_next  := null;

  if p_outcome = 'providerAccepted' then
    v_status := 'dispatched';
  elsif p_outcome = 'outcomeUncertain' then
    v_status := 'outcomeUncertain';
  elsif p_outcome = 'failedPermanent' then
    v_status := 'failedPermanent';
  else
    if v_row.attempts >= c_max_attempts then
      v_status := 'failedPermanent';
      v_class  := coalesce(v_class, 'retry_cap_exhausted');
    else
      v_status := 'queued';
      v_next   := now() + make_interval(hours => least(greatest(v_row.attempts, 1), 3));
    end if;
  end if;

  -- ★ PHASE 11-OC — ACCEPTANCE IS STAMPED IN THIS ONE STATEMENT, BESIDE THE STATUS IT AGREES WITH.
  --
  -- `notice_accepted_at` is the fact Phase D makes release-authoritative, and it is written here and
  -- nowhere else. One UPDATE, so `dispatched` + NULL acceptance is structurally unreachable for any
  -- row written after Phase A — which is what lets the re-notice routine treat that combination as
  -- an unambiguous LEGACY marker rather than as a state it might have produced itself.
  --
  -- ★ IT IS KEYED ON `p_outcome`, NOT ON `v_status`. They agree today: `providerAccepted` is the only
  -- branch that yields `dispatched`. Keying on the OUTCOME ties the stamp to what the provider
  -- actually reported, so if a future branch ever reaches `dispatched` by another route it does not
  -- silently inherit an acceptance fact nobody established. `outcomeUncertain`, `retryPending` and
  -- `failedPermanent` all leave it NULL — an unknown outcome must never be recorded as an acceptance,
  -- which is the whole reason this column exists rather than a status list.
  --
  -- First-write-wins needs no `where notice_accepted_at is null` guard: the settled-status no-op
  -- above already makes a second settle unreachable, and a redundant guard here would mask a future
  -- change to that no-op instead of failing beside it.
  update public.owner_notice_outbox
     set status             = v_status,
         failure_class      = v_class,
         next_attempt_at    = v_next,
         dispatched_at      = case when v_status = 'dispatched' then now() else dispatched_at end,
         notice_accepted_at = case when p_outcome = 'providerAccepted' then now()
                                   else notice_accepted_at end
   where id = p_id;

  -- ★ THE AUDIT NAMES THE OUTCOME AND THE CHANNEL CLASS, NEVER THE ADDRESS — the same discipline as
  -- the dispatch audit it follows. An audit row outlives every reason anyone had to read it.
  -- actor_id is NULL because the actor is a scheduled worker, not a person; `source = 'worker'`
  -- says so without inventing a synthetic operator identity.
  insert into public.audit_logs (actor_id, estate_id, action, target_table, target_id, metadata, source)
  values (null, v_row.estate_id, 'death_process.owner_notice_outcome', 'owner_notice_outbox', p_id,
          jsonb_build_object('severity', 'high', 'outcome', v_status,
                            'failure_class', v_class, 'attempts', v_row.attempts,
                            'channel', v_row.channel, 'notice_kind', v_row.notice_kind),
          'worker');
  return v_status;
end $function$;
revoke execute on function public.record_owner_notice_outcome(uuid, text, text)
  from public, anon, authenticated;
grant  execute on function public.record_owner_notice_outcome(uuid, text, text) to service_role;

comment on function public.record_owner_notice_outcome(uuid, text, text) is
  'Write-back half of the owner-safety notice drain (Phase 11-K). providerAccepted -> dispatched; '
  'retryPending -> queued with backoff until a 3-attempt cap, then failedPermanent; '
  'outcomeUncertain and failedPermanent are terminal. An already-settled row is a no-op, so a '
  'duplicate callback can never produce a second send. Records no recipient address. service_role only.';

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- purge_outbox_rows(p_outbox, p_before, p_reason) → int                       [admin, AAL2+fresh]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ THE AUDIT ROW IS WRITTEN BEFORE THE DELETE, IN THE SAME TRANSACTION. Not after — an audit
-- written afterwards is an audit that a failure can skip, leaving rows gone and no record of who
-- removed them or why. Here the audit and the deletion commit together or neither happens.
--
-- ★ A REASON IS REQUIRED AND CANNOT BE BLANK. "Cleaning up" is not a reason; the column exists so
-- that someone reconstructing a disputed release a year later can tell a routine hygiene sweep from
-- a deletion that removed the evidence of an owner who was never reached.
--
-- ★ IT REFUSES TO TOUCH ROWS THAT ARE STILL ACTIONABLE. `queued` and `processing` notices are live
-- safety messages; purging those would be deleting an owner's warning while it is still in flight.
-- Only settled rows (dispatched / failedPermanent / cancelled) can be purged, and only ones older
-- than an explicit cutoff the caller states.
create or replace function public.purge_outbox_rows(
  p_outbox text,
  p_before timestamptz,
  p_reason text
)
 returns int
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid    uuid;
  v_count  int;
  v_oldest timestamptz;
  v_newest timestamptz;
  v_audit  uuid;
begin
  perform public.admin_require_gate();
  v_uid := auth.uid();

  if p_reason is null or btrim(p_reason) = '' then
    raise exception 'purge_reason_required' using errcode = 'P0001';
  end if;
  if p_before is null then
    raise exception 'purge_cutoff_required' using errcode = 'P0001';
  end if;
  -- A closed vocabulary of purgeable outboxes. An unknown name is refused rather than resolved
  -- dynamically: `execute format('delete from %I')` on a caller-supplied table is how an admin
  -- routine becomes a general-purpose delete.
  if p_outbox is distinct from 'owner_notice_outbox' then
    raise exception 'unknown_outbox' using errcode = 'P0001';
  end if;

  select count(*), min(requested_at), max(requested_at)
    into v_count, v_oldest, v_newest
    from public.owner_notice_outbox
   where status in ('dispatched', 'failedPermanent', 'cancelled')
     and requested_at < p_before;

  if v_count = 0 then
    return 0; -- nothing to purge writes no audit row: an audit of a no-op is noise, not evidence
  end if;

  insert into public.outbox_purge_audit
    (outbox_name, actor_id, row_count, oldest_row_at, newest_row_at, reason)
  values (p_outbox, v_uid, v_count, v_oldest, v_newest, p_reason)
  returning id into v_audit;

  -- Stamp the audit id onto the rows first, so even a partial failure leaves the link.
  update public.owner_notice_outbox
     set purge_audit_id = v_audit
   where status in ('dispatched', 'failedPermanent', 'cancelled')
     and requested_at < p_before;

  delete from public.owner_notice_outbox
   where status in ('dispatched', 'failedPermanent', 'cancelled')
     and requested_at < p_before;

  insert into public.audit_logs (actor_id, estate_id, action, target_table, target_id, metadata, source)
  values (v_uid, null, 'outbox.purged', 'outbox_purge_audit', v_audit,
          jsonb_build_object('severity', 'high', 'outbox', p_outbox, 'row_count', v_count,
                            'oldest_row_at', v_oldest, 'newest_row_at', v_newest,
                            'reason', p_reason),
          'admin');
  return v_count;
end $function$;
revoke execute on function public.purge_outbox_rows(text, timestamptz, text) from public, anon;
grant  execute on function public.purge_outbox_rows(text, timestamptz, text) to authenticated;

comment on function public.purge_outbox_rows(text, timestamptz, text) is
  'Purges SETTLED owner-notice rows older than an explicit cutoff (Phase 11-F, Stage 3). Writes the '
  'outbox_purge_audit row BEFORE deleting, in the same transaction, so a silent purge is impossible. '
  'Requires a non-blank reason, refuses an unknown outbox name, and never touches queued or '
  'processing rows — those are live safety messages still in flight.';

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- owner_notice_census() → jsonb                                                [admin, AAL2+fresh]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- The read-only classification Stage 3 requires before any delivery path is enabled: totals, status
-- distribution, age distribution, and the actionable/stale split — computed against the CURRENT age
-- gate rather than against a remembered one. Counts only; no recipient address, no estate name.
create or replace function public.owner_notice_census()
 returns jsonb
 language plpgsql
 security definer
 stable
 set search_path to 'public'
as $function$
declare v_gate interval; v_out jsonb;
begin
  perform public.admin_require_gate();
  v_gate := public.owner_notice_age_gate();

  -- ★ TWO SEPARATE AGGREGATIONS, COMBINED — NOT A LATERAL JOIN. The first draft joined a
  -- per-status GROUP BY laterally onto the row set, which returns every status group for EVERY row:
  -- three rows across three statuses became nine, and `total` reported 9. The status map looked
  -- right (duplicate keys resolve last-wins), so a test asserting only the presence of keys passed
  -- while the headline number was triple the truth. A census whose total is wrong is worse than no
  -- census — it is the number an operator would quote when deciding whether to purge.
  with rows as (
    select o.status, o.requested_at, o.claimed_at,
           -- ★ PHASE 11-OC. The three facts that make the Phase D blast radius countable.
           o.notice_accepted_at, o.case_id, o.superseded_by, o.generation
      from public.owner_notice_outbox o
  ),
  by_gen as (
    select coalesce(jsonb_object_agg(t.generation::text, t.n), '{}'::jsonb) as m
      from (select r.generation, count(*) as n from rows r group by r.generation) t
  ),
  by_status as (
    select coalesce(jsonb_object_agg(t.status, t.n), '{}'::jsonb) as m
      from (select r.status, count(*) as n from rows r group by r.status) t
  )
  select jsonb_build_object(
    'total', (select count(*) from rows),
    'by_status', (select m from by_status),
    'age_gate', v_gate::text,
    'oldest_requested_at', (select min(r.requested_at) from rows r),
    'newest_requested_at', (select max(r.requested_at) from rows r),
    'actionable', (select count(*) from rows r
                    where r.status = 'queued'
                      and v_gate is not null and r.requested_at >= now() - v_gate),
    'stale', (select count(*) from rows r
               where r.status in ('queued', 'processing')
                 and v_gate is not null and r.requested_at < now() - v_gate),
    -- ★ 11-K: without this key an `outcomeUncertain` row would appear in `total` and `by_status`
    -- and in NONE of the three splits, so an operator reconciling actionable+stale+purgeable
    -- against the total would find a gap with no name — and a nameless gap in a safety queue is
    -- the number someone eventually explains away. It is counted separately rather than folded
    -- into `purgeable` because it is deliberately NOT purgeable.
    'uncertain', (select count(*) from rows r where r.status = 'outcomeUncertain'),
    'purgeable', (select count(*) from rows r
                   where r.status in ('dispatched', 'failedPermanent', 'cancelled')),
    -- ★ PHASE 11-OBR / OB-1 — THE STUCK-CLAIM SPLIT, WITHOUT WHICH THIS DEFECT IS INVISIBLE.
    --
    -- The Branch A notice sat at `processing` for a day and nothing anywhere said so: `by_status`
    -- carried a `processing: 1` that reads as healthy in-flight work, and there was no way to ask
    -- how long it had been in flight. These three keys are what turn "a notice is being sent" into
    -- "a notice has been abandoned", which is a different operational fact entirely.
    --
    -- `processing_stale` uses the SAME predicate the drain reclaims by — including its NULL branch —
    -- read from `owner_notice_claim_visibility()` rather than restated, so this number is exactly
    -- "rows the next drain will pick up" and not an approximation of it.
    'processing_total', (select count(*) from rows r where r.status = 'processing'),
    'processing_stale', (select count(*) from rows r
                          where r.status = 'processing'
                            and (r.claimed_at is null
                                 or r.claimed_at < now() - public.owner_notice_claim_visibility())),
    -- Age of the OLDEST claim still in flight, as an interval string. NULL when nothing is
    -- processing. A legacy row with no claimed_at cannot have an age computed, so it reports NULL
    -- here and is counted in `processing_stale` above — the count is the alarm, this is the detail.
    'oldest_processing_age', (select (now() - min(r.claimed_at))::text from rows r
                               where r.status = 'processing' and r.claimed_at is not null),
    -- ────────────────────────────────────────────────────────────────────────────────────────
    -- ★ PHASE 11-OC — THE ACCEPTANCE AND EPISODE SPLITS.
    -- ────────────────────────────────────────────────────────────────────────────────────────
    --
    -- These four keys are what make the Phase D blast radius a NUMBER instead of an argument. They
    -- follow the `uncertain` key's discipline exactly: every row must land in a NAMED split, because
    -- a nameless gap in a safety queue is the number someone eventually explains away.
    --
    -- The reconciliation an operator can perform, and which the suite asserts:
    --
    --   accepted_total + unaccepted_total            = total
    --   legacy_unaccepted ⊆ unaccepted_total         (it is the `dispatched` slice of it)
    --   sum(by_generation values)                    = total
    --
    -- `accepted_total` counts the FACT, not the status: a row is accepted because a provider
    -- acceptance was stamped on it, never because it reached some status.
    'accepted_total',   (select count(*) from rows r where r.notice_accepted_at is not null),
    'unaccepted_total', (select count(*) from rows r where r.notice_accepted_at is null),
    -- ★ THE LEGACY POPULATION, PRECISELY. `dispatched` with no acceptance fact is the shape that
    -- existed before Phase A and is structurally unreachable after it (status and acceptance are
    -- written in one UPDATE). A non-zero count here is therefore a count of PRE-PHASE-A rows, which
    -- is exactly the population Phase D would refuse and Phase C must remediate.
    'legacy_unaccepted', (select count(*) from rows r
                           where r.status = 'dispatched' and r.notice_accepted_at is null),
    -- Rows that belong to no episode. Also strictly pre-Phase-A: the INSERT trigger refuses a NULL
    -- case_id, so this can only shrink.
    'no_episode',       (select count(*) from rows r where r.case_id is null),
    'superseded_total', (select count(*) from rows r where r.superseded_by is not null),
    'current_total',    (select count(*) from rows r where r.superseded_by is null),
    'by_generation',    (select m from by_gen)
  ) into v_out;

  return v_out;
end $function$;
revoke execute on function public.owner_notice_census() from public, anon;
grant  execute on function public.owner_notice_census() to authenticated;

comment on function public.owner_notice_census() is
  'Read-only owner-notice outbox classification (Phase 11-F, Stage 3): totals, status and age '
  'distribution, and the actionable/stale/purgeable split against the CURRENT age gate. Phase 11-OC '
  'adds the acceptance and episode splits (accepted_total, legacy_unaccepted, no_episode, '
  'superseded_total, by_generation), each reconciling against total with no nameless gap. Counts '
  'only — never a recipient address. Admin-gated.';

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- owner_notice_release_readiness_census() → jsonb                            [admin, AAL2+fresh]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ PHASE 11-OC · THE BLAST RADIUS, AS A NUMBER, BEFORE THE POLICY THAT CREATES IT.
--
-- `owner_notice_census` counts ROWS. This counts ESTATES AT THE DOOR — the population Phase D's
-- stricter release predicate will actually judge — classified by the state of the CURRENT generation
-- of the CURRENT case episode. It exists so the Phase D cutover decision is made against a measured
-- count rather than an assumption, and so the class that needs the Phase C remedy is named before it
-- is blocked.
--
-- ★ IT IS SCOPED EXACTLY AS THE PHASE D PREDICATE WILL BE, OR IT WOULD BE MEASURING SOMETHING ELSE.
-- Current case episode (`status = 'verified'`, newest `decided_at`), current generation
-- (`superseded_by is null`), email channel, window-opened kind. A census that aggregated by estate
-- would count an accepted notice from a prior REJECTED case as readiness for a new one — which is
-- the exact defect Phase D exists to close, reproduced in the instrument built to measure it.
--
-- ★ EVERY ESTATE LANDS IN EXACTLY ONE NAMED BUCKET, AND THE BUCKETS RECONCILE AGAINST THE TOTAL.
-- The `uncertain` discipline again: a nameless remainder is the number someone explains away. The
-- suite asserts the sum, so a future status that fell through would break the reconciliation rather
-- than hide in it.
--
-- ★ TWO ABSENCES ARE DISTINGUISHED, BECAUSE THE OPERATOR'S NEXT ACTION DIFFERS.
--   · `no_current_notice`            — no notice row names this case at all. Needs dispatch, not
--                                      re-notice. Fail-closed either way.
--   · `ambiguous_historical_linkage` — the estate HAS notice rows but they carry a NULL case_id, so
--                                      which episode they belong to is unprovable. These are
--                                      pre-Phase-A rows and are NEVER guessed into an episode; the
--                                      remedy is a re-notice that produces a fact, never a backfill
--                                      that invents one.
--
-- ★ PRIVACY-MINIMIZED BY CONSTRUCTION. Counts only. No estate id, no estate name, no case id, no
-- user id, no recipient address — on any branch. There is nothing here to correlate back to a living
-- owner, which is the point: an operator deciding a rollout needs a distribution, not a roster.
create or replace function public.owner_notice_release_readiness_census()
 returns jsonb
 language plpgsql
 security definer
 stable
 set search_path to 'public'
as $function$
declare v_out jsonb;
begin
  perform public.admin_require_gate();

  with door as (
    -- Every estate standing at the release door. `challenge_window` is the ONLY state Phase D's
    -- predicate governs; a released estate is past the door and an earlier one has not reached it.
    --
    -- ★ THE TABLE, NOT `estate_lifecycle_state()`, AND THE CHOICE IS FORCED RATHER THAN CASUAL.
    --
    -- `deathVerificationFoundation.test.ts` keeps two lists with two different privileges, and this
    -- read had to land in one of them. Going through the reader looks stricter and violates the OTHER
    -- rule in the same audit: outside the death module the reader may appear only as an argument to
    -- `release_condition_satisfied`, never in a local comparison — because
    -- `if estate_lifecycle_state(e) = '…'` is release policy leaking back out of the canonical module
    -- one `if` at a time, which that audit calls the single most likely accident here. A
    -- `where estate_lifecycle_state(e.id) = 'challenge_window'` scan is exactly that shape.
    --
    -- So this file joins `LIFECYCLE_TABLE_READERS`, the list `operator_console.sql` already occupies
    -- for the same reason: an operator PROJECTION that reports where the machine stands. Membership
    -- carries a proof obligation the other lists do not — the audit asserts every member is READ-ONLY
    -- against the lifecycle — and this file satisfies it: the census is `stable`, selects only, and
    -- names no transition, no lifecycle UPDATE and no INSERT.
    select l.estate_id
      from public.estate_lifecycle l
     where l.state = 'challenge_window'
  ),
  cur_case as (
    -- The CURRENT episode key, resolved exactly as authorize_release resolves it.
    select d.estate_id,
           (select c.id from public.death_verification_cases c
             where c.estate_id = d.estate_id and c.status = 'verified'
             order by c.decided_at desc limit 1) as case_id
      from door d
  ),
  cur_gen as (
    select cc.estate_id,
           cc.case_id,
           o.status,
           -- ★ ACCEPTANCE IS AN EXISTENTIAL OVER THE WHOLE EPISODE, NEVER A PROPERTY OF THE CURRENT
           -- GENERATION — and this census got that wrong on its first draft, which its own direction-1
           -- positive control caught.
           --
           -- The door asks "did ANY generation of this episode reach provider acceptance?". Reading
           -- only the current generation implements "latest generation only", which the architecture
           -- rejects explicitly: an already-accepted generation 1 would STOP qualifying the moment a
           -- generation 2 was created, so issuing a notice would REMOVE release authority and hand an
           -- operator a lever that suppresses a release. Authority is monotone — creating a generation
           -- can only ever ADD it — which is the same property that makes the MIN anchor immutable.
           --
           -- This must match the Phase D predicate exactly, or the console and the door disagree about
           -- the same estate.
           --
           -- ★ PHASE C — THE EPISODE IS A KIND SET, NOT ONE LITERAL, AND THAT IS WHAT MAKES THE
           -- REMEDY VISIBLE TO THE INSTRUMENT THAT MEASURES IT. A deliberate re-notice takes
           -- `death_process.window_renotice` (migration 0059) so a second warning is never recorded
           -- as the initial window-opening event. Left as the Phase A literal, this predicate could
           -- not see a re-notice at all: a remediated estate would keep reporting as REFUSED however
           -- many times it was re-noticed, its eventual provider acceptance would never be counted,
           -- and Phase C would be inert in exactly the census built to prove Phase C works.
           --
           -- Read from `owner_notice_episode_kinds()` rather than restated, for the reason
           -- `owner_notice_claim_visibility()` gives: two literals are two opinions about the same
           -- bytes, and the door and the census must never hold different ones.
           exists (
             select 1 from public.owner_notice_outbox a
              where a.case_id = cc.case_id
                and a.channel = 'email'
                and a.notice_kind = any (public.owner_notice_episode_kinds())
                and a.notice_accepted_at is not null
           ) as accepted_any,
           -- Does the estate carry any unlinkable pre-Phase-A row? Only consulted when no current
           -- generation was found, to separate "never dispatched" from "cannot be proven".
           (select count(*) from public.owner_notice_outbox z
             where z.estate_id = cc.estate_id and z.case_id is null) as orphan_rows
      from cur_case cc
      -- Phase C: the CURRENT generation may be a re-notice, so the join reads the episode kind SET
      -- for the same reason `accepted_any` above does. Left as one literal, a remediated estate would
      -- report `no_current_notice` — an estate that has just been re-noticed described as one that
      -- was never dispatched, which is the opposite of the truth and would send an operator to
      -- dispatch a window that is already open.
      left join public.owner_notice_outbox o
        on o.case_id = cc.case_id
       and o.channel = 'email'
       and o.notice_kind = any (public.owner_notice_episode_kinds())
       and o.superseded_by is null
  ),
  classified as (
    select case
             when case_id is null                              then 'no_verified_case'
             -- ★ THE ACCEPTANCE TEST COMES FIRST, and it is the ONLY bucket that decides admission.
             -- Everything below it describes what the CURRENT generation is doing, which is
             -- diagnostic information for an operator — useful, and not the release question.
             when accepted_any                                 then 'accepted'
             when status is null and orphan_rows > 0           then 'ambiguous_historical_linkage'
             when status is null                               then 'no_current_notice'
             when status = 'dispatched'                        then 'legacy_dispatched_unaccepted'
             when status = 'outcomeUncertain'                  then 'outcome_uncertain'
             when status = 'failedPermanent'                   then 'failed_permanent'
             when status = 'queued'                            then 'queued'
             when status = 'processing'                        then 'processing'
             when status = 'cancelled'                         then 'cancelled'
             -- ★ NOT A FALL-THROUGH. A status outside the six lands HERE, by name, so a widened
             -- CHECK constraint shows up as an unclassified count instead of silently joining a
             -- neighbouring bucket. The reconciliation assertion in the suite then fails loudly.
             else 'unclassified'
           end as bucket
      from cur_gen
  )
  select jsonb_build_object(
    'estates_at_door', (select count(*) from classified),
    'by_readiness',    coalesce((select jsonb_object_agg(t.bucket, t.n)
                                   from (select bucket, count(*) as n from classified group by bucket) t),
                                '{}'::jsonb),
    -- ★ THE ONE NUMBER THE PHASE D GATE TURNS ON. Estates at the door whose current episode carries
    -- NO provable provider acceptance — i.e. exactly those Phase D would refuse with
    -- `notice_never_accepted`. If this is non-zero, Phase D must not activate for that class until
    -- the Phase C re-notice remedy is deployed and operational.
    'would_be_refused_by_phase_d',
      (select count(*) from classified where bucket <> 'accepted'),
    'would_be_admitted_by_phase_d',
      (select count(*) from classified where bucket = 'accepted'),
    -- Retained so a reader can see that the strict policy is strictly narrower than today's, without
    -- having to reason about it: today's predicate admits every estate with any non-cancelled row.
    'would_be_admitted_by_current_predicate',
      (select count(*) from classified where bucket not in ('no_verified_case', 'no_current_notice',
                                                            'cancelled'))
  ) into v_out;

  return v_out;
end $function$;
revoke execute on function public.owner_notice_release_readiness_census() from public, anon;
grant  execute on function public.owner_notice_release_readiness_census() to authenticated;

comment on function public.owner_notice_release_readiness_census() is
  'Read-only Phase 11-OC blast-radius projection: how many estates standing at the release door '
  'would be admitted or refused by the Phase D acceptance predicate, classified by the state of the '
  'CURRENT generation of the CURRENT case episode. Scoped by case exactly as the Phase D predicate '
  'is, so it cannot credit an accepted notice from a prior rejected process. Every estate lands in '
  'one NAMED bucket and the buckets reconcile against the total. Counts ONLY — no estate id, no '
  'case id, no user id, no recipient address, on any branch. Admin-gated.';

commit;
-- ★ If you see an error above and no COMMIT, nothing was applied. Fix the cause and paste again.
