-- GENERATED by scripts/scripts/buildProvisioningCorrectionBundle.mjs — DO NOT EDIT.
-- Edit the sources instead:
--   db/functions/provision_from_invitation.sql
--   db/functions/accept_invitation.sql
--   db/functions/bind_invitation_token.sql
--   db/functions/create_invitation.sql
--
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- PASTE THIS WHOLE FILE INTO THE SUPABASE WEB SQL EDITOR AND RUN IT ONCE.
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- PURE SQL: this artifact contains no psql meta-commands. (\set and friends are client directives
-- the web editor cannot honour; they are stripped at build time and remain only in the sources,
-- which are applied through psql by the SQL suite.)
--
-- TRANSACTIONAL: the entire artifact runs inside ONE explicit transaction. Every statement here is
-- transaction-safe — the builder refuses to emit a wrapper otherwise — so:
--
--   · if ANY statement fails, the transaction aborts and COMMIT is never reached;
--   · the database is left EXACTLY as it was: there is no half-applied state to diagnose;
--   · the migrations' own self-checks raise on a bad state, which aborts before COMMIT too, so a
--     bundle that detects a problem rolls itself back rather than shipping it.
--
-- IDEMPOTENT: every table is IF NOT EXISTS, every function is CREATE OR REPLACE, every constraint
-- is dropped-then-added, and every seed uses ON CONFLICT. Re-running is safe and is the intended
-- recovery action after a failure.
begin;

-- ==== db/functions/provision_from_invitation.sql ==================================================
-- public.provision_from_invitation(p_invitation_id uuid, p_user uuid) -> uuid (estate_memberships.id)
--
-- SHARED, idempotent post-status provisioning for BOTH accept_invitation and bind_invitation_token (0021).
-- Holds: membership-reconcile + beneficiary self-link (triple-equality) + executor/trustee designation stamp
-- + audit. Assumes the caller already locked the invitation FOR UPDATE and ran the status + P0006 identity
-- guards. INTERNAL only (revoked from public/anon/authenticated — the DEFINER callers invoke it as owner).
--
-- Why a shared helper: a bind-accepted executor must NEVER end up membership-without-designation (a silent
-- authority void). Centralizing here also fixes the pre-existing bind beneficiary-self-link asymmetry.
-- Idempotent: membership ON CONFLICT(estate_id,user_id) DO NOTHING (reuse, don't duplicate); designation
-- ON CONFLICT (partial-unique-on-active) DO NOTHING; designation.created audited ONLY when inserted.
-- Captured from live 2026-07-15 (migration 0021). Source of truth — re-apply on reset.

create or replace function public.provision_from_invitation(p_invitation_id uuid, p_user uuid)
 returns uuid
 language plpgsql
 security definer
 set search_path to 'public', 'extensions'
as $function$
declare
  v_inv record;
  v_membership_id uuid;
  v_desig_id uuid;
  v_is_fiduciary boolean;
begin
  select * into v_inv from public.invitations where id = p_invitation_id;
  if not found then raise exception 'invitation_not_found' using errcode = 'P0002'; end if;

  -- ════════════════════════════════════════════════════════════════════════════════════════════════
  -- ★ PHASE 11-MC — A FIDUCIARY DESIGNATION NO LONGER MANUFACTURES A DISCLOSURE CLASS.
  -- ════════════════════════════════════════════════════════════════════════════════════════════════
  --
  -- Until now every acceptance inserted an `estate_memberships` row at the invitation's
  -- `proposed_role`, and `create_invitation` forces that to `'beneficiary'` for executor/trustee. So
  -- granting WORKFLOW capacity silently granted a DISCLOSURE access class as a side effect — the
  -- authority-model defect 11-MA diagnosed.
  --
  -- ★ THE GATE IS `kind`, NOT `proposed_role`, AND THAT CHOICE IS THE WHOLE COMPATIBILITY STORY.
  --
  -- `proposed_role` is PERSISTED AT CREATE TIME (`create_invitation` writes it into the row). Every
  -- executor/trustee invitation already in the table therefore carries a stored
  -- `proposed_role = 'beneficiary'`, and an invitation created before this change but accepted after it
  -- would still manufacture a membership if the provisioner keyed off that stale column. Correcting
  -- `create_invitation` alone fixes NOTHING for outstanding invitations.
  --
  -- `kind` is the authoritative, immutable statement of what the invitation IS. Keying on it fixes new
  -- and outstanding invitations in one place, with no data migration and no need to cancel anything.
  --
  -- ★ AND REMOVING THE FORCED ROLE ALONE WOULD HAVE BEEN WORSE THAN LEAVING IT. Without this gate, an
  -- executor invitation minted with `p_proposed_role = 'professional_delegate'` would provision a
  -- PROFESSIONAL DELEGATE membership instead of a beneficiary one — a different disclosure class,
  -- manufactured just as silently. The defect was never the forced value; it was that a fiduciary
  -- invitation created a membership at all.
  -- ★ `coalesce(..., false)` IS LOAD-BEARING, AND A LAXER TEST SCHEMA IS WHAT PROVED IT.
  --
  -- `NULL in ('executor','trustee')` evaluates to NULL, not false — so `if not v_is_fiduciary` would be
  -- `not NULL`, the membership branch would be SKIPPED, and an ordinary beneficiary acceptance would
  -- silently provision nothing. Production's `invitations.kind` is `text NOT NULL` so it cannot be null
  -- there; the test preamble declares it merely `text`, and an existing lifecycle fixture that omits
  -- `kind` failed immediately on the first run of this correction.
  --
  -- That divergence caught a genuine fragility rather than exposing a harmless one, which is why the
  -- preamble is NOT being tightened to match: a null kind must mean "not a fiduciary invitation" and
  -- therefore "provision exactly as before", because the conservative default for an unrecognised
  -- invitation is the path that existed before this change — never the one that creates no membership.
  v_is_fiduciary := coalesce(v_inv.kind in ('executor', 'trustee'), false);

  if not v_is_fiduciary then
    insert into public.estate_memberships
      (id, estate_id, user_id, role, status, source_invitation_id, approved_at, created_at)
    values
      (gen_random_uuid(), v_inv.estate_id, p_user, v_inv.proposed_role, 'approved', v_inv.id, now(), now())
    on conflict (estate_id, user_id) do nothing
    returning id into v_membership_id;
    if v_membership_id is null then
      select em.id into v_membership_id from public.estate_memberships em
       where em.estate_id = v_inv.estate_id and em.user_id = p_user;
    end if;

    if v_inv.proposed_role::text = 'beneficiary' then
      update public.beneficiaries set user_id = p_user
       where estate_id = v_inv.estate_id and user_id is null
         and ((v_inv.invitee_email is not null and lower(email) = lower(v_inv.invitee_email))
              or (v_inv.invitee_phone is not null and phone = v_inv.invitee_phone));
    end if;
  else
    /**
     * ★ AN INDEPENDENTLY-HELD MEMBERSHIP IS REPORTED, NEVER CREATED, AND NEVER TOUCHED.
     *
     * A person may already be a beneficiary or professional delegate of this estate for reasons that
     * have nothing to do with this invitation. Accepting a fiduciary invitation must leave that
     * relationship exactly as it was — it is a separate authority on a separate axis. So this SELECTs
     * an existing membership to report, and inserts none.
     *
     * ★ NULL IS A LEGITIMATE RETURN VALUE FROM HERE NOW. A fiduciary-only recipient has no membership,
     * so there is no `estate_memberships.id` to hand back. Both callers were adjusted to tell the truth
     * about that rather than assert an approved membership that does not exist, and the two BFF routes
     * that read the result were adjusted to accept it — see `lib/invitations/accept.ts`. Deploying this
     * routine BEFORE those callers would make every executor acceptance look like a 502.
     */
    select em.id into v_membership_id from public.estate_memberships em
     where em.estate_id = v_inv.estate_id and em.user_id = p_user;
  end if;

  if v_inv.kind in ('executor','trustee') then
    v_desig_id := null;
    insert into public.estate_designations
      (estate_id, user_id, designation_type, status, source_invitation_id, granted_by)
    values (v_inv.estate_id, p_user, v_inv.kind, 'active', v_inv.id, v_inv.invited_by)
    on conflict (estate_id, user_id, designation_type) where status = 'active' do nothing
    returning id into v_desig_id;
    if v_desig_id is not null then
      perform public.write_audit('designation.created', 'estate_designations', v_desig_id, v_inv.estate_id,
        jsonb_build_object('invitation_id', v_inv.id, 'designation_type', v_inv.kind));
    end if;
    -- VERIFICATION HOOK (NO-OP): per-claim verification (Reading A) attaches here later; no external call.
  end if;

  return v_membership_id;
end;
$function$;
revoke execute on function public.provision_from_invitation(uuid, uuid) from public, anon, authenticated;


-- ==== db/functions/accept_invitation.sql ==========================================================
-- public.accept_invitation(p_invitation_id uuid)
--   -> TABLE(membership_id uuid, estate_id uuid, estate_display_name text, role text, status text)
--
-- Accepts an invitation BY ID (matched-invitations screen). Validates token/expiry/status + the P0006
-- identity guard (caller's own contact must match the invitee), then delegates provisioning to the shared
-- public.provision_from_invitation helper (membership-reconcile + beneficiary self-link + executor/trustee
-- designation + audit). Idempotent: re-accept returns the existing membership and self-heals via the helper.
--
-- Error codes: 42501 unauthenticated, P0002 not_found, P0003 expired, P0004 revoked, P0005 already_accepted
-- (by someone else), P0006 not_for_caller, P0007 declined.
--
-- Captured from live 2026-07-15 (migration 0021 — refactored onto the shared helper). SECURITY DEFINER.

create or replace function public.accept_invitation(p_invitation_id uuid)
 returns table(membership_id uuid, estate_id uuid, estate_display_name text, role text, status text)
 language plpgsql
 security definer
 set search_path to 'public', 'extensions'
as $function$
declare
  v_user uuid := auth.uid();
  v_inv record; v_user_email text; v_user_phone text; v_membership_id uuid;
begin
  if v_user is null then raise exception 'unauthenticated' using errcode = '42501'; end if;
  select * into v_inv from public.invitations where id = p_invitation_id for update;
  if not found then raise exception 'invitation_not_found' using errcode = 'P0002'; end if;
  if v_inv.expires_at < now() then raise exception 'invitation_expired' using errcode = 'P0003'; end if;
  if v_inv.status = 'revoked' then raise exception 'invitation_revoked' using errcode = 'P0004'; end if;
  if v_inv.status = 'declined' then raise exception 'invitation_declined' using errcode = 'P0007'; end if;

  select profiles.email, profiles.phone into v_user_email, v_user_phone from public.profiles where profiles.id = v_user;
  if not ((v_inv.invitee_email is not null and lower(v_inv.invitee_email) = lower(coalesce(v_user_email,'')))
       or (v_inv.invitee_phone is not null and v_inv.invitee_phone = coalesce(v_user_phone,''))) then
    raise exception 'invitation_not_for_caller' using errcode = 'P0006';
  end if;

  -- Idempotency keys on the invitation's OWN accepted_by (authoritative), NOT the membership's
  -- source_invitation_id: a reconciled membership (an executor who was already a beneficiary member) has a
  -- different/NULL source, so keying on source would (a) spuriously P0005 a same-user re-accept AND (b)
  -- NEVER self-heal a missing designation — the silent-authority-void the shared helper exists to prevent.
  if v_inv.status = 'accepted' then
    if v_inv.accepted_by = v_user then
      perform public.provision_from_invitation(v_inv.id, v_user);   -- idempotent self-heal (re-stamps a missing designation)
      select em.id into v_membership_id from public.estate_memberships em
       where em.estate_id = v_inv.estate_id and em.user_id = v_user;
          -- ★ PHASE 11-MC: A FIDUCIARY ACCEPTANCE HAS NO MEMBERSHIP, SO IT REPORTS NONE.
      -- `provision_from_invitation` no longer creates a membership for an executor/trustee invitation,
      -- so `v_membership_id` is NULL for a recipient who holds no independent access class. Returning
      -- the invitation's stale `proposed_role` and a hardcoded 'approved' would assert an approved
      -- beneficiary membership that does not exist — the exact fiction this phase removes, restated on
      -- the way out. Role and status are NULL together with the membership id; the fiduciary authority
      -- is reported by `get_my_fiduciary_estates`, which is the surface that owns it.
  return query select v_membership_id, v_inv.estate_id,
        (select e.name from public.estates e where e.id = v_inv.estate_id),
        case when v_membership_id is null then null else v_inv.proposed_role::text end,
        case when v_membership_id is null then null else 'approved'::text end;
      return;
    else
      raise exception 'invitation_already_accepted' using errcode = 'P0005';
    end if;
  end if;

  update public.invitations set status='accepted', accepted_by=v_user, accepted_at=now(), updated_at=now() where id=v_inv.id;
  v_membership_id := public.provision_from_invitation(v_inv.id, v_user);
  perform public.write_audit('invitation.accepted', 'estate_memberships', v_membership_id, v_inv.estate_id,
    jsonb_build_object('invitation_id', v_inv.id, 'via', 'accept_by_id'));

  -- ★ PHASE 10-E — the OWNER learns their invitation was accepted. Deliberately BELOW the idempotent
  -- re-accept branch above, which returns early: a self-heal re-accept must not tell the owner a
  -- second time that someone joined.
  --
  -- The copy says "someone you invited", never who. The owner issued the invitation and already
  -- knows the invitee, so this says strictly LESS than they know — which is the correct direction
  -- for a surface whose whole job is to avoid becoming a disclosure channel. It also never names the
  -- accepted ROLE: a membership role is a relationship, and relationships are stated by the
  -- authoritative surfaces that already gate them, not by a heads-up.
  perform public.emit_lifecycle_notification(
    public.estate_owner_user_id(v_inv.estate_id),
    v_inv.estate_id,
    'invitation.accepted',
    'afterworth://owner-invitations'
  );
  return query select v_membership_id, v_inv.estate_id,
    (select e.name from public.estates e where e.id = v_inv.estate_id),
    case when v_membership_id is null then null else v_inv.proposed_role::text end,
    case when v_membership_id is null then null else 'approved'::text end;
end;
$function$;


-- ==== db/functions/bind_invitation_token.sql ======================================================
-- public.bind_invitation_token(p_token text)
--   -> TABLE(membership_id uuid, estate_id uuid, estate_display_name text, role text, status text)
--
-- Binds the authenticated caller to an invitation by its plaintext token (hashes it, looks up, verifies the
-- P0006 identity guard), then delegates provisioning to the shared public.provision_from_invitation helper
-- (membership-reconcile + beneficiary self-link + executor/trustee designation + audit). Idempotent.
--
-- 0021: refactored onto the shared helper. NOTE: the beneficiary self-link now runs on the TOKEN path too
-- (it previously ran only on accept-by-id — a pre-existing asymmetry, fixed here). Membership + the
-- invitation.bound audit are unchanged.
--
-- Error codes: 42501 unauthenticated, P0001 invalid_token, P0002 not_found, P0003 expired, P0004 revoked,
-- P0005 already_accepted (by someone else), P0006 not_for_caller.
--
-- Captured from live 2026-07-15. SECURITY DEFINER. Source of truth — re-apply on reset.

create or replace function public.bind_invitation_token(p_token text)
 returns table(membership_id uuid, estate_id uuid, estate_display_name text, role text, status text)
 language plpgsql
 security definer
 set search_path to 'public', 'extensions'
as $function$
declare
  v_user uuid := auth.uid(); v_hash text; v_inv record; v_user_email text; v_user_phone text; v_membership_id uuid;
begin
  if v_user is null then raise exception 'unauthenticated' using errcode = '42501'; end if;
  if p_token is null or length(p_token) < 16 or length(p_token) > 512 then
    raise exception 'invalid_token' using errcode = 'P0001';
  end if;
  v_hash := encode(digest(p_token, 'sha256'), 'hex');
  select * into v_inv from public.invitations where token_hash = v_hash for update;
  if not found then raise exception 'invitation_not_found' using errcode = 'P0002'; end if;
  if v_inv.expires_at < now() then raise exception 'invitation_expired' using errcode = 'P0003'; end if;
  if v_inv.status = 'revoked' then raise exception 'invitation_revoked' using errcode = 'P0004'; end if;

  select profiles.email, profiles.phone into v_user_email, v_user_phone from public.profiles where profiles.id = v_user;
  if not ((v_inv.invitee_email is not null and lower(v_inv.invitee_email) = lower(coalesce(v_user_email,'')))
       or (v_inv.invitee_phone is not null and v_inv.invitee_phone = coalesce(v_user_phone,''))) then
    raise exception 'invitation_not_for_caller' using errcode = 'P0006';
  end if;

  -- Idempotency keys on the invitation's OWN accepted_by (authoritative), NOT the membership's
  -- source_invitation_id (see accept_invitation) — a reconciled membership has a different/NULL source.
  if v_inv.status = 'accepted' then
    if v_inv.accepted_by = v_user then
      perform public.provision_from_invitation(v_inv.id, v_user);   -- idempotent self-heal (re-stamps a missing designation)
      select em.id into v_membership_id from public.estate_memberships em
       where em.estate_id = v_inv.estate_id and em.user_id = v_user;
          -- ★ PHASE 11-MC: A FIDUCIARY ACCEPTANCE HAS NO MEMBERSHIP, SO IT REPORTS NONE.
      -- `provision_from_invitation` no longer creates a membership for an executor/trustee invitation,
      -- so `v_membership_id` is NULL for a recipient who holds no independent access class. Returning
      -- the invitation's stale `proposed_role` and a hardcoded 'approved' would assert an approved
      -- beneficiary membership that does not exist — the exact fiction this phase removes, restated on
      -- the way out. Role and status are NULL together with the membership id; the fiduciary authority
      -- is reported by `get_my_fiduciary_estates`, which is the surface that owns it.
  return query select v_membership_id, v_inv.estate_id,
        (select e.name from public.estates e where e.id = v_inv.estate_id),
        case when v_membership_id is null then null else v_inv.proposed_role::text end,
        case when v_membership_id is null then null else 'approved'::text end;
      return;
    else
      raise exception 'invitation_already_accepted' using errcode = 'P0005';
    end if;
  end if;

  update public.invitations set status='accepted', accepted_by=v_user, accepted_at=now(), updated_at=now() where id=v_inv.id;
  v_membership_id := public.provision_from_invitation(v_inv.id, v_user);
  perform public.write_audit('invitation.bound', 'estate_memberships', v_membership_id, v_inv.estate_id,
    jsonb_build_object('token_fingerprint', substr(v_hash,1,12), 'invitation_id', v_inv.id));
  return query select v_membership_id, v_inv.estate_id,
    (select e.name from public.estates e where e.id = v_inv.estate_id),
    case when v_membership_id is null then null else v_inv.proposed_role::text end,
    case when v_membership_id is null then null else 'approved'::text end;
end;
$function$;


-- ==== db/functions/create_invitation.sql ==========================================================
-- public.create_invitation(p_estate, p_kind, p_proposed_role, p_invitee_email, p_invitee_phone,
--                          p_show_estate_name, p_show_inviter_name, p_expires_in_days)
--   -> TABLE(invitation_id uuid, raw_token text, token_fingerprint text, expires_at timestamptz)
--
-- Owner-OR-admin mints an invitation (invitation_write_gate). Returns the raw token ONCE. 0021 LIFTED the
-- executor/trustee rejection: kind now allows all four, and for executor/trustee proposed_role is DERIVED
-- to 'beneficiary' — the GENERIC access-class membership (fiduciary authority lives ONLY in
-- estate_designations, stamped at accept, NEVER the membership role). Pending-cap ≤20 active per estate.
-- Captured from live 2026-07-15 (previously VC-only in migration 0016). SECURITY DEFINER.

create or replace function public.create_invitation(
  p_estate uuid, p_kind text, p_proposed_role text,
  p_invitee_email text default null, p_invitee_phone text default null,
  p_show_estate_name boolean default false, p_show_inviter_name boolean default false,
  p_expires_in_days int default 14
)
 returns table(invitation_id uuid, raw_token text, token_fingerprint text, expires_at timestamptz)
 language plpgsql security definer set search_path to 'public', 'extensions'
as $function$
declare
  v_pending int; v_raw text; v_hash text;
  v_estate_name text; v_inviter_name text; v_email_hint text; v_phone_hint text;
  v_expires timestamptz; v_id uuid;
begin
  perform public.invitation_write_gate(p_estate);

  if p_invitee_email is null and p_invitee_phone is null then
    raise exception 'invitee_contact_required' using errcode = 'P0001';
  end if;

  if p_kind not in ('beneficiary','professional_delegate','executor','trustee') then
    raise exception 'kind_not_supported' using errcode = 'P0001';
  end if;
  -- ════════════════════════════════════════════════════════════════════════════════════════════════
  -- ★ PHASE 11-MC — THIS LINE STAYS, AND IT IS NOW INERT. BOTH HALVES OF THAT MATTER.
  -- ════════════════════════════════════════════════════════════════════════════════════════════════
  --
  -- WHY IT CANNOT BE REMOVED: `invitations.proposed_role` is `text NOT NULL` with
  -- `check (proposed_role = any (array['beneficiary','professional_delegate']))`. There is no value that
  -- honestly means "no access class", and inventing one is DDL on a live table plus a migration. So an
  -- executor/trustee invitation must still persist one of two disclosure-class words it does not mean.
  --
  -- WHY REMOVING IT WOULD HAVE BEEN WORSE THAN LEAVING IT: the defect was never this value. It was that
  -- `provision_from_invitation` created a membership AT this value for every acceptance. Drop the force
  -- and an executor invitation minted with `p_proposed_role = 'professional_delegate'` would have
  -- provisioned a PROFESSIONAL DELEGATE membership instead — a different manufactured disclosure class,
  -- and a worse one, because nothing in the product expects a fiduciary to arrive as a delegate.
  --
  -- WHERE THE FIX ACTUALLY LIVES: `provision_from_invitation` now gates membership creation on `kind`,
  -- the authoritative and immutable statement of what the invitation is. That also fixes every
  -- OUTSTANDING invitation — this column is written at CREATE time, so rows minted before the correction
  -- already carry 'beneficiary', and a provisioner keyed on `proposed_role` would have kept honouring it
  -- forever.
  --
  -- WHAT IT STILL AFFECTS: nothing in provisioning. It remains visible as `proposedRole` in
  -- `resolve_membership`'s pending-invitation payload, where the client maps it to a presentation-only
  -- `accessClass` label — `features/invitations/model.ts` states outright that nothing gates on it. So a
  -- fiduciary invitation card can still show the wrong relationship WORD. That is a real accuracy defect
  -- and it is recorded rather than silently tolerated: fixing it means surfacing `kind` in that payload,
  -- which is a separate backend+client slice. Making the column nullable belongs with it.
  if p_kind in ('executor','trustee') then
    p_proposed_role := 'beneficiary';
  elsif p_proposed_role not in ('beneficiary','professional_delegate') then
    raise exception 'invalid_proposed_role' using errcode = 'P0001';
  end if;

  if p_expires_in_days < 1 or p_expires_in_days > 90 then
    raise exception 'invalid_expiry' using errcode = 'P0001';
  end if;

  select count(*) into v_pending from public.invitations inv
  where inv.estate_id = p_estate and inv.status in ('pending','matched') and inv.expires_at > now();
  if v_pending >= 20 then raise exception 'pending_invitation_cap' using errcode = 'P0001'; end if;

  select e.name into v_estate_name from public.estates e where e.id = p_estate;
  select coalesce(nullif(p.full_name,''), p.email) into v_inviter_name from public.profiles p where p.id = auth.uid();
  v_email_hint := case when p_invitee_email is not null
    then left(p_invitee_email,1) || '•••@' || split_part(p_invitee_email,'@',2) else null end;
  v_phone_hint := case when p_invitee_phone is not null then '•••' || right(p_invitee_phone,4) else null end;
  v_raw := encode(gen_random_bytes(32), 'hex'); v_hash := encode(digest(v_raw, 'sha256'), 'hex');
  v_expires := now() + make_interval(days => p_expires_in_days);

  insert into public.invitations
    (id, estate_id, invited_by, kind, proposed_role, status, expires_at, invitee_email, invitee_phone,
     invitee_email_hint, invitee_phone_hint, estate_display_name, inviter_display_name, preview_visibility,
     token_hash, created_at, updated_at)
  values
    (gen_random_uuid(), p_estate, auth.uid(), p_kind, p_proposed_role, 'pending', v_expires,
     p_invitee_email, p_invitee_phone, v_email_hint, v_phone_hint, v_estate_name, v_inviter_name,
     jsonb_build_object('showEstateName', p_show_estate_name, 'showInviterName', p_show_inviter_name),
     v_hash, now(), now())
  returning id into v_id;

  perform public.write_audit('invitation.created', 'invitations', v_id, p_estate,
    jsonb_build_object('invitation_id', v_id, 'kind', p_kind, 'proposed_role', p_proposed_role,
                       'token_fingerprint', substr(v_hash,1,12), 'expires_at', v_expires,
                       'invitee_email_hint', v_email_hint));
  return query select v_id, v_raw, substr(v_hash,1,12), v_expires;
end;
$function$;
revoke execute on function public.create_invitation(uuid,text,text,text,text,boolean,boolean,int) from public, anon;
grant  execute on function public.create_invitation(uuid,text,text,text,text,boolean,boolean,int) to authenticated;

commit;
-- ★ If you see an error above and no COMMIT, nothing was applied. Fix the cause and paste again.
