-- GENERATED by scripts/buildReleaseConditionBundle.mjs — DO NOT EDIT.
-- Edit the sources instead:
--   db/migrations/0051_20260812_release_condition_engine.sql
--   db/migrations/0052_20260812_death_verification_foundation.sql
--   db/migrations/0053_20260812_lifecycle_aware_release_predicate.sql
--   db/migrations/0054_20260812_challenge_window_release_seam.sql
--   db/migrations/0055_20260812_release_authorization.sql
--   db/functions/release_conditions.sql
--   db/functions/estate_lifecycle_state.sql
--   db/functions/document_grantable.sql
--   db/functions/can_access_document.sql
--
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- PASTE THIS WHOLE FILE INTO THE SUPABASE WEB SQL EDITOR AND RUN IT ONCE.
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- PURE SQL: this artifact contains no psql meta-commands. (\set and friends are client directives
-- the web editor cannot honour; they are stripped at build time and remain only in the sources,
-- which are applied through psql by the SQL suite.)
--
-- TRANSACTIONAL: the entire artifact runs inside ONE explicit transaction. Every statement here is
-- transaction-safe — the builder refuses to emit a wrapper otherwise — so:
--
--   · if ANY statement fails, the transaction aborts and COMMIT is never reached;
--   · the database is left EXACTLY as it was: there is no half-applied state to diagnose;
--   · the migrations' own self-checks raise on a bad state, which aborts before COMMIT too, so a
--     bundle that detects a problem rolls itself back rather than shipping it.
--
-- IDEMPOTENT: every table is IF NOT EXISTS, every function is CREATE OR REPLACE, every constraint
-- is dropped-then-added, and every seed uses ON CONFLICT. Re-running is safe and is the intended
-- recovery action after a failure.
begin;

-- ==== db/migrations/0051_20260812_release_condition_engine.sql ====================================
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- 0051 · PHASE 11-B — the canonical release-condition engine, and the death/incapacity split
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- ★ THIS MIGRATION CHANGES NO DISCLOSURE. Every read path answers exactly what it answered before,
-- for every stored row, and the SQL suite compares the full input space to prove it rather than
-- asserting it. What changes is WHERE the answer is decided.
--
-- Two things happen here:
--
--   1 · The release rule — written out seven times across five routines, giving two different
--       answers — moves into `public.release_condition_satisfied`, and every evaluator becomes a
--       caller. Phase 11 activates a death condition; doing that with seven copies is how the four
--       role maps drifted apart in Phase 9.
--
--   2 · `after_verified_death_or_incapacity` is split into `after_verified_death` and
--       `after_verified_incapacity`. The CHECK is WIDENED to admit both while keeping the fused
--       value legal, so no stored row is rewritten, reinterpreted or invalidated. The RPC write gate
--       (`release_condition_writable`) refuses the fused value for new rows.
--
-- ★ WHY THE OLD VALUE STAYS LEGAL. Deciding that a fused row "really meant death" is a product
-- decision about somebody else's estate, and it points at a disclosure that cannot be undone.
-- Deciding it meant incapacity is the same guess reversed. An unsatisfiable legacy state costs an
-- owner one re-authoring; a wrong guess costs a survivor's privacy. No row becomes more permissive:
-- the fused value was dormant before this migration and is dormant after it.
--
-- ★ NOTHING HERE VERIFIES A DEATH OR RELEASES ANYTHING. `after_verified_death` is storable and
-- satisfied by nothing. There is still no routine that writes a released state, and no read path
-- consults the release seam. This migration makes the eventual wiring a one-file change; it does not
-- perform it.
--
-- IDEMPOTENT. Safe to re-apply: the constraint is dropped-if-exists before being added, and every
-- function is `create or replace`.
--
-- APPLY ORDER: this migration must precede any re-application of
-- `estate_inventory_and_discovery_bundle.sql` or `lifecycle_notifications_bundle.sql`, whose
-- functions now call `public.release_condition_satisfied`. The
-- `release_conditions_bundle.sql` artifact bundles this file with those functions in the right
-- order for a single paste.

-- [psql meta-command removed for the SQL editor] \set ON_ERROR_STOP on

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 1 · WIDEN the release-condition vocabulary. Additive only.
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ THE CONSTRAINT NAME IS RESOLVED, NOT GUESSED. `access_grants.release_condition` was declared
-- inline in migration 0002 (`release_condition text not null check (...)`), so Postgres generated
-- the name — `access_grants_release_condition_check` by convention, but a database that has been
-- through a table rewrite or a manual repair may carry something else. Dropping a guessed name with
-- `if exists` would silently no-op and leave the OLD constraint in force, and the migration would
-- report success having widened nothing: the new conditions would then be refused by storage while
-- the RPC gate accepted them. So the name is looked up from the catalog by the column it governs.
do $$
declare
  v_name text;
begin
  for v_name in
    select con.conname
      from pg_constraint con
      join pg_class rel on rel.oid = con.conrelid
      join pg_namespace nsp on nsp.oid = rel.relnamespace
     where nsp.nspname = 'public'
       and rel.relname = 'access_grants'
       and con.contype = 'c'
       and pg_get_constraintdef(con.oid) ilike '%release_condition%'
  loop
    execute format('alter table public.access_grants drop constraint %I', v_name);
    raise notice 'dropped prior release_condition constraint: %', v_name;
  end loop;

  alter table public.access_grants
    add constraint access_grants_release_condition_check
    check (release_condition in (
      'never',
      'immediately',
      'after_owner_approval',
      'after_identity_verification',
      'after_access_request_approval',
      -- Phase 11-B: the split. Storable, and satisfied by nothing.
      'after_verified_death',
      'after_verified_incapacity',
      -- DEPRECATED, DELIBERATELY STILL LEGAL. Stored rows must remain readable, and
      -- `release_condition_writable` refuses it for every new write.
      'after_verified_death_or_incapacity',
      'after_claim_case_approval'
    ));
end $$;

-- ★ PROVE THE WIDENING TOOK, IN THE MIGRATION ITSELF. A constraint that failed to move would leave
-- `create_asset_grant` accepting a condition storage refuses — an error surfacing at insert time,
-- from a gate that had already said yes. Both directions are checked: the new values admitted, the
-- fused value still admitted, and an invented value still refused (or the CHECK has been dropped
-- rather than replaced, which reads identically from the accepting side).
do $$
declare
  v_def text;
begin
  select pg_get_constraintdef(con.oid) into v_def
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
   where nsp.nspname = 'public' and rel.relname = 'access_grants'
     and con.conname = 'access_grants_release_condition_check';

  if v_def is null then
    raise exception '0051 FAILED: the release_condition CHECK is absent after the widening';
  end if;
  if position('after_verified_death''' in v_def) = 0 then
    raise exception '0051 FAILED: after_verified_death is not in the widened CHECK: %', v_def;
  end if;
  if position('after_verified_incapacity' in v_def) = 0 then
    raise exception '0051 FAILED: after_verified_incapacity is not in the widened CHECK: %', v_def;
  end if;
  if position('after_verified_death_or_incapacity' in v_def) = 0 then
    raise exception '0051 FAILED: the legacy fused value was dropped — stored rows would be orphaned';
  end if;
  raise notice '0051 · release_condition vocabulary widened (death/incapacity split, legacy retained)';
end $$;


-- ==== db/migrations/0052_20260812_death_verification_foundation.sql ===============================
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- 0052 · PHASE 11-C — death event + evidence + verification-state FOUNDATION (data model only)
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- ★ THIS MIGRATION CHANGES NO DISCLOSURE. It creates three tables and grants NOTHING to any client
-- role. Every read path answers exactly what it answered before, for every stored row — the Phase
-- 11-C SQL suite compares composed viewer payloads across every new state to prove it.
--
-- What exists after this migration:
--
--   1 · `estate_lifecycle` — the AUTHORITATIVE estate lifecycle record Phase 11-B deferred here.
--       One current state per estate. `claim_packets.status` stops being the only carrier of
--       anything lifecycle-shaped: the claim row is EVIDENCE FOR a lifecycle event, never the event.
--       (`estate_release_state()` remains what it was — a label-only projection of claim status
--       with one consumer — untouched, still consulted by no authorization path.)
--
--   2 · `death_verification_cases` — the death-verification case: who initiated, in what fiduciary
--       capacity, under what jurisdiction context, what the policy REQUIRED at initiation, and what
--       has actually been ATTAINED. Required and attained are different columns with different
--       writers, and the attained baseline is NULL — nothing attained — which is the fail-closed
--       floor every comparison must coalesce against.
--
--   3 · `death_verification_evidence` — evidence received for a case. Evidence KIND is not modelled
--       here as a new vocabulary: an evidence row references a `documents` row, and the document
--       taxonomy (a server catalog) is the authoritative descriptor of what a document is. Review
--       status says only what the platform actually did — `received` / `reviewed_accepted` /
--       `reviewed_rejected` — never "verified": no authenticity vendor exists, and a status that
--       claimed verification would be a fact the system does not possess.
--
-- ★ WHAT IS DELIBERATELY IMPOSSIBLE HERE:
--
--   · `released` is NOT in the lifecycle CHECK. Making an estate released is not a state this
--     schema can store, let alone a transition a routine could take. Widening that CHECK is 11-D's
--     controlled, reviewed change — not a value waiting for a writer.
--   · `event_type` admits ONLY 'death'. Incapacity is a legally distinct event (D9); the fused
--     death-or-incapacity shape is unrepresentable for new rows. Widening the CHECK is an explicit
--     future migration, not an accepted value.
--   · No client role can read or write any of the three tables. RLS is enabled and there are ZERO
--     grants and ZERO policies — the tables are reachable only through the SECURITY DEFINER
--     routines in `db/functions/death_verification.sql`, each of which carries its own gate.
--   · Nothing here manufactures a grant, a disclosure tier, or a fiduciary capacity. The case
--     records facts ABOUT verification; it is not itself an access instrument.
--
-- ★ REQUIRED vs ATTAINED. `required_level_at_initiation` is a SNAPSHOT of what
-- `public.required_verification_level(estate)` answered when the case was opened — recorded so the
-- case file is honest about the policy in force at initiation. It is NEVER the enforcement input:
-- the decision routine re-derives the requirement live at decision time, so a policy tightened
-- mid-case tightens the case. The snapshot cannot leak into `attained_level` — different columns,
-- different writers, and the suite mutation-proves that initiation leaves attained NULL.
--
-- IDEMPOTENT. Safe to re-apply: `create table if not exists`, `create index if not exists`, and
-- the self-checks at the end raise rather than silently no-op.
--
-- APPLY ORDER: requires migrations 0019 (estate_designations), 0026/0027 (verification_level enum +
-- policy engine), 0035 (documents write path exists in practice) — all deployed long before this
-- file. Standing Phase 11-B rule unchanged: `release_conditions_bundle.sql` is pasted FIRST before
-- any other bundle re-application. The `death_verification_bundle.sql` artifact bundles this file
-- with its routines in the right order for a single paste.

-- [psql meta-command removed for the SQL editor] \set ON_ERROR_STOP on

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 1 · THE ESTATE LIFECYCLE RECORD — one authoritative current state per estate
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ ABSENT ROW = 'active'. Every estate that has never seen a death-verification case has no row
-- here, and `estate_lifecycle_state()` reads that absence as the base state. That keeps the table
-- append-on-first-event rather than requiring a backfill trigger on estate creation, and it means
-- the empty table is a correct table, not a missing one.
--
-- ★ HISTORY LIVES IN `audit_logs`. Every transition writes an audit row carrying from/to/case/actor
-- (see `apply_estate_lifecycle_transition`), so the current-state row can stay a single row per
-- estate without losing the append-only trail the 11-A forensics review required.
create table if not exists public.estate_lifecycle (
  estate_id  uuid primary key references public.estates(id) on delete cascade,
  -- 'released', 'frozen', 'release_pending' are DELIBERATELY NOT HERE. A value with no writer is a
  -- value waiting for one; the 11-D activation adds states the same reviewed way this file adds
  -- these three. `death_verified` IS reachable in 11-C — through exactly one admin-gated routine
  -- that enforces attained ≥ required — and the Phase 11-C suite proves reaching it changes no
  -- viewer payload by one byte.
  state           text        not null default 'active'
    check (state in ('active', 'death_verification_pending', 'death_verified')),
  updated_at      timestamptz not null default now(),
  -- The case that most recently moved this estate's state (null for the base row shape). Kept as a
  -- plain FK for forensics; authority never flows FROM this column.
  updated_case_id uuid
);

alter table public.estate_lifecycle enable row level security;
-- ZERO grants, ZERO policies — not client-readable, not client-writable, by construction. The
-- jurisdiction_policy precedent: a table only DEFINER routines may touch needs no latent policy
-- inviting a future grant to widen it.

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 2 · THE DEATH-VERIFICATION CASE
-- ────────────────────────────────────────────────────────────────────────────────────────────────
create table if not exists public.death_verification_cases (
  id                           uuid        primary key default gen_random_uuid(),
  estate_id                    uuid        not null references public.estates(id) on delete cascade,
  -- ★ ONLY 'death'. Incapacity is a distinct event with a deferred workflow (D9); admitting it here
  -- before that workflow exists would be vocabulary ahead of authorization. The fused value is
  -- unrepresentable — that is the point.
  event_type                   text        not null default 'death'
    check (event_type in ('death')),
  status                       text        not null default 'open'
    check (status in ('open', 'verified', 'rejected', 'cancelled')),
  initiated_by                 uuid        not null references auth.users(id),
  -- The designation row that AUTHORIZED initiation, and the capacity it carried at that moment.
  -- Capacity is a snapshot of fact ("this person acted as executor"), never an authority the case
  -- can later re-assert — a revoked designee does not keep acting because a case remembers them.
  initiator_designation_id     uuid        not null references public.estate_designations(id),
  initiator_capacity           text        not null
    check (initiator_capacity in ('executor', 'trustee')),
  -- Snapshot of `estates.jurisdiction` at initiation. NULL is a legal, honest value — an estate
  -- with no jurisdiction resolves to the fail-closed maximum requirement, and recording NULL here
  -- says "unknown at initiation" rather than inventing a jurisdiction.
  jurisdiction_context         text,
  -- What the policy engine REQUIRED when the case opened. A record, not the enforcement input —
  -- the decision routine re-derives live. Typed to the same enum as the requirement engine so the
  -- two can never drift vocabularies.
  required_level_at_initiation public.verification_level not null,
  -- What has actually been ATTAINED. NULL = nothing attained — the fail-closed baseline every
  -- comparison must coalesce against. Written by exactly one admin-gated routine; the enum type
  -- makes an out-of-vocabulary level unrepresentable rather than merely refused.
  attained_level               public.verification_level,
  decided_by                   uuid        references auth.users(id),
  decided_at                   timestamptz,
  decision_note                text,
  created_at                   timestamptz not null default now(),
  updated_at                   timestamptz not null default now()
);

-- ★ ONE OPEN CASE PER ESTATE — the claim_packets_one_active_per_estate precedent. Decided cases
-- (verified / rejected / cancelled) are history and coexist; a second OPEN case is a conflict, not
-- a queue.
create unique index if not exists death_verification_cases_one_open_per_estate
  on public.death_verification_cases (estate_id) where status = 'open';
create index if not exists death_verification_cases_estate_idx
  on public.death_verification_cases (estate_id);

alter table public.death_verification_cases enable row level security;
-- ZERO grants, ZERO policies. Unlike `claim_packets` (which the mobile client reads directly under
-- `claim_own_read`), no client surface reads cases in 11-C — so nothing is granted, and an
-- unauthorized viewer cannot learn a case EXISTS, which is itself protected information (T9/H1:
-- whether a death claim is in flight is a fact about a person).

-- The lifecycle FK arrives after the cases table exists (forward reference above).
do $$ begin
  if not exists (
    select 1 from pg_constraint where conname = 'estate_lifecycle_updated_case_id_fkey'
  ) then
    alter table public.estate_lifecycle
      add constraint estate_lifecycle_updated_case_id_fkey
      foreign key (updated_case_id) references public.death_verification_cases(id);
  end if;
end $$;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 3 · EVIDENCE — received, reviewed, never "verified"
-- ────────────────────────────────────────────────────────────────────────────────────────────────
create table if not exists public.death_verification_evidence (
  id            uuid        primary key default gen_random_uuid(),
  case_id       uuid        not null references public.death_verification_cases(id) on delete cascade,
  -- Denormalized estate scope so cross-estate smuggling is refusable without a join, and provable
  -- by constraint in the routines (the attach routine asserts document.estate_id = case.estate_id).
  estate_id     uuid        not null references public.estates(id) on delete cascade,
  -- ★ NO `on delete` CLAUSE — deliberate. `documents` is the single secure store (the Vault); an
  -- evidence pin does not copy bytes, it references them. A vault deletion that would orphan
  -- OPEN-case evidence fails the FK instead of silently un-evidencing a case. (The claim pins chose
  -- `on delete set null` + an explicit `blocked_active_claim` guard inside the delete routine;
  -- giving this FK the same polished sentinel is recorded in the 11-C deferred ledger rather than
  -- edited into `delete_vault_document` here, because that function is deployed and unbundled, and
  -- editing it would open a source↔deployment drift this phase does not need.)
  document_id   uuid        not null references public.documents(id),
  submitted_by  uuid        not null references auth.users(id),
  submitted_at  timestamptz not null default now(),
  -- What the platform actually did with it. 'received' is the entire truth at insert time — no
  -- authenticity vendor exists, and nothing here may claim one does (D1; brief §13).
  review_status text        not null default 'received'
    check (review_status in ('received', 'reviewed_accepted', 'reviewed_rejected')),
  reviewed_by   uuid        references auth.users(id),
  reviewed_at   timestamptz,
  review_note   text
);

create index if not exists death_verification_evidence_case_idx
  on public.death_verification_evidence (case_id);
create index if not exists death_verification_evidence_document_idx
  on public.death_verification_evidence (document_id);

alter table public.death_verification_evidence enable row level security;
-- ZERO grants, ZERO policies — same posture, same reason.

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 4 · PROVE THE FOUNDATION TOOK, IN THE MIGRATION ITSELF
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ BOTH DIRECTIONS, LIKE 0051: the states this phase needs must be admitted, and the states this
-- phase must NOT make storable must be absent from the constraint text. A CHECK that silently
-- failed to apply reads identically from the accepting side.
do $$
declare
  v_def text;
begin
  -- Lifecycle vocabulary: the three foundation states this migration owns must be present.
  --
  -- ★ EDITED IN PHASE 11-E (0052 has never been deployed; the bundles re-apply this file after
  -- 0054). The original check raised if 'released' was storable — correct while 0052 was the last
  -- word on the vocabulary, and WRONG the moment 0054 deliberately widened it: a re-applied bundle
  -- would read the widened CHECK and abort its own idempotent re-paste. The absence pin did not
  -- weaken — it MOVED to where the vocabulary now lives: 0054's self-check pins exactly six states
  -- and refuses invented ones, and the SQL suite enumerates the deployed CHECK on every run.
  select pg_get_constraintdef(con.oid) into v_def
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
   where nsp.nspname = 'public' and rel.relname = 'estate_lifecycle'
     and con.contype = 'c' and pg_get_constraintdef(con.oid) ilike '%state%';
  if v_def is null then
    raise exception '0052 FAILED: estate_lifecycle has no state CHECK';
  end if;
  if position('active' in v_def) = 0
     or position('death_verification_pending' in v_def) = 0
     or position('death_verified' in v_def) = 0 then
    raise exception '0052 FAILED: lifecycle CHECK is missing an 11-C foundation state: %', v_def;
  end if;

  -- Event vocabulary: death only; the fused shape unrepresentable.
  select pg_get_constraintdef(con.oid) into v_def
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
   where nsp.nspname = 'public' and rel.relname = 'death_verification_cases'
     and con.contype = 'c' and pg_get_constraintdef(con.oid) ilike '%event_type%';
  if v_def is null then
    raise exception '0052 FAILED: death_verification_cases has no event_type CHECK';
  end if;
  if position('incapacity' in v_def) > 0 then
    raise exception '0052 FAILED: event_type admits an incapacity value — D9 keeps the events '
      'distinct and the incapacity workflow deferred: %', v_def;
  end if;

  -- Required and attained are BOTH the policy engine's enum — no duplicate ladder, no drift.
  if (select count(*)
        from information_schema.columns
       where table_schema = 'public' and table_name = 'death_verification_cases'
         and column_name in ('required_level_at_initiation', 'attained_level')
         and udt_name = 'verification_level') <> 2 then
    raise exception '0052 FAILED: required/attained levels are not both typed '
      'public.verification_level — a second vocabulary would drift from the policy engine';
  end if;

  -- The attained baseline is fail-closed: no default may exist on the column.
  if (select column_default
        from information_schema.columns
       where table_schema = 'public' and table_name = 'death_verification_cases'
         and column_name = 'attained_level') is not null then
    raise exception '0052 FAILED: attained_level has a DEFAULT — the baseline must be NULL '
      '(nothing attained), not a granted starting level';
  end if;

  -- No client role can touch any of the three tables.
  if exists (
    select 1
      from information_schema.role_table_grants
     where table_schema = 'public'
       and table_name in ('estate_lifecycle', 'death_verification_cases', 'death_verification_evidence')
       and grantee in ('anon', 'authenticated')
  ) then
    raise exception '0052 FAILED: a client role holds a table grant on the death-verification '
      'foundation — these tables are DEFINER-routine-only';
  end if;

  raise notice '0052 · death-verification foundation in place (lifecycle, case, evidence; '
    'released unrepresentable; attained baseline NULL; client roles grant-less)';
end $$;


-- ==== db/migrations/0053_20260812_lifecycle_aware_release_predicate.sql ===========================
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- 0053 · PHASE 11-D — the release predicate becomes lifecycle-aware (one signature, one authority)
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- ★ WHAT THIS PHASE CONNECTS, AND THE ONLY THING IT CONNECTS:
--
--       authoritative estate lifecycle state  (estate_lifecycle, read via estate_lifecycle_state)
--               ↓
--       public.release_condition_satisfied(condition, approved_at, policy, lifecycle_state)
--               ↓
--       existing owner-authored death-conditioned grants may become live
--
-- `after_verified_death` becomes satisfiable — under the `standard` policy only, and only while the
-- estate's authoritative lifecycle is `death_verified`. Nothing else moves:
--
--   · NO grant is created, widened, re-tiered or re-approved. Activation is EVALUATIVE — the same
--     stored row, the same ceiling, the same membership requirements, one predicate answering
--     differently because the lifecycle fact it now consumes has changed.
--   · `legacy_immediate_only` is PRESERVED EXACTLY: the asset-value surfaces still honour
--     `immediately` alone. A death-conditioned asset grant stays dormant on those surfaces.
--     Policy unification remains a deferred product decision (R12), not a side effect.
--   · `after_verified_incapacity` stays dormant (no incapacity workflow exists — R6).
--   · `after_verified_death_or_incapacity` (legacy fused rows) stays dormant and unreinterpreted (R7).
--   · claim approval, evidence receipt, evidence review and attained verification levels satisfy
--     nothing — only the lifecycle record does, and only its one audited writer can move it.
--   · No `released` estate state exists; the 0052 CHECK still cannot store one.
--
-- ★ THE DDL HERE IS ONE DROP. The widened predicate itself lives in
-- `db/functions/release_conditions.sql` (the canonical module) and arrives with the bundle; what a
-- migration must own is the removal of the LIFECYCLE-BLIND overload. `create or replace` cannot
-- replace across a signature change — it would leave both, and Postgres overload resolution would
-- quietly keep serving the 3-argument version to any consumer that was not rewired. A consumer that
-- bypasses the widening must fail LOUDLY at first call, not keep getting yesterday's answer.
--
-- DEPLOYMENT STATE NOTE: the 11-B/11-C bundles are source-merged but not yet pasted, so no deployed
-- database carries the 3-argument predicate; there this drop is a documented no-op. The database it
-- is load-bearing for is any that applied the 11-B artifacts (the SQL harness, a dev paste).
--
-- IDEMPOTENT. Safe to re-apply: `drop function if exists`, and the self-check raises rather than
-- silently no-ops.
--
-- APPLY ORDER: inside `release_conditions_bundle.sql`, after 0051/0052 and immediately before the
-- canonical module that creates the 4-argument predicate. Standing rule unchanged: that bundle is
-- pasted FIRST, before any other bundle re-application.

-- [psql meta-command removed for the SQL editor] \set ON_ERROR_STOP on

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 1 · REMOVE the lifecycle-blind overload, so exactly one authority can exist.
-- ────────────────────────────────────────────────────────────────────────────────────────────────
drop function if exists public.release_condition_satisfied(text, timestamptz, text);

-- ★ PROVE THE REMOVAL TOOK. A drop that silently missed (a renamed schema, an altered signature)
-- would leave two authorities answering the same question, and the un-rewired consumer would keep
-- binding to the blind one — green everywhere, wrong at the first verified death.
do $$
begin
  if to_regprocedure('public.release_condition_satisfied(text, timestamptz, text)') is not null then
    raise exception '0053 FAILED: the 3-argument (lifecycle-blind) release_condition_satisfied still '
      'exists after the drop — two release authorities would coexist and overload resolution would '
      'quietly serve the blind one to any consumer that was not rewired';
  end if;
  raise notice '0053 · lifecycle-blind release predicate removed (the 4-argument authority in '
    'release_conditions.sql is now the only satisfiable spelling)';
end $$;


-- ==== db/migrations/0054_20260812_challenge_window_release_seam.sql ===============================
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- 0054 · PHASE 11-E — the challenge window: the safety seam between death_verified and released
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- ★ WHAT THIS PHASE INSERTS, AND WHY IT EXISTS. 11-D let `after_verified_death` satisfy at
-- `death_verified`. That connected verification directly to irreversible disclosure — and disclosure
-- cannot be undone (R15: revoking future access is possible; undoing disclosure is not). 11-E
-- inserts the missing safety states between them:
--
--     active → death_verification_pending → death_verified
--            → challenge_window            (verification accepted; release deliberately waiting;
--                                           the owner has been notified and can object)
--            → released                    (the ONLY lifecycle at which owner-authored
--                                           death-conditioned grants may evaluate as satisfied)
--     any pre-released death-process state
--            → challenge_halted            (the authenticated owner objected; terminal in 11-E)
--
-- The predicate change rides in `release_conditions.sql`: `after_verified_death` is FALSE at
-- death_verified, FALSE throughout challenge_window, FALSE at challenge_halted, TRUE only at
-- released. So this migration making `released` STORABLE widens no disclosure: the only writer is
-- `release_estate` (client-revoked, no reachable door in 11-E), behind an elapsed, configured,
-- owner-notified, unchallenged window.
--
-- ★ THE WINDOW DURATION IS CONFIGURATION, NOT A GUESS. `release_safety_policy` ships EMPTY: no
-- default duration is seeded, because the duration is a product decision this phase does not own.
-- Fail-closed direction: an estate can always ENTER the challenge window (the owner-safety clock
-- and notice), but with no configured duration the window NEVER ELAPSES and release refuses with
-- `release_window_not_configured`. The duration is re-read LIVE at release time (the H2 precedent:
-- a policy tightened mid-window tightens the window) — never stamped at entry.
--
-- ★ THE OWNER CHALLENGE IS CHEAPER THAN THE CLAIM (R13) AND WINS TIES (R14). No evidence, no
-- review, no waiting period, no designation — one authenticated owner action. The tiebreak is
-- structural: release requires the window STRICTLY elapsed (`now() > notified_at + duration`), so
-- at the exact boundary instant release refuses while challenge still succeeds; both transitions
-- serialize on the lifecycle row lock, and nothing transitions out of challenge_halted.
--
-- IDEMPOTENT. Safe to re-apply. APPLY ORDER: after 0052/0053, inside the bundles that carry it.

-- [psql meta-command removed for the SQL editor] \set ON_ERROR_STOP on

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 1 · WIDEN the lifecycle vocabulary to the six-state safety machine. Additive only.
-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- The constraint name is resolved from the catalog, not guessed (the 0051 lesson).
do $$
declare
  v_name text;
begin
  for v_name in
    select con.conname
      from pg_constraint con
      join pg_class rel on rel.oid = con.conrelid
      join pg_namespace nsp on nsp.oid = rel.relnamespace
     where nsp.nspname = 'public'
       and rel.relname = 'estate_lifecycle'
       and con.contype = 'c'
       and pg_get_constraintdef(con.oid) ilike '%state%'
  loop
    execute format('alter table public.estate_lifecycle drop constraint %I', v_name);
  end loop;

  alter table public.estate_lifecycle
    add constraint estate_lifecycle_state_check
    check (state in (
      'active',
      'death_verification_pending',
      'death_verified',
      -- Phase 11-E: the safety seam. Storable here; REACHABLE only through the closed transition
      -- map in apply_estate_lifecycle_transition, and 'released' only through release_estate.
      'challenge_window',
      'challenge_halted',
      'released'
    ));
end $$;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 2 · THE SAFETY FACTS live on the lifecycle row: when the owner was notified, when the window
--     opened, when it was halted or released, and WHICH notification row is the safety notice.
--     Facts, never authority — release re-derives everything live.
-- ────────────────────────────────────────────────────────────────────────────────────────────────
alter table public.estate_lifecycle add column if not exists owner_notified_at            timestamptz;
alter table public.estate_lifecycle add column if not exists challenge_window_started_at  timestamptz;
alter table public.estate_lifecycle add column if not exists halted_at                    timestamptz;
alter table public.estate_lifecycle add column if not exists released_at                  timestamptz;
alter table public.estate_lifecycle add column if not exists safety_notification_id       uuid;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 3 · A HALTED CASE IS ITS OWN STATUS. The owner challenge halts any open case; 'cancelled' means
--     the initiator withdrew and reusing it would erase the difference between "the claimant
--     changed their mind" and "the owner said they are alive" — facts with different forensics.
-- ────────────────────────────────────────────────────────────────────────────────────────────────
do $$
declare
  v_name text;
begin
  for v_name in
    select con.conname
      from pg_constraint con
      join pg_class rel on rel.oid = con.conrelid
      join pg_namespace nsp on nsp.oid = rel.relnamespace
     where nsp.nspname = 'public'
       and rel.relname = 'death_verification_cases'
       and con.contype = 'c'
       and pg_get_constraintdef(con.oid) ilike '%status%'
       and pg_get_constraintdef(con.oid) not ilike '%event_type%'
       and pg_get_constraintdef(con.oid) not ilike '%review_status%'
       and pg_get_constraintdef(con.oid) not ilike '%initiator_capacity%'
  loop
    execute format('alter table public.death_verification_cases drop constraint %I', v_name);
  end loop;

  alter table public.death_verification_cases
    add constraint death_verification_cases_status_check
    check (status in ('open', 'verified', 'rejected', 'cancelled',
                      -- Phase 11-E: set only by the owner-challenge routine.
                      'halted'));
end $$;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 4 · THE WINDOW-DURATION CONFIGURATION — one row, definer-only, DELIBERATELY UNSEEDED.
-- ────────────────────────────────────────────────────────────────────────────────────────────────
create table if not exists public.release_safety_policy (
  -- Single-row table: the PK admits exactly `true`.
  id               boolean     primary key default true check (id),
  challenge_window interval    not null,
  updated_at       timestamptz not null default now()
);

alter table public.release_safety_policy enable row level security;
-- ZERO grants, ZERO policies — reachable only through the DEFINER reader. No seed row: the
-- duration is a product/operator decision recorded by an explicit, reviewed INSERT, and until it
-- exists the release window cannot elapse anywhere.

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 5 · PROVE THE SEAM TOOK, IN THE MIGRATION ITSELF (both directions, the 0051/0052 discipline).
-- ────────────────────────────────────────────────────────────────────────────────────────────────
do $$
declare
  v_def text;
begin
  select pg_get_constraintdef(con.oid) into v_def
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
   where nsp.nspname = 'public' and rel.relname = 'estate_lifecycle'
     and con.contype = 'c' and pg_get_constraintdef(con.oid) ilike '%state%';
  if v_def is null then
    raise exception '0054 FAILED: estate_lifecycle has no state CHECK after the widening';
  end if;
  if position('challenge_window' in v_def) = 0
     or position('challenge_halted' in v_def) = 0
     or position('released' in v_def) = 0 then
    raise exception '0054 FAILED: the safety vocabulary is incomplete: %', v_def;
  end if;
  if (select count(*) from regexp_matches(v_def, '''[a-z_]+''', 'g')) <> 6 then
    raise exception '0054 FAILED: the lifecycle vocabulary is not exactly six states: %', v_def;
  end if;
  -- 'frozen' and other invented states must still be unrepresentable.
  if position('frozen' in v_def) > 0 then
    raise exception '0054 FAILED: an unapproved lifecycle state is storable: %', v_def;
  end if;

  select pg_get_constraintdef(con.oid) into v_def
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
   where nsp.nspname = 'public' and rel.relname = 'death_verification_cases'
     and con.conname = 'death_verification_cases_status_check';
  if v_def is null or position('halted' in v_def) = 0 then
    raise exception '0054 FAILED: the case status vocabulary did not gain ''halted'': %',
      coalesce(v_def, '<absent>');
  end if;

  -- The policy table is definer-only and EMPTY: a seeded duration would be a product decision
  -- taken by a migration.
  if exists (
    select 1 from information_schema.role_table_grants
     where table_schema = 'public' and table_name = 'release_safety_policy'
       and grantee in ('anon', 'authenticated')
  ) then
    raise exception '0054 FAILED: a client role holds a grant on release_safety_policy';
  end if;
  if (select count(*) from public.release_safety_policy) <> 0 then
    -- On RE-application to a database whose operator later configured the window, a row is
    -- legitimate — the check refuses only a duration arriving in the SAME transaction that
    -- created the table (i.e. seeded by migration).
    if (select min(updated_at) from public.release_safety_policy) >= transaction_timestamp() then
      raise exception '0054 FAILED: release_safety_policy was seeded by this migration — the '
        'window duration is a product decision, not a default';
    end if;
  end if;

  raise notice '0054 · challenge-window seam in place (6 lifecycle states; halted case status; '
    'safety facts columns; duration configuration table EMPTY and definer-only)';
end $$;


-- ==== db/migrations/0055_20260812_release_authorization.sql =======================================
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- 0055 · PHASE 11-F — owner-liveness delivery, the two-person release rule, and the release record
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- ★ WHAT THE FIVE APPROVED DECISIONS CHANGE, AND WHY EACH NEEDS SCHEMA.
--
-- D1 · TWO-PERSON RULE. The operator who verifies a death may not be the operator who authorizes
--      release, and that is enforced in the DATABASE, not in a console. `release_authorizations`
--      records both reviewers as first-class columns with a CHECK that they differ — so the rule
--      survives a UI rewrite, a direct RPC call, and a future admin tool nobody has written yet.
--
-- D2 · THE CLOCK STARTS AT DISPATCH, NOT AT VERIFICATION. A seventh lifecycle state
--      (`owner_notification_dispatched`) sits between `death_verified` and `challenge_window`
--      precisely so "we accepted the death" and "we told the owner" cannot be the same fact. The
--      duration is 7 x 24h — now an approved decision, so 0055 SEEDS it (0054 deliberately did not,
--      because in 11-E it was not yet decided).
--
-- D4 · IN-APP ALONE IS INSUFFICIENT. `owner_notice_outbox` is the independently-reachable channel:
--      an email row committed in the same transaction as the dispatch transition. The requirement is
--      DISPATCH INITIATION — the row exists and is addressed — never a read receipt, an open, or an
--      acknowledgement, none of which the product can honestly observe.
--
-- ★ WHAT THIS MIGRATION STILL CANNOT DO. It creates no grant, tier, membership or designation, and
-- it makes `released` no easier to reach: the route is still `challenge_window -> released` alone,
-- now additionally gated on two distinct reviewers and a dispatched notice (D5).
--
-- IDEMPOTENT. Safe to re-apply. APPLY ORDER: after 0054, inside the bundles that carry it.

-- [psql meta-command removed for the SQL editor] \set ON_ERROR_STOP on

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 1 · THE SEVENTH LIFECYCLE STATE — "we told the owner" is its own fact
-- ────────────────────────────────────────────────────────────────────────────────────────────────
do $$
declare v_name text;
begin
  for v_name in
    select con.conname
      from pg_constraint con
      join pg_class rel on rel.oid = con.conrelid
      join pg_namespace nsp on nsp.oid = rel.relnamespace
     where nsp.nspname = 'public' and rel.relname = 'estate_lifecycle'
       and con.contype = 'c' and pg_get_constraintdef(con.oid) ilike '%state%'
  loop
    execute format('alter table public.estate_lifecycle drop constraint %I', v_name);
  end loop;

  alter table public.estate_lifecycle
    add constraint estate_lifecycle_state_check
    check (state in (
      'active',
      'death_verification_pending',
      'death_verified',
      -- Phase 11-F (D2): the owner has been told, and the challenge clock has started.
      'owner_notification_dispatched',
      'challenge_window',
      'challenge_halted',
      'released'
    ));
end $$;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 2 · THE OWNER NOTICE OUTBOX — the independently reachable channel (D4)
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ A SEPARATE TABLE FROM `invitation_delivery_outbox`, DELIBERATELY. That outbox is FK-bound to an
-- invitation and drained by a daily cron whose claim predicate has no age bound — the right class
-- for an invitation email and the wrong one for the notice that starts a release clock. Sharing it
-- would silently inherit both properties.
--
-- ★ THE RECIPIENT IS RESOLVED AND STORED AT DISPATCH. Storing the address is what makes
-- "independently reachable" a checkable fact rather than an assumption: a dispatch with no
-- resolvable address must FAIL, not queue a row nobody can deliver.
create table if not exists public.owner_notice_outbox (
  id            uuid        primary key default gen_random_uuid(),
  estate_id     uuid        not null references public.estates(id) on delete cascade,
  user_id       uuid        not null references auth.users(id),
  -- Email is the minimum bar (D4). Push, when it exists, is SUPPLEMENTAL and joins this CHECK by a
  -- reviewed migration — it never replaces the email row.
  channel       text        not null default 'email' check (channel in ('email')),
  recipient     text        not null,
  notice_kind   text        not null check (notice_kind in ('death_process.window_opened')),
  status        text        not null default 'queued'
    check (status in ('queued', 'processing', 'dispatched', 'failedPermanent', 'cancelled')),
  requested_at  timestamptz not null default now(),
  dispatched_at timestamptz,
  attempts      int         not null default 0,
  next_attempt_at timestamptz,
  failure_class text,
  purge_audit_id uuid
);

create index if not exists owner_notice_outbox_estate_idx on public.owner_notice_outbox (estate_id);
create index if not exists owner_notice_outbox_claimable_idx
  on public.owner_notice_outbox (requested_at) where status in ('queued', 'processing');

alter table public.owner_notice_outbox enable row level security;
-- ZERO grants, ZERO policies: a row here names a living owner's email address and the fact that a
-- death process is running against their estate. Only DEFINER routines may touch it.

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 3 · THE RELEASE AUTHORIZATION RECORD — its own model, never overloaded (Stage 5)
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ NOT A CLAIM PACKET, NOT A MEMBERSHIP, NOT A DESIGNATION. Each of those answers a different
-- question with a different actor, evidence and reversibility; overloading one of them to carry
-- "two operators authorized this release" is how a fact acquires the wrong lifecycle. This table
-- exists so the release event has a home with exactly the fields the audit needs.
--
-- ★ THE TWO-PERSON RULE IS A TABLE CONSTRAINT (D1). Not a trigger, not a routine-only check: a CHECK
-- means no INSERT anywhere — routine, migration, console, future admin tool — can record a release
-- authorized by one person. The routine enforces it too; this is the layer that cannot be bypassed.
create table if not exists public.release_authorizations (
  id            uuid        primary key default gen_random_uuid(),
  estate_id     uuid        not null references public.estates(id) on delete cascade,
  case_id       uuid        not null references public.death_verification_cases(id),
  -- reviewer_a VERIFIED THE DEATH. reviewer_b AUTHORIZED THE RELEASE. They must differ.
  reviewer_a    uuid        not null references auth.users(id),
  reviewer_b    uuid        not null references auth.users(id),
  verified_at   timestamptz not null,
  authorized_at timestamptz not null default now(),
  released_at   timestamptz,
  audit_reason  text        not null,
  constraint release_authorizations_two_person check (reviewer_a <> reviewer_b)
);

-- One authorization per estate: release is not a thing that happens twice.
create unique index if not exists release_authorizations_one_per_estate
  on public.release_authorizations (estate_id);

alter table public.release_authorizations enable row level security;
-- ZERO grants, ZERO policies — DEFINER-routine-only, like every other record on this path.

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 4 · THE PURGE AUDIT — nothing is ever silently deleted (Stage 3)
-- ────────────────────────────────────────────────────────────────────────────────────────────────
create table if not exists public.outbox_purge_audit (
  id            uuid        primary key default gen_random_uuid(),
  outbox_name   text        not null,
  purged_at     timestamptz not null default now(),
  actor_id      uuid,
  row_count     int         not null,
  oldest_row_at timestamptz,
  newest_row_at timestamptz,
  reason        text        not null
);
alter table public.outbox_purge_audit enable row level security;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 5 · THE CHALLENGE WINDOW DURATION — 7 x 24h, now an APPROVED decision (D2)
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ 0054 DELIBERATELY SEEDED NOTHING, AND THAT WAS RIGHT THEN. In 11-E the duration was undecided,
-- so the fail-closed posture was "no window can ever elapse". D2 decides it, so it is recorded here
-- — in a migration, reviewably, once — rather than left to an operator's console session where
-- nobody could later say what value production carries or when it changed.
--
-- `on conflict do update` is deliberate: re-applying this migration re-asserts the approved value,
-- so a hand-edited production row is corrected by the next paste rather than silently kept.
insert into public.release_safety_policy (id, challenge_window)
values (true, interval '7 days')
on conflict (id) do update set challenge_window = excluded.challenge_window, updated_at = now();

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 6 · REMOVE the one-person release lever
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ THE 0053 PRECEDENT, APPLIED TO AN ACTOR RATHER THAN AN ARGUMENT. 11-E's `release_estate(uuid)`
-- had no concept of a second reviewer. Leaving it in place beside the two-person door would be a
-- second release path that bypasses D1 entirely — and `create or replace` cannot remove it, because
-- the replacement has a different name and signature. It is DROPPED, so a caller that was never
-- rewired fails loudly instead of releasing on one person's say-so.
drop function if exists public.release_estate(uuid);

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 7 · PROVE IT TOOK, IN THE MIGRATION ITSELF (both directions)
-- ────────────────────────────────────────────────────────────────────────────────────────────────
do $$
declare v_def text; v_n int;
begin
  select pg_get_constraintdef(con.oid) into v_def
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
   where nsp.nspname = 'public' and rel.relname = 'estate_lifecycle'
     and con.contype = 'c' and pg_get_constraintdef(con.oid) ilike '%state%';
  if v_def is null or position('owner_notification_dispatched' in v_def) = 0 then
    raise exception '0055 FAILED: the dispatch state is not storable: %', coalesce(v_def, '<absent>');
  end if;
  if (select count(*) from regexp_matches(v_def, '''[a-z_]+''', 'g')) <> 7 then
    raise exception '0055 FAILED: the lifecycle vocabulary is not exactly seven states: %', v_def;
  end if;

  -- The two-person CHECK must exist as a CONSTRAINT, not merely as routine logic.
  if not exists (
    select 1 from pg_constraint where conname = 'release_authorizations_two_person'
  ) then
    raise exception '0055 FAILED: the two-person rule is not a table constraint — routine-only '
      'enforcement can be bypassed by any other writer';
  end if;
  -- …and it must actually refuse. Proven, not assumed.
  begin
    insert into public.release_authorizations
      (estate_id, case_id, reviewer_a, reviewer_b, verified_at, audit_reason)
    select e.id, c.id, c.initiated_by, c.initiated_by, now(), '0055 self-check'
      from public.estates e join public.death_verification_cases c on c.estate_id = e.id limit 1;
    -- If a row existed to try with AND the insert succeeded, the constraint is not working.
    get diagnostics v_n = row_count;
    if v_n > 0 then
      raise exception '0055 FAILED: a single-reviewer release authorization was insertable';
    end if;
  exception when check_violation then
    null; -- the constraint refused, which is the point
  end;

  -- ★ THE TABLE, NOT THE READER. `challenge_window_duration()` lives in `release_safety.sql`, which
  -- ships in a LATER bundle — so a migration that asked the function would raise on the first paste
  -- of the release-conditions bundle, where 0055 legitimately runs before that function exists. A
  -- migration must be checkable against the schema it changed, not against a function some other
  -- artifact happens to carry.
  if (select p.challenge_window from public.release_safety_policy p where p.id)
     is distinct from interval '7 days' then
    raise exception '0055 FAILED: the challenge window is % (expected 7 days per D2)',
      (select p.challenge_window from public.release_safety_policy p where p.id);
  end if;

  if to_regprocedure('public.release_estate(uuid)') is not null then
    raise exception '0055 FAILED: the one-person release lever still exists — D1 would be bypassable';
  end if;

  if exists (
    select 1 from information_schema.role_table_grants
     where table_schema = 'public'
       and table_name in ('owner_notice_outbox', 'release_authorizations', 'outbox_purge_audit')
       and grantee in ('anon', 'authenticated')
  ) then
    raise exception '0055 FAILED: a client role holds a grant on a release-path table';
  end if;

  raise notice '0055 · release authorization in place (7 lifecycle states; owner notice outbox; '
    'two-person CHECK enforced; window = 7 days; one-person lever dropped)';
end $$;


-- ==== db/functions/release_conditions.sql =========================================================
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- THE CANONICAL RELEASE-CONDITION AUTHORITY  ·  Phase 11-B, lifecycle-aware since Phase 11-D
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- ★ WHY THIS FILE EXISTS. Before Phase 11-B the rule "is this grant's release condition satisfied?"
-- was written out SEVEN times in FIVE routines, and the seven copies gave TWO different answers:
--
--     can_access_document          immediately + the two approval conditions once approved
--     inventory_disclosure_tier    same
--     notification_grant_is_live   same
--     asset_grant_tier             immediately ONLY
--     list_estate_assets           immediately ONLY
--     get_estate_net_worth  (×2)   immediately ONLY
--
-- Phase 11 connects a verified death to disclosure. The single most likely way to get that wrong is
-- not a missing check — it is activating a condition at four sites and forgetting the other three,
-- which is precisely the shape of the four role maps that drifted apart in Phase 9. So the predicate
-- moved HERE first (11-B), before any death wiring existed, and every consumer became a caller.
--
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- ★ WHAT THIS MODULE DECIDES, AND WHAT IT DELIBERATELY DOES NOT
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- It answers ONE question: given a release condition, the approval fact recorded beside it, and the
-- estate's authoritative lifecycle state, is that condition presently SATISFIED?
--
-- It does NOT decide who may receive a grant, compute a disclosure tier, manufacture a grant, verify
-- a death, approve a claim, or transition any lifecycle state. Callers keep every one of those. A
-- grant whose condition is satisfied still discloses nothing unless the SAME checks that have always
-- guarded it also pass: active status, the viewer's own grant row, the read-time ceiling clamp, the
-- hidden-tier refusal. Satisfaction is one conjunct, never a bypass.
--
-- ★ IT TAKES LIFECYCLE STATE AS AN ARGUMENT, AND READS NOTHING — THAT IS THE 11-D DESIGN.
--
-- 11-B deliberately gave this function no lifecycle argument, so that "no authorization path
-- consults the release seam" stayed structurally true while there was no verified event to consult.
-- 11-D is the phase that spends that guarantee, deliberately, in ONE file: the signature widens to
--
--     release_condition_satisfied(condition, approved_at, policy, lifecycle_state)
--
-- and every consumer resolves the lifecycle through `public.estate_lifecycle_state(estate)` — the
-- authoritative reader over `estate_lifecycle`, the record whose ONLY writer is the audited
-- transition routine. The predicate itself stays a PURE function of its arguments (immutable, no
-- table reads), for three reasons:
--
--   · a pure predicate can be truth-tabled exhaustively against a written specification, which is
--     how the SQL suite proves it (every condition × approval × policy × lifecycle, enumerated);
--   · a predicate that resolved estate → lifecycle itself would be a client-reachable death-status
--     oracle for arbitrary estate ids (it is EXECUTEable by `authenticated`; the reader is not);
--   · the lifecycle READ stays in SECURITY DEFINER consumers beside the grant lookup it scopes, so
--     the estate whose lifecycle is consulted is by construction the estate whose grant is evaluated.
--
-- What no consumer may do is compare the lifecycle locally ("if death_verified then …") — that is
-- release policy leaking back out of the centre, and `test/deathVerificationFoundation.test.ts`
-- pins that the reader appears outside the death module ONLY as this function's fourth argument.
--
-- ★ NOT `claim_packets.status`. NOT evidence rows. NOT attained verification levels. NOT the
-- label-only `estate_release_state()` claim projection. The lifecycle record is the one fact that
-- can satisfy a death condition, and it moves only through `apply_estate_lifecycle_transition`,
-- behind an admin decision that re-derives the required verification level LIVE (H2).
--
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- ★ TWO POLICIES, STILL — 11-D activates death under `standard` and PRESERVES the legacy clamp
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- `standard` (documents, the estate-documents category, estate inventory, notification speech):
-- gains the death arm. `after_verified_death` is satisfied exactly while the lifecycle is
-- `death_verified`.
--
-- `legacy_immediate_only` (account balances, institution names, total asset value, linked account
-- details): carried forward EXACTLY as written — `immediately` alone, lifecycle-indifferent. A
-- death-conditioned grant on an asset-value surface therefore stays dormant even at death_verified.
-- That asymmetry is deliberate and is pinned by test in both directions: unifying the policies
-- changes what a survivor sees on the asset surfaces, which is a product decision with its own row
-- inventory and migration price (R12), not a tidy-up. The divergence remains one `case` arm in one
-- file instead of seven scattered literals.
--
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- ★ FAIL-CLOSED IN EVERY ARGUMENT
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- An unknown condition is false. An unknown policy is false. An unknown or NULL lifecycle state is
-- false — for EVERY condition, including `immediately`: the authoritative reader can only produce
-- the three CHECK-constrained states, so an out-of-vocabulary lifecycle here means a consumer wired
-- something that is not the seam, and the answer to a miswired consumer is refusal, not tolerance.
-- NULL condition and NULL policy are false. There is no permissive default and no `else true`
-- anywhere below.
--
-- The `coalesce` is load-bearing rather than defensive tidiness: `null = 'immediately'` is NULL, not
-- false, and a boolean gate that returns NULL is not refused by `if not (…) then` — that branch
-- simply does not execute, and the caller carries on as though the check had passed. A three-valued
-- answer from a two-valued gate is how a fail-closed predicate fails open.

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- release_condition_satisfied(condition, approved_at, policy, lifecycle_state) — THE AUTHORITY
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- `p_policy` has NO DEFAULT, on purpose. A default would let a new consumer inherit the wider rule by
-- saying nothing, which is the exact failure mode — silent policy by omission — that the seven
-- scattered copies represented. `p_lifecycle_state` has no default for the same reason: a consumer
-- that says nothing about the lifecycle must not silently evaluate "as if active"; it must not
-- compile. (The 3-argument spelling is DROPPED by migration 0053, so an un-rewired caller fails
-- loudly at first call rather than binding to a lifecycle-blind overload.)
create or replace function public.release_condition_satisfied(
  p_release_condition text,
  p_approved_at       timestamptz,
  p_policy            text,
  p_lifecycle_state   text
)
 returns boolean
 language sql
 immutable
 set search_path to 'public'
as $function$
  select coalesce(
    -- ★ THE LIFECYCLE VALIDITY GATE COMES FIRST and refuses EVERYTHING on an out-of-vocabulary
    -- state. The set is the deployed CHECK's (0052 widened by 0054), spelled here because a pure
    -- function cannot read the catalog; `db/tests/release_condition_authorization.sql` enumerates
    -- the CHECK at run time and fails if the two vocabularies ever drift.
    -- ★ THE GATE MUST NAME EVERY STORABLE STATE, INCLUDING ONES THAT SATISFY NOTHING. A state
    -- missing here refuses EVERY condition for that estate — including `immediately` — so an
    -- owner's ordinary live grants would go dark the moment a death process reached the unlisted
    -- state. Failing closed on an UNKNOWN state is the design; failing closed on a KNOWN one is a
    -- disclosure outage. 11-F's `owner_notification_dispatched` joins the list for that reason and
    -- for no other: it satisfies nothing, exactly like the two states either side of it.
    p_lifecycle_state in ('active', 'death_verification_pending', 'death_verified',
                          'owner_notification_dispatched',
                          'challenge_window', 'challenge_halted', 'released')
    and case p_policy
      -- Documents, the estate-documents category, estate inventory, and notification speech.
      -- `after_owner_approval` (owner-initiated) and `after_access_request_approval`
      -- (beneficiary-initiated) are the SAME gate — both mean "the owner approved this access",
      -- differing only by who asked.
      when 'standard' then
        p_release_condition = 'immediately'
        or (p_release_condition in ('after_owner_approval', 'after_access_request_approval')
            and p_approved_at is not null)
        -- ★ THE DEATH ARM — RE-POINTED IN PHASE 11-E (R7). 11-D satisfied this at death_verified;
        -- that connected an accepted verification DIRECTLY to irreversible disclosure, and 11-E
        -- inserts the safety seam: the condition is satisfied ONLY at `released`, which is
        -- reachable only through the challenge window — owner notified in the same transaction,
        -- configured duration strictly elapsed, no owner challenge. death_verified satisfies
        -- NOTHING; challenge_window satisfies NOTHING; challenge_halted satisfies NOTHING.
        -- Claim approval, evidence, and attained levels never appear here because they cannot
        -- move the lifecycle. Incapacity and the legacy fused value stay out of this arm
        -- entirely — dormant under every policy, every lifecycle (R8/R9).
        or (p_release_condition = 'after_verified_death'
            and p_lifecycle_state = 'released')

      -- The asset-value surfaces (account balances, institution names, total asset value, linked
      -- account details). Carried forward EXACTLY as written in 11-B, including their narrowness
      -- and their lifecycle-indifference: `immediately` alone, at every lifecycle state. This is a
      -- compatibility clamp with a standing ledger entry (R12), not a rule anyone designed — and
      -- 11-D deliberately does NOT spend that product decision.
      when 'legacy_immediate_only' then
        p_release_condition = 'immediately'

      -- Unknown policy -> refused. No `else true`, ever.
      else false
    end,
    false);
$function$;

comment on function public.release_condition_satisfied(text, timestamptz, text, text) is
  'THE canonical release-condition authority (Phase 11-B; lifecycle-aware since 11-D; safety-seamed '
  'in 11-E). Answers only "is this condition presently satisfied", never who may receive a grant, '
  'what tier they get, or whether anyone has died. PURE: the lifecycle arrives as an argument, '
  'resolved by SECURITY DEFINER consumers through public.estate_lifecycle_state — never from claim '
  'status, evidence, or attained levels. after_verified_death is satisfied only under the standard '
  'policy at RELEASED (R7) — death_verified, challenge_window and challenge_halted all satisfy '
  'nothing; incapacity, the legacy fused value, identity and claim conditions are dormant under '
  'every policy. Unknown condition, unknown policy, unknown lifecycle and NULL all refuse.';

revoke execute on function public.release_condition_satisfied(text, timestamptz, text, text) from public, anon;
grant  execute on function public.release_condition_satisfied(text, timestamptz, text, text) to authenticated;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- release_condition_writable(condition) -> boolean   — THE WRITE-TIME VOCABULARY GATE
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ THE DEATH/INCAPACITY SPLIT LIVES HERE, AND IT IS A WRITE-SIDE RULE ONLY.
--
-- `after_verified_death_or_incapacity` fused two legally distinct events into one storable value.
-- Death and incapacity differ in who is alive to contest, what evidence exists, whether the owner's
-- own instructions still govern, and whether the change is reversible. A single condition cannot
-- carry both and mean anything.
--
-- The split is done WITHOUT touching stored rows:
--
--   · the table CHECK still ACCEPTS the fused value, so every existing row remains readable and no
--     migration has to guess what an owner meant when they chose it;
--   · this gate REFUSES it for new writes, so no further row can be created carrying the ambiguity;
--   · the satisfied-predicate above treats it as dormant — exactly as it was before — so a legacy
--     row is no more permissive than it was yesterday and no less.
--
-- ★ THE LEGACY VALUE IS NOT REINTERPRETED, AND 11-D DID NOT CHANGE THAT. Now that a verified death
-- can activate `after_verified_death`, the pull to "complete the migration" by mapping fused rows
-- onto the death condition is stronger than ever — and it is still a guess about owner intent that
-- silently makes a stored grant activate on an event the owner may never have chosen alone. Mapping
-- them to `after_verified_incapacity` is the same guess pointing the other way. Both are product
-- decisions about somebody else's estate. An explicit unsatisfiable legacy state costs a
-- re-authoring; a wrong guess costs a disclosure that cannot be undone.
--
-- ★ WRITABLE IS NOT LIVE. `after_verified_death` being writable (11-B) and satisfiable (11-D) are
-- separate facts; `after_verified_incapacity` remains writable and satisfied by NOTHING — nothing
-- verifies an incapacity, and the predicate admits it under no policy. This gate widens what an
-- owner may EXPRESS, never what anybody may SEE.
create or replace function public.release_condition_writable(p_release_condition text)
 returns boolean
 language sql
 immutable
 set search_path to 'public'
as $function$
  select coalesce(p_release_condition in (
    'never',
    'immediately',
    'after_owner_approval',
    'after_identity_verification',
    'after_access_request_approval',
    -- Phase 11-B: the split. Storable and expressible; death satisfiable only since 11-D and only
    -- at death_verified under the standard policy; incapacity satisfied by nothing.
    'after_verified_death',
    'after_verified_incapacity',
    'after_claim_case_approval'
    -- 'after_verified_death_or_incapacity' is DELIBERATELY ABSENT — readable, never writable again.
  ), false);
$function$;

comment on function public.release_condition_writable(text) is
  'Write-time vocabulary gate for access_grants.release_condition (Phase 11-B). Accepts the split '
  'after_verified_death / after_verified_incapacity and REFUSES the deprecated fused '
  'after_verified_death_or_incapacity, which remains legal in the CHECK so stored rows stay readable '
  'and unreinterpreted. Writable is not live: incapacity is satisfied by no policy, and death only '
  'by the authoritative death_verified lifecycle under the standard policy (11-D).';

revoke execute on function public.release_condition_writable(text) from public, anon;
grant  execute on function public.release_condition_writable(text) to authenticated;


-- ==== db/functions/estate_lifecycle_state.sql =====================================================
-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- estate_lifecycle_state(p_estate) → text            [INTERNAL — the authoritative lifecycle read]
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ EXTRACTED FROM `death_verification.sql` IN PHASE 11-D, because the seam changed sides. In 11-C
-- this reader existed for the death-verification routines and was consulted by nobody else — that
-- absence was the firewall. In 11-D the canonical release predicate consumes lifecycle state as an
-- argument, so every disclosure evaluator resolves it at read time. The reader therefore ships in
-- `release_conditions_bundle.sql` (the FIRST artifact an operator pastes), so that no paste order
-- ever leaves a consumer referencing a reader that does not exist yet. The death-verification
-- bundle also carries it (idempotent re-create), keeping that artifact single-paste runnable.
--
-- ★ ABSENT ROW = 'active'. An estate that has never seen a death-verification case has no row in
-- `estate_lifecycle`, and this reader answers the base state. The empty table is a correct table.
--
-- ★ THE CLOSED SET IS THE TABLE'S, NOT THIS FUNCTION'S. The CHECK on `estate_lifecycle.state`
-- (migration 0052) admits exactly 'active' / 'death_verification_pending' / 'death_verified', and
-- the canonical predicate REFUSES any lifecycle value outside that set — so a state this reader
-- could never produce fails closed at the predicate rather than being interpreted.
--
-- ★ NO CLIENT MAY EXECUTE THIS. A client that can map estate → lifecycle state has been handed a
-- death-status oracle for arbitrary estates. Its callers are SECURITY DEFINER routines (the
-- death-verification module and the disclosure evaluators) and the SQL suite. The disclosure rule
-- for consumers is pinned by `test/deathVerificationFoundation.test.ts`: outside the death module,
-- this function may appear ONLY as the lifecycle argument of `public.release_condition_satisfied` —
-- never as the subject of a local comparison, which would be release policy leaking out of the
-- canonical predicate one `if` at a time.
create or replace function public.estate_lifecycle_state(p_estate uuid)
 returns text
 language sql
 security definer
 stable
 set search_path to 'public'
as $function$
  select coalesce(
    (select l.state from public.estate_lifecycle l where l.estate_id = p_estate),
    'active');
$function$;
revoke execute on function public.estate_lifecycle_state(uuid) from public, anon, authenticated;

comment on function public.estate_lifecycle_state(uuid) is
  'THE authoritative estate lifecycle read (Phase 11-C, extracted 11-D). Absent row = active. '
  'INTERNAL: execute revoked from every client role — a client that can map estate to lifecycle '
  'state holds a death-status oracle. Consumed by the death-verification routines and, since 11-D, '
  'as the lifecycle argument to public.release_condition_satisfied inside disclosure evaluators. '
  'Never derived from claim_packets.status, evidence, or attained verification levels.';


-- ==== db/functions/document_grantable.sql =========================================================
-- public.document_grantable(p_role text, p_sensitivity text) -> boolean
--
-- THE DOCUMENT DISCLOSURE CEILING. What a grantee role may be shown at a given document
-- sensitivity, regardless of what tier a grant happens to name. `can_access_document` re-checks it
-- at READ time against the document's CURRENT sensitivity, so reclassifying a document to `sealed`
-- takes effect immediately rather than only for grants issued afterwards.
--
-- ★ EXTRACTED TO A SOURCE FILE IN PHASE 11-B, AND IT HAD BEEN A SHADOW COPY UNTIL THEN.
--
-- Its only definition was inside `db/migrations/0002_20260620_access_grants.sql`, and
-- `db/tests/preamble_real_auth.sql` carried a hand-written copy so the SQL suite could stand the
-- schema up. `verifySqlAuthorization.mjs` refuses to run when the preamble shadows a production
-- body — but it resolved "production body" by searching `db/functions/` alone, so a function whose
-- source of truth lived in a migration was invisible to the guard. The ceiling, the document gate
-- and the asset ceiling all sat in that blind spot, unaudited, for their entire lives.
--
-- They happened to agree. Nothing would have said so if they had not — which is the same near-miss
-- as `asset_bracket_low`/`asset_bracket_high` in Phase 10-F, one directory over.
--
-- The body below is byte-identical to 0002's. Extraction is what makes it comparable, not a rewrite.
--
-- Unknown sensitivity denies. Source of truth — re-apply on DB reset.

create or replace function public.document_grantable(p_role text, p_sensitivity text)
returns boolean
language sql
immutable
as $$
  select case
    when p_sensitivity = 'sealed'     then false
    when p_sensitivity = 'restricted' then p_role = 'professional_delegate'
    when p_sensitivity in ('low','medium','high')
                                      then p_role in ('beneficiary','professional_delegate')
    else false                                   -- unknown sensitivity -> deny
  end;
$$;


-- ==== db/functions/can_access_document.sql ========================================================
-- public.can_access_document(p_document_id uuid) -> boolean
--
-- THE DOCUMENT AUTHORIZATION GATE. Consulted by the `documents` RLS read policy and by
-- `get_professional_workspace`; it is the only thing standing between a non-owner and a document row.
--
-- ★ EXTRACTED TO A SOURCE FILE IN PHASE 11-B. Until then its definition lived in
-- `db/migrations/0004_20260624_access_requests.sql` (re-declared from 0003, itself from 0002), with a
-- hand-written copy in `db/tests/preamble_real_auth.sql` that the harness's own anti-shadow guard
-- could not see — the guard searched `db/functions/` for a production counterpart and found none, so
-- it classified the estate's document gate as "a pure harness fixture" and skipped it. The copy
-- happened to match 0004. It is now comparable rather than lucky.
--
-- ★ THE RELEASE RULE IS NO LONGER WRITTEN HERE (Phase 11-B). It was one of seven copies; it is now
-- one call to `public.release_condition_satisfied`. The `'standard'` policy is the same rule this
-- function has carried since 0004 — `immediately`, plus the two approval-based conditions once
-- `approved_at` is set — and the SQL suite compares the predicate's full truth table rather than
-- taking that claim on trust.
--
-- Ladder, unchanged: owner inherent → per-document grant → `estate_documents` category fallback →
-- default-deny → ceiling re-check against CURRENT sensitivity → hidden tier → release condition.
--
-- SECURITY DEFINER; relies on auth.uid(). The DEFINER context is what lets the policy call it
-- without recursing through `documents`' own RLS. Source of truth — re-apply on DB reset.

create or replace function public.can_access_document(p_document_id uuid)
returns boolean
language plpgsql
security definer
stable
set search_path to 'public'
as $$
declare
  v_uid    uuid := auth.uid();
  v_estate uuid;
  v_sens   text;
  g        record;
begin
  if v_uid is null then
    return false;
  end if;

  select estate_id, sensitivity into v_estate, v_sens
  from public.documents
  where id = p_document_id;

  if v_estate is null then
    return false;
  end if;

  -- Owner inherent (A.1) — no grant row needed.
  if public.is_estate_owner(v_estate) then
    return true;
  end if;

  -- Non-owner: per-document grant first...
  select grantee_role, visibility_tier, release_condition, approved_at
    into g
  from public.access_grants
  where estate_id = v_estate
    and grantee_user_id = v_uid
    and status = 'active'
    and document_id = p_document_id
  limit 1;

  -- ...then category 'estate_documents' fallback (the access-request grant lands here).
  if not found then
    select grantee_role, visibility_tier, release_condition, approved_at
      into g
    from public.access_grants
    where estate_id = v_estate
      and grantee_user_id = v_uid
      and status = 'active'
      and category = 'estate_documents'
    limit 1;
  end if;

  if not found then
    return false;                                            -- default-deny (A.5)
  end if;

  -- Ceiling re-check against the document's CURRENT sensitivity (A.3). For a CATEGORY
  -- grant this is the ONLY ceiling enforcement (the write-time trigger no-ops on category
  -- grants), so a sealed/restricted doc stays hidden here even with the category grant.
  if not public.document_grantable(g.grantee_role, v_sens) then
    return false;
  end if;

  if g.visibility_tier = 'hidden' then
    return false;
  end if;

  -- ★ THE CANONICAL RELEASE PREDICATE (Phase 11-B) — was seven scattered copies, now one call.
  -- Since 11-D it consumes the AUTHORITATIVE lifecycle for THIS document's estate, resolved through
  -- the one sanctioned reader: `after_verified_death` opens exactly while the estate is
  -- death_verified. 'never', incapacity, the legacy fused value, identity and claim conditions stay
  -- dormant-deny (A.4), and an unknown condition or lifecycle refuses. No comparison happens here —
  -- the lifecycle is an ARGUMENT, and the policy stays in the predicate.
  return public.release_condition_satisfied(
    g.release_condition, g.approved_at, 'standard', public.estate_lifecycle_state(v_estate));
end;
$$;

commit;
-- ★ If you see an error above and no COMMIT, nothing was applied. Fix the cause and paste again.
