-- GENERATED by scripts/buildReleaseConditionBundle.mjs — DO NOT EDIT.
-- Edit the sources instead:
--   db/migrations/0051_20260812_release_condition_engine.sql
--   db/functions/release_conditions.sql
--   db/functions/document_grantable.sql
--   db/functions/can_access_document.sql
--
-- Paste this whole file into the Supabase SQL editor and run it once.
-- The migration is idempotent and every function is CREATE OR REPLACE, so re-running is safe.

-- ==== db/migrations/0051_20260812_release_condition_engine.sql ====================================
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- 0051 · PHASE 11-B — the canonical release-condition engine, and the death/incapacity split
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- ★ THIS MIGRATION CHANGES NO DISCLOSURE. Every read path answers exactly what it answered before,
-- for every stored row, and the SQL suite compares the full input space to prove it rather than
-- asserting it. What changes is WHERE the answer is decided.
--
-- Two things happen here:
--
--   1 · The release rule — written out seven times across five routines, giving two different
--       answers — moves into `public.release_condition_satisfied`, and every evaluator becomes a
--       caller. Phase 11 activates a death condition; doing that with seven copies is how the four
--       role maps drifted apart in Phase 9.
--
--   2 · `after_verified_death_or_incapacity` is split into `after_verified_death` and
--       `after_verified_incapacity`. The CHECK is WIDENED to admit both while keeping the fused
--       value legal, so no stored row is rewritten, reinterpreted or invalidated. The RPC write gate
--       (`release_condition_writable`) refuses the fused value for new rows.
--
-- ★ WHY THE OLD VALUE STAYS LEGAL. Deciding that a fused row "really meant death" is a product
-- decision about somebody else's estate, and it points at a disclosure that cannot be undone.
-- Deciding it meant incapacity is the same guess reversed. An unsatisfiable legacy state costs an
-- owner one re-authoring; a wrong guess costs a survivor's privacy. No row becomes more permissive:
-- the fused value was dormant before this migration and is dormant after it.
--
-- ★ NOTHING HERE VERIFIES A DEATH OR RELEASES ANYTHING. `after_verified_death` is storable and
-- satisfied by nothing. There is still no routine that writes a released state, and no read path
-- consults the release seam. This migration makes the eventual wiring a one-file change; it does not
-- perform it.
--
-- IDEMPOTENT. Safe to re-apply: the constraint is dropped-if-exists before being added, and every
-- function is `create or replace`.
--
-- APPLY ORDER: this migration must precede any re-application of
-- `estate_inventory_and_discovery_bundle.sql` or `lifecycle_notifications_bundle.sql`, whose
-- functions now call `public.release_condition_satisfied`. The
-- `release_conditions_bundle.sql` artifact bundles this file with those functions in the right
-- order for a single paste.

\set ON_ERROR_STOP on

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- 1 · WIDEN the release-condition vocabulary. Additive only.
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ THE CONSTRAINT NAME IS RESOLVED, NOT GUESSED. `access_grants.release_condition` was declared
-- inline in migration 0002 (`release_condition text not null check (...)`), so Postgres generated
-- the name — `access_grants_release_condition_check` by convention, but a database that has been
-- through a table rewrite or a manual repair may carry something else. Dropping a guessed name with
-- `if exists` would silently no-op and leave the OLD constraint in force, and the migration would
-- report success having widened nothing: the new conditions would then be refused by storage while
-- the RPC gate accepted them. So the name is looked up from the catalog by the column it governs.
do $$
declare
  v_name text;
begin
  for v_name in
    select con.conname
      from pg_constraint con
      join pg_class rel on rel.oid = con.conrelid
      join pg_namespace nsp on nsp.oid = rel.relnamespace
     where nsp.nspname = 'public'
       and rel.relname = 'access_grants'
       and con.contype = 'c'
       and pg_get_constraintdef(con.oid) ilike '%release_condition%'
  loop
    execute format('alter table public.access_grants drop constraint %I', v_name);
    raise notice 'dropped prior release_condition constraint: %', v_name;
  end loop;

  alter table public.access_grants
    add constraint access_grants_release_condition_check
    check (release_condition in (
      'never',
      'immediately',
      'after_owner_approval',
      'after_identity_verification',
      'after_access_request_approval',
      -- Phase 11-B: the split. Storable, and satisfied by nothing.
      'after_verified_death',
      'after_verified_incapacity',
      -- DEPRECATED, DELIBERATELY STILL LEGAL. Stored rows must remain readable, and
      -- `release_condition_writable` refuses it for every new write.
      'after_verified_death_or_incapacity',
      'after_claim_case_approval'
    ));
end $$;

-- ★ PROVE THE WIDENING TOOK, IN THE MIGRATION ITSELF. A constraint that failed to move would leave
-- `create_asset_grant` accepting a condition storage refuses — an error surfacing at insert time,
-- from a gate that had already said yes. Both directions are checked: the new values admitted, the
-- fused value still admitted, and an invented value still refused (or the CHECK has been dropped
-- rather than replaced, which reads identically from the accepting side).
do $$
declare
  v_def text;
begin
  select pg_get_constraintdef(con.oid) into v_def
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
   where nsp.nspname = 'public' and rel.relname = 'access_grants'
     and con.conname = 'access_grants_release_condition_check';

  if v_def is null then
    raise exception '0051 FAILED: the release_condition CHECK is absent after the widening';
  end if;
  if position('after_verified_death''' in v_def) = 0 then
    raise exception '0051 FAILED: after_verified_death is not in the widened CHECK: %', v_def;
  end if;
  if position('after_verified_incapacity' in v_def) = 0 then
    raise exception '0051 FAILED: after_verified_incapacity is not in the widened CHECK: %', v_def;
  end if;
  if position('after_verified_death_or_incapacity' in v_def) = 0 then
    raise exception '0051 FAILED: the legacy fused value was dropped — stored rows would be orphaned';
  end if;
  raise notice '0051 · release_condition vocabulary widened (death/incapacity split, legacy retained)';
end $$;


-- ==== db/functions/release_conditions.sql =========================================================
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- THE CANONICAL RELEASE-CONDITION AUTHORITY  ·  Phase 11-B
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- ★ WHY THIS FILE EXISTS. Before Phase 11-B the rule "is this grant's release condition satisfied?"
-- was written out SEVEN times in FIVE routines, and the seven copies gave TWO different answers:
--
--     can_access_document          immediately + the two approval conditions once approved
--     inventory_disclosure_tier    same
--     notification_grant_is_live   same
--     asset_grant_tier             immediately ONLY
--     list_estate_assets           immediately ONLY
--     get_estate_net_worth  (×2)   immediately ONLY
--
-- Phase 11 connects a verified death to disclosure. The single most likely way to get that wrong is
-- not a missing check — it is activating a condition at four sites and forgetting the other three,
-- which is precisely the shape of the four role maps that drifted apart in Phase 9. So the predicate
-- moves HERE first, before any death wiring exists, and every consumer becomes a caller.
--
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- ★ WHAT THIS MODULE DECIDES, AND WHAT IT DELIBERATELY DOES NOT
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- It answers ONE question: given a release condition and the approval fact recorded beside it, is
-- that condition presently SATISFIED?
--
-- It does NOT decide who may receive a grant, compute a disclosure tier, manufacture a grant, verify
-- a death, approve a claim, or transition any lifecycle state. Callers keep every one of those.
--
-- ★ IT TAKES NO LIFECYCLE STATE, AND THAT IS A DECISION RATHER THAN AN OMISSION.
--
-- The obvious shape for this function is `(condition, approved_at, estate_lifecycle_state)`. It is
-- deliberately NOT that shape in 11-B, because giving it one would require every read path to
-- resolve the estate's release state — and "no authorization path consults the release seam" is the
-- structural guarantee that makes an approved claim disclose nothing today. Today that is true not
-- because each read path checks the state and refuses, but because no read path knows the state
-- exists. Wiring a lifecycle argument through here would quietly spend that guarantee for nothing,
-- weeks before there is a verified event to spend it on.
--
-- The 11-D change is therefore a widening of THIS signature and nothing else, in ONE file, with the
-- firewall suite watching. That is the entire point of the phase.
--
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- ★ TWO POLICIES, NAMED — because the drift above is real and 11-B may not spend it
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- Collapsing the two answers into one requires choosing which is right, and both directions change
-- what a user sees:
--
--   · widening the asset surfaces to honour approval-conditioned grants would make an already-stored,
--     already-approved grant start disclosing — new disclosure, forbidden in a behaviour-preserving
--     phase, and a product decision about whether an existing grant becomes more permissive;
--   · narrowing the document surfaces would break the access-request feature outright, since
--     `approve_access_request` issues exactly an `after_access_request_approval` grant.
--
-- So 11-B centralizes the AUTHORITY without deciding the POLICY: both answers live here, each named,
-- each chosen explicitly at its call site, and the divergence is now one `case` arm in one file
-- instead of seven scattered literals nobody can enumerate. `legacy_immediate_only` is named for
-- what it is — a compatibility clamp carried forward verbatim, not a designed rule — and unifying it
-- is the first item in the Phase 11-C ledger.
--
-- ════════════════════════════════════════════════════════════════════════════════════════════════
-- ★ FAIL-CLOSED IN BOTH ARGUMENTS
-- ════════════════════════════════════════════════════════════════════════════════════════════════
--
-- An unknown condition is false. An unknown policy is false. A NULL condition is false. A NULL
-- policy is false. There is no permissive default and no `else true` anywhere below.
--
-- The `coalesce` is load-bearing rather than defensive tidiness: `null = 'immediately'` is NULL, not
-- false, and a boolean gate that returns NULL is not refused by `if not (…) then` — that branch
-- simply does not execute, and the caller carries on as though the check had passed. A three-valued
-- answer from a two-valued gate is how a fail-closed predicate fails open.

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- release_condition_satisfied(condition, approved_at, policy) -> boolean   — THE AUTHORITY
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- `p_policy` has NO DEFAULT, on purpose. A default would let a new consumer inherit the wider rule by
-- saying nothing, which is the exact failure mode — silent policy by omission — that the seven
-- scattered copies represented.
create or replace function public.release_condition_satisfied(
  p_release_condition text,
  p_approved_at       timestamptz,
  p_policy            text
)
 returns boolean
 language sql
 immutable
 set search_path to 'public'
as $function$
  select coalesce(
    case p_policy
      -- Documents, the estate-documents category, and estate inventory. `after_owner_approval`
      -- (owner-initiated) and `after_access_request_approval` (beneficiary-initiated) are the SAME
      -- gate — both mean "the owner approved this access", differing only by who asked.
      when 'standard' then
        p_release_condition = 'immediately'
        or (p_release_condition in ('after_owner_approval', 'after_access_request_approval')
            and p_approved_at is not null)

      -- The asset-value surfaces (account balances, institution names, total asset value, linked
      -- account details). Carried forward EXACTLY as they were written, including their narrowness.
      -- See the note above: this is a compatibility clamp with a 11-C ledger entry, not a rule
      -- anyone designed.
      when 'legacy_immediate_only' then
        p_release_condition = 'immediately'

      -- Unknown policy -> refused. No `else true`, ever.
      else false
    end,
    false);
$function$;

comment on function public.release_condition_satisfied(text, timestamptz, text) is
  'THE canonical release-condition authority (Phase 11-B). Answers only "is this condition presently '
  'satisfied", never who may receive a grant, what tier they get, or whether anyone has died. Takes '
  'NO lifecycle state by design: wiring one through would connect the release seam to authorization, '
  'which is the structural guarantee that makes an approved claim disclose nothing. Death-, '
  'incapacity-, identity- and claim-conditioned grants are dormant under every policy. Unknown '
  'condition, unknown policy and NULL all refuse.';

revoke execute on function public.release_condition_satisfied(text, timestamptz, text) from public, anon;
grant  execute on function public.release_condition_satisfied(text, timestamptz, text) to authenticated;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- release_condition_writable(condition) -> boolean   — THE WRITE-TIME VOCABULARY GATE
-- ────────────────────────────────────────────────────────────────────────────────────────────────
--
-- ★ THE DEATH/INCAPACITY SPLIT LIVES HERE, AND IT IS A WRITE-SIDE RULE ONLY.
--
-- `after_verified_death_or_incapacity` fused two legally distinct events into one storable value.
-- Death and incapacity differ in who is alive to contest, what evidence exists, whether the owner's
-- own instructions still govern, and whether the change is reversible. A single condition cannot
-- carry both and mean anything.
--
-- The split is done WITHOUT touching stored rows:
--
--   · the table CHECK still ACCEPTS the fused value, so every existing row remains readable and no
--     migration has to guess what an owner meant when they chose it;
--   · this gate REFUSES it for new writes, so no further row can be created carrying the ambiguity;
--   · the satisfied-predicate above treats it as dormant — exactly as it was before — so a legacy
--     row is no more permissive than it was yesterday and no less.
--
-- ★ THE LEGACY VALUE IS NOT REINTERPRETED, AND THAT IS THE SAFE ANSWER RATHER THAN THE EASY ONE.
-- Mapping fused rows to `after_verified_death` would be a guess about owner intent that silently
-- makes a stored grant activate on an event the owner may never have chosen; mapping them to
-- `after_verified_incapacity` is the same guess pointing the other way. Both are product decisions
-- about somebody else's estate. An explicit unsatisfiable legacy state costs a re-authoring; a wrong
-- guess costs a disclosure that cannot be undone.
--
-- ★ AND BOTH NEW CONDITIONS ARE UNSATISFIABLE TODAY. Being writable is not being live: nothing
-- verifies a death, nothing verifies an incapacity, and `release_condition_satisfied` admits neither
-- under any policy. This gate widens what an owner may EXPRESS, never what anybody may SEE.
create or replace function public.release_condition_writable(p_release_condition text)
 returns boolean
 language sql
 immutable
 set search_path to 'public'
as $function$
  select coalesce(p_release_condition in (
    'never',
    'immediately',
    'after_owner_approval',
    'after_identity_verification',
    'after_access_request_approval',
    -- Phase 11-B: the split. Storable, expressible, and satisfied by nothing.
    'after_verified_death',
    'after_verified_incapacity',
    'after_claim_case_approval'
    -- 'after_verified_death_or_incapacity' is DELIBERATELY ABSENT — readable, never writable again.
  ), false);
$function$;

comment on function public.release_condition_writable(text) is
  'Write-time vocabulary gate for access_grants.release_condition (Phase 11-B). Accepts the split '
  'after_verified_death / after_verified_incapacity and REFUSES the deprecated fused '
  'after_verified_death_or_incapacity, which remains legal in the CHECK so stored rows stay readable '
  'and unreinterpreted. Writable is not live: neither new condition is satisfied by any policy.';

revoke execute on function public.release_condition_writable(text) from public, anon;
grant  execute on function public.release_condition_writable(text) to authenticated;


-- ==== db/functions/document_grantable.sql =========================================================
-- public.document_grantable(p_role text, p_sensitivity text) -> boolean
--
-- THE DOCUMENT DISCLOSURE CEILING. What a grantee role may be shown at a given document
-- sensitivity, regardless of what tier a grant happens to name. `can_access_document` re-checks it
-- at READ time against the document's CURRENT sensitivity, so reclassifying a document to `sealed`
-- takes effect immediately rather than only for grants issued afterwards.
--
-- ★ EXTRACTED TO A SOURCE FILE IN PHASE 11-B, AND IT HAD BEEN A SHADOW COPY UNTIL THEN.
--
-- Its only definition was inside `db/migrations/0002_20260620_access_grants.sql`, and
-- `db/tests/preamble_real_auth.sql` carried a hand-written copy so the SQL suite could stand the
-- schema up. `verifySqlAuthorization.mjs` refuses to run when the preamble shadows a production
-- body — but it resolved "production body" by searching `db/functions/` alone, so a function whose
-- source of truth lived in a migration was invisible to the guard. The ceiling, the document gate
-- and the asset ceiling all sat in that blind spot, unaudited, for their entire lives.
--
-- They happened to agree. Nothing would have said so if they had not — which is the same near-miss
-- as `asset_bracket_low`/`asset_bracket_high` in Phase 10-F, one directory over.
--
-- The body below is byte-identical to 0002's. Extraction is what makes it comparable, not a rewrite.
--
-- Unknown sensitivity denies. Source of truth — re-apply on DB reset.

create or replace function public.document_grantable(p_role text, p_sensitivity text)
returns boolean
language sql
immutable
as $$
  select case
    when p_sensitivity = 'sealed'     then false
    when p_sensitivity = 'restricted' then p_role = 'professional_delegate'
    when p_sensitivity in ('low','medium','high')
                                      then p_role in ('beneficiary','professional_delegate')
    else false                                   -- unknown sensitivity -> deny
  end;
$$;


-- ==== db/functions/can_access_document.sql ========================================================
-- public.can_access_document(p_document_id uuid) -> boolean
--
-- THE DOCUMENT AUTHORIZATION GATE. Consulted by the `documents` RLS read policy and by
-- `get_professional_workspace`; it is the only thing standing between a non-owner and a document row.
--
-- ★ EXTRACTED TO A SOURCE FILE IN PHASE 11-B. Until then its definition lived in
-- `db/migrations/0004_20260624_access_requests.sql` (re-declared from 0003, itself from 0002), with a
-- hand-written copy in `db/tests/preamble_real_auth.sql` that the harness's own anti-shadow guard
-- could not see — the guard searched `db/functions/` for a production counterpart and found none, so
-- it classified the estate's document gate as "a pure harness fixture" and skipped it. The copy
-- happened to match 0004. It is now comparable rather than lucky.
--
-- ★ THE RELEASE RULE IS NO LONGER WRITTEN HERE (Phase 11-B). It was one of seven copies; it is now
-- one call to `public.release_condition_satisfied`. The `'standard'` policy is the same rule this
-- function has carried since 0004 — `immediately`, plus the two approval-based conditions once
-- `approved_at` is set — and the SQL suite compares the predicate's full truth table rather than
-- taking that claim on trust.
--
-- Ladder, unchanged: owner inherent → per-document grant → `estate_documents` category fallback →
-- default-deny → ceiling re-check against CURRENT sensitivity → hidden tier → release condition.
--
-- SECURITY DEFINER; relies on auth.uid(). The DEFINER context is what lets the policy call it
-- without recursing through `documents`' own RLS. Source of truth — re-apply on DB reset.

create or replace function public.can_access_document(p_document_id uuid)
returns boolean
language plpgsql
security definer
stable
set search_path to 'public'
as $$
declare
  v_uid    uuid := auth.uid();
  v_estate uuid;
  v_sens   text;
  g        record;
begin
  if v_uid is null then
    return false;
  end if;

  select estate_id, sensitivity into v_estate, v_sens
  from public.documents
  where id = p_document_id;

  if v_estate is null then
    return false;
  end if;

  -- Owner inherent (A.1) — no grant row needed.
  if public.is_estate_owner(v_estate) then
    return true;
  end if;

  -- Non-owner: per-document grant first...
  select grantee_role, visibility_tier, release_condition, approved_at
    into g
  from public.access_grants
  where estate_id = v_estate
    and grantee_user_id = v_uid
    and status = 'active'
    and document_id = p_document_id
  limit 1;

  -- ...then category 'estate_documents' fallback (the access-request grant lands here).
  if not found then
    select grantee_role, visibility_tier, release_condition, approved_at
      into g
    from public.access_grants
    where estate_id = v_estate
      and grantee_user_id = v_uid
      and status = 'active'
      and category = 'estate_documents'
    limit 1;
  end if;

  if not found then
    return false;                                            -- default-deny (A.5)
  end if;

  -- Ceiling re-check against the document's CURRENT sensitivity (A.3). For a CATEGORY
  -- grant this is the ONLY ceiling enforcement (the write-time trigger no-ops on category
  -- grants), so a sealed/restricted doc stays hidden here even with the category grant.
  if not public.document_grantable(g.grantee_role, v_sens) then
    return false;
  end if;

  if g.visibility_tier = 'hidden' then
    return false;
  end if;

  -- ★ THE CANONICAL RELEASE PREDICATE (Phase 11-B) — was seven scattered copies, now one call.
  -- 'never' and every signal-based condition (identity, death, incapacity, claim) stay
  -- dormant-deny (A.4), and an unknown condition refuses.
  return public.release_condition_satisfied(g.release_condition, g.approved_at, 'standard');
end;
$$;
