-- R02_7 · HOSTED COLUMN FINGERPRINT FORENSIC DIAGNOSTIC.  PREPARED, NOT EXECUTED.
-- Target: afterworth-nonprod (qxzeougbaarecaiiqsay).
-- SELECT-only: 0 DDL · 0 DML · 0 GRANT/REVOKE · 0 LOCK · 0 SET ROLE · 0 ALTER DEFAULT PRIVILEGES ·
--              0 transaction control · 0 DO.
--
-- ★ WHY. V2 (sha 9bf2e193…2af2) was executed hosted once: 44 gates PASS, one FAIL —
--     gate_columns_fingerprint  expected 4b5b967fcbb085db5e7ae4fd20a07653
--                               actual   9521ca65dda82d442f34a3d75d8d5a59
--   while gate_columns (the count) PASSed at 415. The hosted schema has the same number of columns
--   and at least one normalized row renders differently. An aggregate hash cannot say which one.
--   This emits the difference ROW BY ROW.
--
-- ★ NORMALIZATION IS V2'S, UNCHANGED — the same five fields in the same order:
--     table_name . column_name : data_type : is_nullable : coalesce(column_default,'-')
--   from information_schema.columns where table_schema='public'; rows joined by ',' after
--   ORDER BY on the whole row string; md5.
--   The canonical fingerprint 4b5b967f… is NOT changed, and nothing is normalized away to make the
--   hashes agree. Any such change requires separate adjudication AFTER the difference is known.
--
-- ★ EXPECTED ROWS ORIGINATE FROM PATH_A_FINAL (bootstrap@0060 + 0061 + 0062 + 0063), independently
--   cross-checked against PATH_B_FINAL: both give 415 rows, fingerprint 4b5b967f…, and ZERO
--   row-level differences. They are NOT derived from the hosted database or from V2's actual output.
--
-- ★ Sections 2-4 expose rendering inputs WITHOUT normalizing them, so a schema-qualification or
--   typmod rendering difference can be told apart from real type/default drift.

-- ── 0 · OPERATOR PIN ─────────────────────────────────────────────────────────────────────────
select 'PIN' as class, 'target_project_ref' as k, 'qxzeougbaarecaiiqsay' as v
union all select 'PIN','operator_project_identity_confirmation_required','true — confirm in dashboard; not verifiable in SQL'
union all select 'PIN','canonical_expected_fingerprint','4b5b967fcbb085db5e7ae4fd20a07653 (PATH_A_FINAL, unchanged)'
union all select 'PIN','v2_hosted_actual_fingerprint','9521ca65dda82d442f34a3d75d8d5a59 (recorded, NOT adopted)';

-- ── 1 · ROW-LEVEL DIFFERENCE REPORT — the decisive output ───────────────────────────────────
with expected(table_name, column_name, data_type, is_nullable, column_default) as (values
  ('access_grants','approved_at','timestamp with time zone','YES','-'),
  ('access_grants','approved_by_user_id','uuid','YES','-'),
  ('access_grants','category','text','YES','-'),
  ('access_grants','created_at','timestamp with time zone','NO','now()'),
  ('access_grants','document_id','uuid','YES','-'),
  ('access_grants','estate_id','uuid','NO','-'),
  ('access_grants','granted_by_user_id','uuid','NO','-'),
  ('access_grants','grantee_role','text','NO','-'),
  ('access_grants','grantee_user_id','uuid','NO','-'),
  ('access_grants','id','uuid','NO','gen_random_uuid()'),
  ('access_grants','professional_type','text','YES','-'),
  ('access_grants','release_condition','text','NO','-'),
  ('access_grants','requires_step_up','boolean','NO','false'),
  ('access_grants','revoked_at','timestamp with time zone','YES','-'),
  ('access_grants','revoked_by_user_id','uuid','YES','-'),
  ('access_grants','status','text','NO','''active''::text'),
  ('access_grants','updated_at','timestamp with time zone','NO','now()'),
  ('access_grants','visibility_tier','text','NO','-'),
  ('access_requests','category','text','NO','-'),
  ('access_requests','created_at','timestamp with time zone','NO','now()'),
  ('access_requests','estate_id','uuid','NO','-'),
  ('access_requests','id','uuid','NO','gen_random_uuid()'),
  ('access_requests','reason','text','YES','-'),
  ('access_requests','requester_role','text','YES','-'),
  ('access_requests','requester_user_id','uuid','NO','-'),
  ('access_requests','resolved_at','timestamp with time zone','YES','-'),
  ('access_requests','resolved_by_user_id','uuid','YES','-'),
  ('access_requests','resulting_grant_id','uuid','YES','-'),
  ('access_requests','status','text','NO','''pending''::text'),
  ('admins','created_at','timestamp with time zone','NO','now()'),
  ('admins','note','text','YES','-'),
  ('admins','user_id','uuid','NO','-'),
  ('assets','asset_type','text','NO','-'),
  ('assets','created_at','timestamp with time zone','YES','now()'),
  ('assets','currency','text','YES','''USD''::text'),
  ('assets','estate_id','uuid','NO','-'),
  ('assets','estimated_value_cents','bigint','YES','-'),
  ('assets','id','uuid','NO','extensions.uuid_generate_v4()'),
  ('assets','identifier_last4','text','YES','-'),
  ('assets','institution','text','YES','-'),
  ('assets','metadata','jsonb','YES','''{}''::jsonb'),
  ('assets','owner_id','uuid','NO','-'),
  ('assets','title','text','NO','-'),
  ('assets','updated_at','timestamp with time zone','YES','now()'),
  ('audit_logs','action','text','NO','-'),
  ('audit_logs','actor_id','uuid','YES','-'),
  ('audit_logs','created_at','timestamp with time zone','YES','now()'),
  ('audit_logs','estate_id','uuid','YES','-'),
  ('audit_logs','id','bigint','NO','nextval(''audit_logs_id_seq''::regclass)'),
  ('audit_logs','ip','inet','YES','-'),
  ('audit_logs','metadata','jsonb','YES','''{}''::jsonb'),
  ('audit_logs','source','text','NO','''server''::text'),
  ('audit_logs','target_id','uuid','YES','-'),
  ('audit_logs','target_table','text','YES','-'),
  ('audit_logs','user_agent','text','YES','-'),
  ('beneficiaries','allocation_percent','numeric','YES','-'),
  ('beneficiaries','created_at','timestamp with time zone','YES','now()'),
  ('beneficiaries','email','text','YES','-'),
  ('beneficiaries','estate_id','uuid','NO','-'),
  ('beneficiaries','full_name','text','NO','-'),
  ('beneficiaries','id','uuid','NO','extensions.uuid_generate_v4()'),
  ('beneficiaries','notes','text','YES','-'),
  ('beneficiaries','owner_id','uuid','NO','-'),
  ('beneficiaries','phone','text','YES','-'),
  ('beneficiaries','relationship','text','YES','-'),
  ('beneficiaries','updated_at','timestamp with time zone','YES','now()'),
  ('beneficiaries','user_id','uuid','YES','-'),
  ('claim_packets','death_certificate_doc_id','uuid','YES','-'),
  ('claim_packets','decided_at','timestamp with time zone','YES','-'),
  ('claim_packets','estate_id','uuid','NO','-'),
  ('claim_packets','executor_id_doc_id','uuid','YES','-'),
  ('claim_packets','id','uuid','NO','extensions.uuid_generate_v4()'),
  ('claim_packets','requested_by','uuid','NO','-'),
  ('claim_packets','review_notes','text','YES','-'),
  ('claim_packets','reviewer_id','uuid','YES','-'),
  ('claim_packets','status','text','NO','''submitted''::text'),
  ('claim_packets','submitted_at','timestamp with time zone','YES','now()'),
  ('connection_secrets','access_token','text','NO','-'),
  ('connection_secrets','connection_id','uuid','NO','-'),
  ('connection_secrets','created_at','timestamp with time zone','NO','now()'),
  ('connection_secrets','provider','text','NO','-'),
  ('connections','created_at','timestamp with time zone','NO','now()'),
  ('connections','estate_id','uuid','NO','-'),
  ('connections','id','uuid','NO','gen_random_uuid()'),
  ('connections','institution_id','text','YES','-'),
  ('connections','institution_name','text','YES','-'),
  ('connections','provider','text','NO','-'),
  ('connections','reference_token','text','NO','-'),
  ('connections','status','text','NO','''active''::text'),
  ('connections','updated_at','timestamp with time zone','NO','now()'),
  ('consent_records','accepted_at','timestamp with time zone','NO','now()'),
  ('consent_records','consent_type','text','NO','-'),
  ('consent_records','created_at','timestamp with time zone','NO','now()'),
  ('consent_records','document_version','text','NO','-'),
  ('consent_records','id','uuid','NO','extensions.uuid_generate_v4()'),
  ('consent_records','user_id','uuid','NO','-'),
  ('death_verification_cases','attained_level','USER-DEFINED','YES','-'),
  ('death_verification_cases','created_at','timestamp with time zone','NO','now()'),
  ('death_verification_cases','decided_at','timestamp with time zone','YES','-'),
  ('death_verification_cases','decided_by','uuid','YES','-'),
  ('death_verification_cases','decision_note','text','YES','-'),
  ('death_verification_cases','estate_id','uuid','NO','-'),
  ('death_verification_cases','event_type','text','NO','''death''::text'),
  ('death_verification_cases','id','uuid','NO','gen_random_uuid()'),
  ('death_verification_cases','initiated_by','uuid','NO','-'),
  ('death_verification_cases','initiator_capacity','text','NO','-'),
  ('death_verification_cases','initiator_designation_id','uuid','NO','-'),
  ('death_verification_cases','jurisdiction_context','text','YES','-'),
  ('death_verification_cases','required_level_at_initiation','USER-DEFINED','NO','-'),
  ('death_verification_cases','status','text','NO','''open''::text'),
  ('death_verification_cases','updated_at','timestamp with time zone','NO','now()'),
  ('death_verification_evidence','case_id','uuid','NO','-'),
  ('death_verification_evidence','document_id','uuid','NO','-'),
  ('death_verification_evidence','estate_id','uuid','NO','-'),
  ('death_verification_evidence','id','uuid','NO','gen_random_uuid()'),
  ('death_verification_evidence','review_note','text','YES','-'),
  ('death_verification_evidence','review_status','text','NO','''received''::text'),
  ('death_verification_evidence','reviewed_at','timestamp with time zone','YES','-'),
  ('death_verification_evidence','reviewed_by','uuid','YES','-'),
  ('death_verification_evidence','submitted_at','timestamp with time zone','NO','now()'),
  ('death_verification_evidence','submitted_by','uuid','NO','-'),
  ('document_sensitivity','badge_color_key','text','YES','-'),
  ('document_sensitivity','created_at','timestamp with time zone','NO','now()'),
  ('document_sensitivity','description','text','YES','-'),
  ('document_sensitivity','display_name','text','NO','-'),
  ('document_sensitivity','icon_key','text','YES','-'),
  ('document_sensitivity','is_active','boolean','NO','true'),
  ('document_sensitivity','rank','integer','NO','0'),
  ('document_sensitivity','sort_order','integer','NO','0'),
  ('document_sensitivity','value','text','NO','-'),
  ('document_subtype','badge_color_key','text','YES','-'),
  ('document_subtype','created_at','timestamp with time zone','NO','now()'),
  ('document_subtype','description','text','YES','-'),
  ('document_subtype','display_name','text','NO','-'),
  ('document_subtype','icon_key','text','YES','-'),
  ('document_subtype','is_active','boolean','NO','true'),
  ('document_subtype','parent_doc_type','text','NO','-'),
  ('document_subtype','rank','integer','NO','0'),
  ('document_subtype','sort_order','integer','NO','0'),
  ('document_subtype','subtype','text','NO','-'),
  ('document_type','badge_color_key','text','YES','-'),
  ('document_type','created_at','timestamp with time zone','NO','now()'),
  ('document_type','description','text','YES','-'),
  ('document_type','display_name','text','NO','-'),
  ('document_type','icon_key','text','YES','-'),
  ('document_type','is_active','boolean','NO','true'),
  ('document_type','rank','integer','NO','0'),
  ('document_type','sort_order','integer','NO','0'),
  ('document_type','value','text','NO','-'),
  ('documents','created_at','timestamp with time zone','YES','now()'),
  ('documents','doc_subtype','text','YES','-'),
  ('documents','doc_type','text','NO','-'),
  ('documents','estate_id','uuid','NO','-'),
  ('documents','id','uuid','NO','extensions.uuid_generate_v4()'),
  ('documents','is_encrypted','boolean','YES','true'),
  ('documents','mime_type','text','YES','-'),
  ('documents','owner_id','uuid','NO','-'),
  ('documents','retention_until','timestamp with time zone','YES','-'),
  ('documents','sensitivity','text','NO','''sealed''::text'),
  ('documents','sha256','text','YES','-'),
  ('documents','size_bytes','bigint','YES','-'),
  ('documents','storage_path','text','NO','-'),
  ('documents','title','text','NO','-'),
  ('encrypted_instructions','ciphertext','bytea','NO','-'),
  ('encrypted_instructions','created_at','timestamp with time zone','YES','now()'),
  ('encrypted_instructions','estate_id','uuid','NO','-'),
  ('encrypted_instructions','id','uuid','NO','extensions.uuid_generate_v4()'),
  ('encrypted_instructions','iv','bytea','NO','-'),
  ('encrypted_instructions','owner_id','uuid','NO','-'),
  ('encrypted_instructions','release_condition','text','NO','-'),
  ('encrypted_instructions','released','boolean','YES','false'),
  ('encrypted_instructions','released_at','timestamp with time zone','YES','-'),
  ('encrypted_instructions','title','text','NO','-'),
  ('encrypted_instructions','wrapped_key','bytea','NO','-'),
  ('estate_asset_category','created_at','timestamp with time zone','NO','now()'),
  ('estate_asset_category','description','text','YES','-'),
  ('estate_asset_category','display_name','text','NO','-'),
  ('estate_asset_category','icon_key','text','YES','-'),
  ('estate_asset_category','is_active','boolean','NO','true'),
  ('estate_asset_category','is_physical','boolean','NO','false'),
  ('estate_asset_category','sort_order','integer','NO','0'),
  ('estate_asset_category','value','text','NO','-'),
  ('estate_asset_documents','asset_id','uuid','NO','-'),
  ('estate_asset_documents','doc_id','uuid','NO','-'),
  ('estate_asset_documents','linked_at','timestamp with time zone','NO','now()'),
  ('estate_asset_documents','linked_by','uuid','NO','-'),
  ('estate_asset_subtype','created_at','timestamp with time zone','NO','now()'),
  ('estate_asset_subtype','description','text','YES','-'),
  ('estate_asset_subtype','display_name','text','NO','-'),
  ('estate_asset_subtype','icon_key','text','YES','-'),
  ('estate_asset_subtype','is_active','boolean','NO','true'),
  ('estate_asset_subtype','parent_category','text','NO','-'),
  ('estate_asset_subtype','sort_order','integer','NO','0'),
  ('estate_asset_subtype','subtype','text','NO','-'),
  ('estate_assets','approximate_value_cents','bigint','YES','-'),
  ('estate_assets','archived_at','timestamp with time zone','YES','-'),
  ('estate_assets','archived_by','uuid','YES','-'),
  ('estate_assets','beneficiary_note','text','YES','-'),
  ('estate_assets','category','text','NO','-'),
  ('estate_assets','country_code','text','YES','-'),
  ('estate_assets','created_at','timestamp with time zone','NO','now()'),
  ('estate_assets','created_by','uuid','NO','-'),
  ('estate_assets','currency','text','NO','''USD''::text'),
  ('estate_assets','estate_id','uuid','NO','-'),
  ('estate_assets','id','uuid','NO','gen_random_uuid()'),
  ('estate_assets','institution_name','text','YES','-'),
  ('estate_assets','jurisdiction','text','YES','-'),
  ('estate_assets','label','text','NO','-'),
  ('estate_assets','notes','text','YES','-'),
  ('estate_assets','owner_label','text','YES','-'),
  ('estate_assets','reference_hint','text','YES','-'),
  ('estate_assets','sensitivity','text','NO','''sealed''::text'),
  ('estate_assets','subtype','text','NO','-'),
  ('estate_assets','updated_at','timestamp with time zone','NO','now()'),
  ('estate_assets','verification_status','text','NO','''unverified''::text'),
  ('estate_designations','created_at','timestamp with time zone','NO','now()'),
  ('estate_designations','designation_type','text','NO','-'),
  ('estate_designations','estate_id','uuid','NO','-'),
  ('estate_designations','granted_by','uuid','YES','-'),
  ('estate_designations','id','uuid','NO','extensions.uuid_generate_v4()'),
  ('estate_designations','revoked_at','timestamp with time zone','YES','-'),
  ('estate_designations','source_invitation_id','uuid','YES','-'),
  ('estate_designations','status','text','NO','''active''::text'),
  ('estate_designations','user_id','uuid','NO','-'),
  ('estate_lifecycle','challenge_window_started_at','timestamp with time zone','YES','-'),
  ('estate_lifecycle','estate_id','uuid','NO','-'),
  ('estate_lifecycle','halted_at','timestamp with time zone','YES','-'),
  ('estate_lifecycle','owner_notified_at','timestamp with time zone','YES','-'),
  ('estate_lifecycle','released_at','timestamp with time zone','YES','-'),
  ('estate_lifecycle','safety_notification_id','uuid','YES','-'),
  ('estate_lifecycle','state','text','NO','''active''::text'),
  ('estate_lifecycle','updated_at','timestamp with time zone','NO','now()'),
  ('estate_lifecycle','updated_case_id','uuid','YES','-'),
  ('estate_memberships','approved_at','timestamp with time zone','YES','-'),
  ('estate_memberships','created_at','timestamp with time zone','YES','now()'),
  ('estate_memberships','estate_id','uuid','NO','-'),
  ('estate_memberships','id','uuid','NO','extensions.uuid_generate_v4()'),
  ('estate_memberships','invited_by','uuid','YES','-'),
  ('estate_memberships','role','text','NO','-'),
  ('estate_memberships','source_invitation_id','uuid','YES','-'),
  ('estate_memberships','status','text','NO','''pending''::text'),
  ('estate_memberships','user_id','uuid','NO','-'),
  ('estates','created_at','timestamp with time zone','YES','now()'),
  ('estates','description','text','YES','-'),
  ('estates','id','uuid','NO','extensions.uuid_generate_v4()'),
  ('estates','is_primary','boolean','NO','false'),
  ('estates','jurisdiction','text','YES','-'),
  ('estates','name','text','NO','-'),
  ('estates','owner_id','uuid','NO','-'),
  ('estates','status','text','NO','''active''::text'),
  ('estates','updated_at','timestamp with time zone','YES','now()'),
  ('invitation_delivery_outbox','attempts','integer','NO','0'),
  ('invitation_delivery_outbox','claimed_at','timestamp with time zone','YES','-'),
  ('invitation_delivery_outbox','delivery_generation','integer','NO','0'),
  ('invitation_delivery_outbox','estate_id','uuid','NO','-'),
  ('invitation_delivery_outbox','failure_class','text','YES','-'),
  ('invitation_delivery_outbox','id','uuid','NO','extensions.uuid_generate_v4()'),
  ('invitation_delivery_outbox','idempotency_key','text','YES','-'),
  ('invitation_delivery_outbox','invitation_id','uuid','NO','-'),
  ('invitation_delivery_outbox','issued_at','timestamp with time zone','YES','-'),
  ('invitation_delivery_outbox','last_error','text','YES','-'),
  ('invitation_delivery_outbox','last_outcome_at','timestamp with time zone','YES','-'),
  ('invitation_delivery_outbox','next_attempt_at','timestamp with time zone','YES','-'),
  ('invitation_delivery_outbox','provider_message_id','text','YES','-'),
  ('invitation_delivery_outbox','reason','text','NO','-'),
  ('invitation_delivery_outbox','requested_at','timestamp with time zone','NO','now()'),
  ('invitation_delivery_outbox','requested_by','uuid','NO','-'),
  ('invitation_delivery_outbox','status','text','NO','''queued''::text'),
  ('invitations','accepted_at','timestamp with time zone','YES','-'),
  ('invitations','accepted_by','uuid','YES','-'),
  ('invitations','created_at','timestamp with time zone','YES','now()'),
  ('invitations','declined_at','timestamp with time zone','YES','-'),
  ('invitations','estate_display_name','text','YES','-'),
  ('invitations','estate_id','uuid','NO','-'),
  ('invitations','expires_at','timestamp with time zone','NO','-'),
  ('invitations','extended_at','timestamp with time zone','YES','-'),
  ('invitations','extended_by','uuid','YES','-'),
  ('invitations','id','uuid','NO','extensions.uuid_generate_v4()'),
  ('invitations','invited_by','uuid','NO','-'),
  ('invitations','invitee_email','text','YES','-'),
  ('invitations','invitee_email_hint','text','YES','-'),
  ('invitations','invitee_phone','text','YES','-'),
  ('invitations','invitee_phone_hint','text','YES','-'),
  ('invitations','inviter_display_name','text','YES','-'),
  ('invitations','kind','text','NO','-'),
  ('invitations','preview_visibility','jsonb','YES','''{}''::jsonb'),
  ('invitations','proposed_role','text','NO','-'),
  ('invitations','revoked_at','timestamp with time zone','YES','-'),
  ('invitations','revoked_by','uuid','YES','-'),
  ('invitations','status','text','NO','''pending''::text'),
  ('invitations','token_hash','text','NO','-'),
  ('invitations','updated_at','timestamp with time zone','YES','now()'),
  ('jurisdiction_policy','created_at','timestamp with time zone','NO','now()'),
  ('jurisdiction_policy','floor_level','USER-DEFINED','NO','-'),
  ('jurisdiction_policy','is_counsel_approved','boolean','NO','false'),
  ('jurisdiction_policy','jurisdiction','text','NO','-'),
  ('jurisdiction_policy','notes','text','YES','-'),
  ('jurisdiction_policy','updated_at','timestamp with time zone','NO','now()'),
  ('jurisdiction_policy','updated_by','uuid','YES','-'),
  ('legal_holds','doc_id','uuid','NO','-'),
  ('legal_holds','id','uuid','NO','extensions.uuid_generate_v4()'),
  ('legal_holds','placed_at','timestamp with time zone','NO','now()'),
  ('legal_holds','placed_by','uuid','NO','-'),
  ('legal_holds','reason','text','NO','-'),
  ('legal_holds','released_at','timestamp with time zone','YES','-'),
  ('legal_holds','released_by','uuid','YES','-'),
  ('mfa_recovery_attempts','failed_count','integer','NO','0'),
  ('mfa_recovery_attempts','locked_until','timestamp with time zone','YES','-'),
  ('mfa_recovery_attempts','updated_at','timestamp with time zone','NO','now()'),
  ('mfa_recovery_attempts','user_id','uuid','NO','-'),
  ('normalized_assets','asset_category','text','YES','-'),
  ('normalized_assets','asset_group','text','NO','-'),
  ('normalized_assets','asset_subtype','text','YES','-'),
  ('normalized_assets','balance_cents','bigint','NO','0'),
  ('normalized_assets','confidence_level','text','NO','''high''::text'),
  ('normalized_assets','connection_id','uuid','NO','-'),
  ('normalized_assets','created_at','timestamp with time zone','NO','now()'),
  ('normalized_assets','currency','text','NO','''USD''::text'),
  ('normalized_assets','estate_id','uuid','NO','-'),
  ('normalized_assets','holdings','jsonb','NO','''[]''::jsonb'),
  ('normalized_assets','id','uuid','NO','gen_random_uuid()'),
  ('normalized_assets','institution_name','text','YES','-'),
  ('normalized_assets','last_sync_status','text','NO','''live_connected''::text'),
  ('normalized_assets','masked_identifier','text','YES','-'),
  ('normalized_assets','provider_name','text','YES','-'),
  ('normalized_assets','refresh_timestamp','timestamp with time zone','YES','-'),
  ('normalized_assets','source_type','text','NO','''aggregator''::text'),
  ('normalized_assets','verification_status','text','NO','''verified''::text'),
  ('notifications','action_deep_link','text','YES','-'),
  ('notifications','body','text','YES','-'),
  ('notifications','channel','text','NO','''inApp''::text'),
  ('notifications','created_at','timestamp with time zone','YES','now()'),
  ('notifications','estate_id','uuid','YES','-'),
  ('notifications','id','uuid','NO','extensions.uuid_generate_v4()'),
  ('notifications','kind','text','NO','-'),
  ('notifications','payload','jsonb','NO','''{}''::jsonb'),
  ('notifications','read','boolean','YES','false'),
  ('notifications','related_document_id','uuid','YES','-'),
  ('notifications','title','text','NO','-'),
  ('notifications','user_id','uuid','NO','-'),
  ('outbox_purge_audit','actor_id','uuid','YES','-'),
  ('outbox_purge_audit','id','uuid','NO','gen_random_uuid()'),
  ('outbox_purge_audit','newest_row_at','timestamp with time zone','YES','-'),
  ('outbox_purge_audit','oldest_row_at','timestamp with time zone','YES','-'),
  ('outbox_purge_audit','outbox_name','text','NO','-'),
  ('outbox_purge_audit','purged_at','timestamp with time zone','NO','now()'),
  ('outbox_purge_audit','reason','text','NO','-'),
  ('outbox_purge_audit','row_count','integer','NO','-'),
  ('owner_notice_outbox','attempts','integer','NO','0'),
  ('owner_notice_outbox','case_id','uuid','YES','-'),
  ('owner_notice_outbox','channel','text','NO','''email''::text'),
  ('owner_notice_outbox','claimed_at','timestamp with time zone','YES','-'),
  ('owner_notice_outbox','dispatched_at','timestamp with time zone','YES','-'),
  ('owner_notice_outbox','estate_id','uuid','NO','-'),
  ('owner_notice_outbox','failure_class','text','YES','-'),
  ('owner_notice_outbox','generation','integer','NO','1'),
  ('owner_notice_outbox','id','uuid','NO','gen_random_uuid()'),
  ('owner_notice_outbox','next_attempt_at','timestamp with time zone','YES','-'),
  ('owner_notice_outbox','notice_accepted_at','timestamp with time zone','YES','-'),
  ('owner_notice_outbox','notice_kind','text','NO','-'),
  ('owner_notice_outbox','purge_audit_id','uuid','YES','-'),
  ('owner_notice_outbox','recipient','text','NO','-'),
  ('owner_notice_outbox','reissue_reason','text','YES','-'),
  ('owner_notice_outbox','reissued_by','uuid','YES','-'),
  ('owner_notice_outbox','requested_at','timestamp with time zone','NO','now()'),
  ('owner_notice_outbox','status','text','NO','''queued''::text'),
  ('owner_notice_outbox','superseded_by','uuid','YES','-'),
  ('owner_notice_outbox','user_id','uuid','NO','-'),
  ('profiles','avatar_url','text','YES','-'),
  ('profiles','created_at','timestamp with time zone','YES','now()'),
  ('profiles','date_of_birth','date','YES','-'),
  ('profiles','email','text','NO','-'),
  ('profiles','full_name','text','YES','-'),
  ('profiles','id','uuid','NO','-'),
  ('profiles','mfa_enabled','boolean','YES','false'),
  ('profiles','phone','text','YES','-'),
  ('profiles','updated_at','timestamp with time zone','YES','now()'),
  ('recovery_codes','code_hash','text','NO','-'),
  ('recovery_codes','created_at','timestamp with time zone','NO','now()'),
  ('recovery_codes','id','uuid','NO','gen_random_uuid()'),
  ('recovery_codes','used_at','timestamp with time zone','YES','-'),
  ('recovery_codes','user_id','uuid','NO','-'),
  ('release_authorizations','audit_reason','text','NO','-'),
  ('release_authorizations','authorized_at','timestamp with time zone','NO','now()'),
  ('release_authorizations','case_id','uuid','NO','-'),
  ('release_authorizations','estate_id','uuid','NO','-'),
  ('release_authorizations','id','uuid','NO','gen_random_uuid()'),
  ('release_authorizations','released_at','timestamp with time zone','YES','-'),
  ('release_authorizations','reviewer_a','uuid','NO','-'),
  ('release_authorizations','reviewer_b','uuid','NO','-'),
  ('release_authorizations','verified_at','timestamp with time zone','NO','-'),
  ('release_safety_policy','challenge_window','interval','NO','-'),
  ('release_safety_policy','id','boolean','NO','true'),
  ('release_safety_policy','updated_at','timestamp with time zone','NO','now()'),
  ('storage_deletion_outbox','attempts','integer','NO','0'),
  ('storage_deletion_outbox','bucket','text','NO','''documents''::text'),
  ('storage_deletion_outbox','estate_id','uuid','NO','-'),
  ('storage_deletion_outbox','id','uuid','NO','extensions.uuid_generate_v4()'),
  ('storage_deletion_outbox','last_error','text','YES','-'),
  ('storage_deletion_outbox','object_path','text','NO','-'),
  ('storage_deletion_outbox','purged_at','timestamp with time zone','YES','-'),
  ('storage_deletion_outbox','reason','text','NO','-'),
  ('storage_deletion_outbox','requested_at','timestamp with time zone','NO','now()'),
  ('storage_deletion_outbox','requested_by','uuid','NO','-'),
  ('storage_deletion_outbox','status','text','NO','''pending''::text'),
  ('taxonomy_version','id','integer','NO','1'),
  ('taxonomy_version','schema_version','integer','NO','1'),
  ('taxonomy_version','updated_at','timestamp with time zone','NO','now()'),
  ('taxonomy_version','vocabulary_version','integer','NO','1'),
  ('upload_policy','allowed_mime_types','ARRAY','NO','-'),
  ('upload_policy','id','integer','NO','1'),
  ('upload_policy','max_aggregate_bytes','bigint','NO','-'),
  ('upload_policy','max_files_per_claim','integer','NO','-'),
  ('upload_policy','max_upload_bytes','bigint','NO','-'),
  ('upload_policy','updated_at','timestamp with time zone','NO','now()')
),
actual as (
  select c.table_name::text, c.column_name::text, c.data_type::text, c.is_nullable::text,
         coalesce(c.column_default,'-')::text as column_default
    from information_schema.columns c
   where c.table_schema = 'public'
),
ctl(check_name, expected_v, actual_v) as (values
  ('ctl_expected_rows_embedded','415',(select count(*)::text from expected)),
  ('ctl_actual_rows_visible','415',(select count(*)::text from actual)),
  ('ctl_known_column_present','1',(select count(*)::text from actual where table_name='assets' and column_name='estate_id'))
)
select 'CONTROL' as class, check_name as table_name, '' as column_name, '' as attribute,
       expected_v as expected, actual_v as actual,
       case when expected_v is not distinct from actual_v then 'PASS' else 'FAIL' end as verdict
  from ctl
union all
select 'MISSING_EXPECTED_ROW', e.table_name, e.column_name, '(whole row)',
       e.data_type||':'||e.is_nullable||':'||e.column_default, '(absent)', 'DIFF'
  from expected e left join actual a using (table_name, column_name) where a.table_name is null
union all
select 'UNEXPECTED_ACTUAL_ROW', a.table_name, a.column_name, '(whole row)',
       '(not expected)', a.data_type||':'||a.is_nullable||':'||a.column_default, 'DIFF'
  from actual a left join expected e using (table_name, column_name) where e.table_name is null
union all
select 'TYPE_MISMATCH', e.table_name, e.column_name, 'data_type', e.data_type, a.data_type, 'DIFF'
  from expected e join actual a using (table_name, column_name) where e.data_type is distinct from a.data_type
union all
select 'NULLABILITY_MISMATCH', e.table_name, e.column_name, 'is_nullable', e.is_nullable, a.is_nullable, 'DIFF'
  from expected e join actual a using (table_name, column_name) where e.is_nullable is distinct from a.is_nullable
union all
select 'DEFAULT_MISMATCH', e.table_name, e.column_name, 'column_default', e.column_default, a.column_default, 'DIFF'
  from expected e join actual a using (table_name, column_name) where e.column_default is distinct from a.column_default
order by 1, 2, 3;

-- ── 2 · DEFAULT EXPRESSION RENDERING — raw catalog vs rendered, NOT normalized ───────────────
select 'DEFAULT_RENDERING' as class, c.relname::text as table_name, a.attname::text as column_name,
       pg_catalog.pg_get_expr(ad.adbin, ad.adrelid)                  as pg_get_expr_rendering,
       ic.column_default                                             as information_schema_rendering,
       (pg_catalog.pg_get_expr(ad.adbin, ad.adrelid) is distinct from ic.column_default) as renderings_differ,
       current_setting('search_path')                                as session_search_path
  from pg_catalog.pg_attrdef ad
  join pg_catalog.pg_class c on c.oid = ad.adrelid
  join pg_catalog.pg_namespace n on n.oid = c.relnamespace
  join pg_catalog.pg_attribute a on a.attrelid = ad.adrelid and a.attnum = ad.adnum
  left join information_schema.columns ic
         on ic.table_schema = 'public' and ic.table_name = c.relname and ic.column_name = a.attname
 where n.nspname = 'public'
 order by 2, 3;

-- ── 3 · TYPE RENDERING — resolved identity vs information_schema.data_type ───────────────────
select 'TYPE_RENDERING' as class, c.relname::text as table_name, a.attname::text as column_name,
       tn.nspname::text                                    as type_schema,
       t.typname::text                                     as type_name,
       pg_catalog.format_type(a.atttypid, a.atttypmod)     as format_type,
       a.atttypmod                                         as typmod,
       t.typtype::text                                     as typtype,
       coalesce(bt.typname::text,'-')                      as domain_base_type,
       ic.data_type                                        as information_schema_data_type,
       a.atttypid::text                                    as type_oid_trace_only
  from pg_catalog.pg_attribute a
  join pg_catalog.pg_class c on c.oid = a.attrelid
  join pg_catalog.pg_namespace n on n.oid = c.relnamespace
  join pg_catalog.pg_type t on t.oid = a.atttypid
  join pg_catalog.pg_namespace tn on tn.oid = t.typnamespace
  left join pg_catalog.pg_type bt on bt.oid = t.typbasetype
  left join information_schema.columns ic
         on ic.table_schema = 'public' and ic.table_name = c.relname and ic.column_name = a.attname
 where n.nspname = 'public' and c.relkind = 'r' and a.attnum > 0 and not a.attisdropped
 order by 2, 3;

-- ── 4 · IDENTITY / GENERATED / COLLATION — NOT part of V2's fingerprint ─────────────────────
select 'IDENTITY_GENERATED_COLLATION' as class, c.relname::text as table_name, a.attname::text as column_name,
       a.attidentity::text  as identity,
       a.attgenerated::text as generated,
       coalesce(col.collname::text,'-') as collation,
       a.attnotnull::text   as attnotnull,
       a.attnum             as ordinal_position
  from pg_catalog.pg_attribute a
  join pg_catalog.pg_class c on c.oid = a.attrelid
  join pg_catalog.pg_namespace n on n.oid = c.relnamespace
  left join pg_catalog.pg_collation col on col.oid = a.attcollation
 where n.nspname = 'public' and c.relkind = 'r' and a.attnum > 0 and not a.attisdropped
   and (a.attidentity <> '' or a.attgenerated <> '' or col.collname is not null)
 order by 2, 3;
